RBE1001Lib: /home/hephaestus/git/ESP32Servo/src/analogWrite.h File Reference
analogWrite.h File Reference
#include <cstdint>
#include <esp32-hal-ledc.h>
#include <Arduino.h>
Macros
#define PWMRANGE 255
Functions
void analogWrite (uint8_t APin, uint16_t AValue)
Macro Definition Documentation
PWMRANGE
#define PWMRANGE 255
Definition at line 7 of file analogWrite.h.
Function Documentation
analogWrite()
void analogWrite (uint8_t APin, uint16_t AValue)
Definition at line 11 of file analogWrite.cpp.
References ESP32PWM::attached(), ESP32PWM::attachPin(), ESP32PWM::detachPin(), pwmFactory(), and ESP32PWM::write().
Referenced by loop().