RBE1001Lib: src/ESPAsyncWebServer/AsyncWebSocket.cpp File Reference
AsyncWebSocket.cpp File Reference
#include "Arduino.h"
#include "AsyncWebSocket.h"
#include <libb64/cencode.h>
Data Structures
struct SHA1_CTX
class AsyncWebSocketControl
Macros
#define MAX_PRINTF_LEN 64
Functions
void SHA1Transform (uint32_t state[5], const unsigned char buffer[64])
void SHA1Init (SHA1_CTX *context)
void SHA1Update (SHA1_CTX *context, const unsigned char *data, uint32_t len)
void SHA1Final (unsigned char digest[20], SHA1_CTX *context)
size_t webSocketSendFrameWindow (AsyncClient *client)
size_t webSocketSendFrame (AsyncClient *client, bool final, uint8_t opcode, bool mask, uint8_t *data, size_t len)
Variables
const char * AWSC_PING_PAYLOAD = "ESPAsyncWebServer-PING"
const size_t AWSC_PING_PAYLOAD_LEN = 22
const char * WS_STR_CONNECTION = "Connection"
const char * WS_STR_UPGRADE = "Upgrade"
const char * WS_STR_ORIGIN = "Origin"
const char * WS_STR_VERSION = "Sec-WebSocket-Version"
const char * WS_STR_KEY = "Sec-WebSocket-Key"
const char * WS_STR_PROTOCOL = "Sec-WebSocket-Protocol"
const char * WS_STR_ACCEPT = "Sec-WebSocket-Accept"
const char * WS_STR_UUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
Macro Definition Documentation
MAX_PRINTF_LEN
#define MAX_PRINTF_LEN 64
Definition at line 43 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketClient::printf(), AsyncWebSocketClient::printf_P(), AsyncWebSocket::printfAll(), and AsyncWebSocket::printfAll_P().
Function Documentation
SHA1Final()
void SHA1Final (unsigned char digest[20], SHA1_CTX * context)
Referenced by AsyncWebSocketResponse::AsyncWebSocketResponse().
SHA1Init()
void SHA1Init (SHA1_CTX * context)
Referenced by AsyncWebSocketResponse::AsyncWebSocketResponse().
SHA1Transform()
void SHA1Transform (uint32_t state[5], const unsigned char buffer[64])
SHA1Update()
void SHA1Update (SHA1_CTX * context, const unsigned char * data, uint32_t len)
Referenced by AsyncWebSocketResponse::AsyncWebSocketResponse().
webSocketSendFrame()
size_t webSocketSendFrame (AsyncClient * client, bool final, uint8_t opcode, bool mask, uint8_t * data, size_t len)
Definition at line 54 of file AsyncWebSocket.cpp.
References AsyncClient::add(), AsyncClient::canSend(), AsyncClient::send(), and AsyncClient::space().
Referenced by AsyncWebSocketBasicMessage::send(), AsyncWebSocketMultiMessage::send(), and AsyncWebSocketControl::send().
webSocketSendFrameWindow()
size_t webSocketSendFrameWindow (AsyncClient * client)
Definition at line 45 of file AsyncWebSocket.cpp.
References AsyncClient::canSend(), and AsyncClient::space().
Referenced by AsyncWebSocketClient::_runQueue(), AsyncWebSocketBasicMessage::send(), and AsyncWebSocketMultiMessage::send().
Variable Documentation
AWSC_PING_PAYLOAD
const char* AWSC_PING_PAYLOAD = "ESPAsyncWebServer-PING"
Definition at line 474 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketClient::_onData(), and AsyncWebSocketClient::_onPoll().
AWSC_PING_PAYLOAD_LEN
const size_t AWSC_PING_PAYLOAD_LEN = 22
Definition at line 475 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketClient::_onData(), and AsyncWebSocketClient::_onPoll().
WS_STR_ACCEPT
const char* WS_STR_ACCEPT = "Sec-WebSocket-Accept"
Definition at line 1165 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketResponse::AsyncWebSocketResponse().
WS_STR_CONNECTION
const char* WS_STR_CONNECTION = "Connection"
Definition at line 1159 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketResponse::AsyncWebSocketResponse(), and AsyncWebSocket::canHandle().
WS_STR_KEY
const char* WS_STR_KEY = "Sec-WebSocket-Key"
Definition at line 1163 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocket::canHandle(), and AsyncWebSocket::handleRequest().
WS_STR_ORIGIN
const char* WS_STR_ORIGIN = "Origin"
Definition at line 1161 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocket::canHandle().
WS_STR_PROTOCOL
const char* WS_STR_PROTOCOL = "Sec-WebSocket-Protocol"
Definition at line 1164 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocket::canHandle(), and AsyncWebSocket::handleRequest().
WS_STR_UPGRADE
const char* WS_STR_UPGRADE = "Upgrade"
Definition at line 1160 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketResponse::AsyncWebSocketResponse(), and AsyncWebSocket::canHandle().
WS_STR_UUID
const char* WS_STR_UUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
Definition at line 1166 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketResponse::AsyncWebSocketResponse().
WS_STR_VERSION
const char* WS_STR_VERSION = "Sec-WebSocket-Version"
Definition at line 1162 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocket::canHandle(), and AsyncWebSocket::handleRequest().