RBE1001Lib: SimpleWebServer Class Reference
SimpleWebServer Class Reference
#include <SimpleWebServer.h>
Public Member Functions
void initialize ()
void handleClient ()
void registerHandler (String url, void(*handler)())
void sendResponse (const String &response)
void sendHTMLResponse (const String &response)
SimpleWebServer ()
Detailed Description
Definition at line 3 of file SimpleWebServer.h.
Constructor & Destructor Documentation
SimpleWebServer()
SimpleWebServer::SimpleWebServer ()
Definition at line 16 of file SimpleWebServer.cpp.
Member Function Documentation
handleClient()
void SimpleWebServer::handleClient ()
Definition at line 45 of file SimpleWebServer.cpp.
References WifiManager::loop(), and server().
Referenced by WebPage::handle().
initialize()
void SimpleWebServer::initialize ()
Definition at line 19 of file SimpleWebServer.cpp.
References Connected, WifiManager::getState(), WifiManager::loop(), server(), and WifiManager::setup().
Referenced by WebPage::initalize().
registerHandler()
void SimpleWebServer::registerHandler (String url, void(*)() handler)
Definition at line 50 of file SimpleWebServer.cpp.
References server().
Referenced by WebPage::initalize().
sendHTMLResponse()
void SimpleWebServer::sendHTMLResponse (const String & response)
Definition at line 41 of file SimpleWebServer.cpp.
References server().
Referenced by WebPage::sendData(), and WebPage::sendStatic().
sendResponse()
void SimpleWebServer::sendResponse (const String & response)
Definition at line 37 of file SimpleWebServer.cpp.
References server().
The documentation for this class was generated from the following files:
src/SimpleWebServer.h
src/SimpleWebServer.cpp