RBE1001Lib: AsyncCallbackWebHandler Class Reference
AsyncCallbackWebHandler Class Reference
#include <WebHandlerImpl.h>
Public Member Functions
AsyncCallbackWebHandler ()
void setUri (const String &uri)
void setMethod (WebRequestMethodComposite method)
void onRequest (ArRequestHandlerFunction fn)
void onUpload (ArUploadHandlerFunction fn)
void onBody (ArBodyHandlerFunction fn)
virtual bool canHandle (AsyncWebServerRequest *request) override final
virtual void handleRequest (AsyncWebServerRequest *request) override final
virtual void handleUpload (AsyncWebServerRequest *request, const String &filename, size_t index, uint8_t *data, size_t len, bool final) override final
virtual void handleBody (AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total) override final
virtual bool isRequestHandlerTrivial () override final
Public Member Functions inherited from AsyncWebHandler
AsyncWebHandler ()
AsyncWebHandler & setFilter (ArRequestFilterFunction fn)
AsyncWebHandler & setAuthentication (const char *username, const char *password)
bool filter (AsyncWebServerRequest *request)
virtual ~AsyncWebHandler ()
virtual bool canHandle (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleRequest (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleUpload (AsyncWebServerRequest *request __attribute__((unused)), const String &filename __attribute__((unused)), size_t index __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), bool final __attribute__((unused)))
virtual void handleBody (AsyncWebServerRequest *request __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), size_t index __attribute__((unused)), size_t total __attribute__((unused)))
Protected Attributes
String _uri
WebRequestMethodComposite _method
ArRequestHandlerFunction _onRequest
ArUploadHandlerFunction _onUpload
ArBodyHandlerFunction _onBody
bool _isRegex
Protected Attributes inherited from AsyncWebHandler
ArRequestFilterFunction _filter
String _username
String _password
Detailed Description
Definition at line 66 of file WebHandlerImpl.h.
Constructor & Destructor Documentation
AsyncCallbackWebHandler()
AsyncCallbackWebHandler::AsyncCallbackWebHandler () inline
Definition at line 76 of file WebHandlerImpl.h.
Member Function Documentation
canHandle()
virtual bool AsyncCallbackWebHandler::canHandle (AsyncWebServerRequest * request) inline final override virtual
Definition at line 86 of file WebHandlerImpl.h.
handleBody()
virtual void AsyncCallbackWebHandler::handleBody (AsyncWebServerRequest * request, uint8_t * data, size_t len, size_t index, size_t total) inline final override virtual
Definition at line 131 of file WebHandlerImpl.h.
handleRequest()
virtual void AsyncCallbackWebHandler::handleRequest (AsyncWebServerRequest * request) inline final override virtual
Definition at line 121 of file WebHandlerImpl.h.
handleUpload()
virtual void AsyncCallbackWebHandler::handleUpload (AsyncWebServerRequest * request, const String & filename, size_t index, uint8_t * data, size_t len, bool final) inline final override virtual
Definition at line 127 of file WebHandlerImpl.h.
isRequestHandlerTrivial()
virtual bool AsyncCallbackWebHandler::isRequestHandlerTrivial () inline final override virtual
Reimplemented from AsyncWebHandler.
Definition at line 135 of file WebHandlerImpl.h.
onBody()
void AsyncCallbackWebHandler::onBody (ArBodyHandlerFunction fn) inline
Definition at line 84 of file WebHandlerImpl.h.
Referenced by AsyncWebServer::on(), AsyncWebServer::onRequestBody(), and AsyncWebServer::reset().
onRequest()
void AsyncCallbackWebHandler::onRequest (ArRequestHandlerFunction fn) inline
Definition at line 82 of file WebHandlerImpl.h.
Referenced by AsyncWebServer::on(), AsyncWebServer::onNotFound(), and AsyncWebServer::reset().
onUpload()
void AsyncCallbackWebHandler::onUpload (ArUploadHandlerFunction fn) inline
Definition at line 83 of file WebHandlerImpl.h.
Referenced by AsyncWebServer::on(), AsyncWebServer::onFileUpload(), and AsyncWebServer::reset().
setMethod()
void AsyncCallbackWebHandler::setMethod (WebRequestMethodComposite method) inline
Definition at line 81 of file WebHandlerImpl.h.
Referenced by AsyncWebServer::on().
setUri()
void AsyncCallbackWebHandler::setUri (const String & uri) inline
Definition at line 77 of file WebHandlerImpl.h.
Referenced by AsyncWebServer::on().
Field Documentation
_isRegex
bool AsyncCallbackWebHandler::_isRegex protected
Definition at line 74 of file WebHandlerImpl.h.
_method
WebRequestMethodComposite AsyncCallbackWebHandler::_method protected
Definition at line 70 of file WebHandlerImpl.h.
Referenced by AsyncWebServerRequest::method().
_onBody
ArBodyHandlerFunction AsyncCallbackWebHandler::_onBody protected
Definition at line 73 of file WebHandlerImpl.h.
_onRequest
ArRequestHandlerFunction AsyncCallbackWebHandler::_onRequest protected
Definition at line 71 of file WebHandlerImpl.h.
_onUpload
ArUploadHandlerFunction AsyncCallbackWebHandler::_onUpload protected
Definition at line 72 of file WebHandlerImpl.h.
_uri
String AsyncCallbackWebHandler::_uri protected
Definition at line 69 of file WebHandlerImpl.h.
The documentation for this class was generated from the following file:
src/ESPAsyncWebServer/WebHandlerImpl.h