RBE1001Lib: AsyncWebHandler Class Reference
AsyncWebHandler Class Reference
#include <ESPAsyncWebServer.h>
Public Member Functions
AsyncWebHandler ()
AsyncWebHandler & setFilter (ArRequestFilterFunction fn)
AsyncWebHandler & setAuthentication (const char *username, const char *password)
bool filter (AsyncWebServerRequest *request)
virtual ~AsyncWebHandler ()
virtual bool canHandle (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleRequest (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleUpload (AsyncWebServerRequest *request __attribute__((unused)), const String &filename __attribute__((unused)), size_t index __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), bool final __attribute__((unused)))
virtual void handleBody (AsyncWebServerRequest *request __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), size_t index __attribute__((unused)), size_t total __attribute__((unused)))
virtual bool isRequestHandlerTrivial ()
Protected Attributes
ArRequestFilterFunction _filter
String _username
String _password
Detailed Description
Definition at line 330 of file ESPAsyncWebServer.h.
Constructor & Destructor Documentation
AsyncWebHandler()
AsyncWebHandler::AsyncWebHandler () inline
Definition at line 336 of file ESPAsyncWebServer.h.
~AsyncWebHandler()
virtual AsyncWebHandler::~AsyncWebHandler () inline virtual
Definition at line 340 of file ESPAsyncWebServer.h.
Member Function Documentation
canHandle()
virtual bool AsyncWebHandler::canHandle (AsyncWebServerRequest *request __attribute__(unused)) inline virtual
Definition at line 341 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServer::_attachHandler().
filter()
bool AsyncWebHandler::filter (AsyncWebServerRequest * request) inline
Definition at line 339 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServer::_attachHandler().
handleBody()
virtual void AsyncWebHandler::handleBody (AsyncWebServerRequest *request __attribute__(unused), uint8_t *data __attribute__(unused), size_t len __attribute__(unused), size_t index __attribute__(unused), size_t total __attribute__(unused)) inline virtual
Definition at line 346 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServerRequest::_onData().
handleRequest()
virtual void AsyncWebHandler::handleRequest (AsyncWebServerRequest *request __attribute__(unused)) inline virtual
Definition at line 344 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServerRequest::_onData(), and AsyncWebServerRequest::_parseLine().
handleUpload()
virtual void AsyncWebHandler::handleUpload (AsyncWebServerRequest *request __attribute__(unused), const String &filename __attribute__(unused), size_t index __attribute__(unused), uint8_t *data __attribute__(unused), size_t len __attribute__(unused), bool final __attribute__(unused)) inline virtual
Definition at line 345 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServerRequest::_handleUploadByte(), and AsyncWebServerRequest::_parseMultipartPostByte().
isRequestHandlerTrivial()
virtual bool AsyncWebHandler::isRequestHandlerTrivial () inline virtual
Reimplemented in AsyncCallbackJsonWebHandler, AsyncCallbackWebHandler, and SPIFFSEditor.
Definition at line 347 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServerRequest::_onData().
setAuthentication()
AsyncWebHandler& AsyncWebHandler::setAuthentication (const char * username, const char * password) inline
Definition at line 338 of file ESPAsyncWebServer.h.
setFilter()
AsyncWebHandler& AsyncWebHandler::setFilter (ArRequestFilterFunction fn) inline
Definition at line 337 of file ESPAsyncWebServer.h.
Field Documentation
_filter
ArRequestFilterFunction AsyncWebHandler::_filter protected
Definition at line 332 of file ESPAsyncWebServer.h.
_password
String AsyncWebHandler::_password protected
Definition at line 334 of file ESPAsyncWebServer.h.
Referenced by AsyncStaticWebHandler::handleRequest(), AsyncEventSource::handleRequest(), and AsyncWebSocket::handleRequest().
_username
String AsyncWebHandler::_username protected
Definition at line 333 of file ESPAsyncWebServer.h.
Referenced by AsyncStaticWebHandler::handleRequest(), AsyncEventSource::handleRequest(), and AsyncWebSocket::handleRequest().
The documentation for this class was generated from the following file:
src/ESPAsyncWebServer/ESPAsyncWebServer.h