RBE1001Lib: AsyncAbstractResponse Class Reference
AsyncAbstractResponse Class Reference
#include <WebResponseImpl.h>
Public Member Functions
AsyncAbstractResponse (AwsTemplateProcessor callback=nullptr)
void _respond (AsyncWebServerRequest *request)
size_t _ack (AsyncWebServerRequest *request, size_t len, uint32_t time)
bool _sourceValid () const
virtual size_t _fillBuffer (uint8_t *buf __attribute__((unused)), size_t maxLen __attribute__((unused)))
Public Member Functions inherited from AsyncWebServerResponse
AsyncWebServerResponse ()
virtual ~AsyncWebServerResponse ()
virtual void setCode (int code)
virtual void setContentLength (size_t len)
virtual void setContentType (const String &type)
virtual void addHeader (const String &name, const String &value)
virtual String _assembleHead (uint8_t version)
virtual bool _started () const
virtual bool _finished () const
virtual bool _failed () const
Protected Attributes
AwsTemplateProcessor _callback
Protected Attributes inherited from AsyncWebServerResponse
int _code
LinkedList< AsyncWebHeader * > _headers
String _contentType
size_t _contentLength
bool _sendContentLength
bool _chunked
size_t _headLength
size_t _sentLength
size_t _ackedLength
size_t _writtenLength
WebResponseState _state
Private Member Functions
size_t _readDataFromCacheOrContent (uint8_t *data, const size_t len)
size_t _fillBufferAndProcessTemplates (uint8_t *buf, size_t maxLen)
Private Attributes
String _head
std::vector< uint8_t > _cache
Additional Inherited Members
Protected Member Functions inherited from AsyncWebServerResponse
const char * _responseCodeToString (int code)
Detailed Description
Definition at line 42 of file WebResponseImpl.h.
Constructor & Destructor Documentation
AsyncAbstractResponse()
AsyncAbstractResponse::AsyncAbstractResponse (AwsTemplateProcessor callback = nullptr)
Definition at line 247 of file WebResponses.cpp.
References AsyncWebServerResponse::_chunked, AsyncWebServerResponse::_contentLength, and AsyncWebServerResponse::_sendContentLength.
Member Function Documentation
_ack()
size_t AsyncAbstractResponse::_ack (AsyncWebServerRequest * request, size_t len, uint32_t time) virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 264 of file WebResponses.cpp.
References AsyncWebServerResponse::_ackedLength, AsyncWebServerResponse::_chunked, AsyncWebServerResponse::_contentLength, _fillBufferAndProcessTemplates(), _head, AsyncWebServerResponse::_sendContentLength, AsyncWebServerResponse::_sentLength, _sourceValid(), AsyncWebServerResponse::_state, AsyncWebServerResponse::_writtenLength, AsyncWebServerRequest::client(), AsyncClient::close(), RESPONSE_CONTENT, RESPONSE_END, RESPONSE_FAILED, RESPONSE_HEADERS, RESPONSE_TRY_AGAIN, RESPONSE_WAIT_ACK, AsyncClient::space(), and AsyncClient::write().
Referenced by _respond().
_fillBuffer()
virtual size_t AsyncAbstractResponse::_fillBuffer (uint8_t *buf __attribute__(unused), size_t maxLen __attribute__(unused)) inline virtual
Definition at line 59 of file WebResponseImpl.h.
Referenced by _fillBufferAndProcessTemplates(), and _readDataFromCacheOrContent().
_fillBufferAndProcessTemplates()
size_t AsyncAbstractResponse::_fillBufferAndProcessTemplates (uint8_t * buf, size_t maxLen) private
Definition at line 381 of file WebResponses.cpp.
References _cache, _callback, _fillBuffer(), _readDataFromCacheOrContent(), memchr(), TEMPLATE_PARAM_NAME_LENGTH, and TEMPLATE_PLACEHOLDER.
Referenced by _ack().
_readDataFromCacheOrContent()
size_t AsyncAbstractResponse::_readDataFromCacheOrContent (uint8_t * data, const size_t len) private
Definition at line 367 of file WebResponses.cpp.
References _cache, and _fillBuffer().
Referenced by _fillBufferAndProcessTemplates().
_respond()
void AsyncAbstractResponse::_respond (AsyncWebServerRequest * request) virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 257 of file WebResponses.cpp.
References _ack(), AsyncWebServerResponse::_assembleHead(), _head, AsyncWebServerResponse::_state, AsyncWebServerResponse::addHeader(), RESPONSE_HEADERS, and AsyncWebServerRequest::version().
_sourceValid()
bool AsyncAbstractResponse::_sourceValid () const inline virtual
Reimplemented from AsyncWebServerResponse.
Reimplemented in AsyncResponseStream, AsyncProgmemResponse, AsyncChunkedResponse, AsyncCallbackResponse, AsyncStreamResponse, and AsyncFileResponse.
Definition at line 58 of file WebResponseImpl.h.
Referenced by _ack().
Field Documentation
_cache
std::vector<uint8_t> AsyncAbstractResponse::_cache private
Definition at line 49 of file WebResponseImpl.h.
Referenced by _fillBufferAndProcessTemplates(), and _readDataFromCacheOrContent().
_callback
AwsTemplateProcessor AsyncAbstractResponse::_callback protected
Definition at line 53 of file WebResponseImpl.h.
Referenced by _fillBufferAndProcessTemplates(), and AsyncFileResponse::AsyncFileResponse().
_head
String AsyncAbstractResponse::_head private
Definition at line 44 of file WebResponseImpl.h.
Referenced by _ack(), and _respond().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/WebResponseImpl.h
src/ESPAsyncWebServer/WebResponses.cpp