RBE1001Lib: AsyncWebHeader Class Reference
AsyncWebHeader Class Reference
#include <ESPAsyncWebServer.h>
Public Member Functions
AsyncWebHeader (const String &name, const String &value)
AsyncWebHeader (const String &data)
~AsyncWebHeader ()
const String & name () const
const String & value () const
String toString () const
Private Attributes
String _name
String _value
Detailed Description
Definition at line 105 of file ESPAsyncWebServer.h.
Constructor & Destructor Documentation
AsyncWebHeader() [1/2]
AsyncWebHeader::AsyncWebHeader (const String & name, const String & value) inline
Definition at line 111 of file ESPAsyncWebServer.h.
AsyncWebHeader() [2/2]
AsyncWebHeader::AsyncWebHeader (const String & data) inline
Definition at line 112 of file ESPAsyncWebServer.h.
~AsyncWebHeader()
AsyncWebHeader::~AsyncWebHeader () inline
Definition at line 119 of file ESPAsyncWebServer.h.
Member Function Documentation
name()
const String& AsyncWebHeader::name () const inline
Definition at line 120 of file ESPAsyncWebServer.h.
References AsyncWebParameter::_name.
Referenced by AsyncWebServerRequest::headerName().
toString()
String AsyncWebHeader::toString () const inline
Definition at line 122 of file ESPAsyncWebServer.h.
value()
const String& AsyncWebHeader::value () const inline
Definition at line 121 of file ESPAsyncWebServer.h.
References AsyncWebParameter::_value.
Referenced by AsyncWebSocket::handleRequest(), and AsyncWebServerRequest::header().
Field Documentation
_name
String AsyncWebHeader::_name private
Definition at line 107 of file ESPAsyncWebServer.h.
_value
String AsyncWebHeader::_value private
Definition at line 108 of file ESPAsyncWebServer.h.
The documentation for this class was generated from the following file:
src/ESPAsyncWebServer/ESPAsyncWebServer.h