RBE1001Lib: AsyncWebSocketMessageBuffer Class Reference
AsyncWebSocketMessageBuffer Class Reference
#include <AsyncWebSocket.h>
Public Member Functions
AsyncWebSocketMessageBuffer ()
AsyncWebSocketMessageBuffer (size_t size)
AsyncWebSocketMessageBuffer (uint8_t *data, size_t size)
AsyncWebSocketMessageBuffer (const AsyncWebSocketMessageBuffer &)
AsyncWebSocketMessageBuffer (AsyncWebSocketMessageBuffer &&)
~AsyncWebSocketMessageBuffer ()
void operator++ (int i)
void operator-- (int i)
bool reserve (size_t size)
void lock ()
void unlock ()
uint8_t * get ()
size_t length ()
uint32_t count ()
bool canDelete ()
Data Fields
friend AsyncWebSocket
Private Attributes
uint8_t * _data
size_t _len
bool _lock
uint32_t _count
Detailed Description
Definition at line 83 of file AsyncWebSocket.h.
Constructor & Destructor Documentation
AsyncWebSocketMessageBuffer() [1/5]
AsyncWebSocketMessageBuffer::AsyncWebSocketMessageBuffer ()
Definition at line 129 of file AsyncWebSocket.cpp.
AsyncWebSocketMessageBuffer() [2/5]
AsyncWebSocketMessageBuffer::AsyncWebSocketMessageBuffer (size_t size)
Definition at line 158 of file AsyncWebSocket.cpp.
References _data, and _len.
AsyncWebSocketMessageBuffer() [3/5]
AsyncWebSocketMessageBuffer::AsyncWebSocketMessageBuffer (uint8_t * data, size_t size)
Definition at line 138 of file AsyncWebSocket.cpp.
References _data, and _len.
AsyncWebSocketMessageBuffer() [4/5]
AsyncWebSocketMessageBuffer::AsyncWebSocketMessageBuffer (const AsyncWebSocketMessageBuffer & copy)
Definition at line 172 of file AsyncWebSocket.cpp.
References _count, _data, _len, and _lock.
AsyncWebSocketMessageBuffer() [5/5]
AsyncWebSocketMessageBuffer::AsyncWebSocketMessageBuffer (AsyncWebSocketMessageBuffer && copy)
Definition at line 194 of file AsyncWebSocket.cpp.
References _count, _data, _len, and _lock.
~AsyncWebSocketMessageBuffer()
AsyncWebSocketMessageBuffer::~AsyncWebSocketMessageBuffer ()
Definition at line 211 of file AsyncWebSocket.cpp.
References _data.
Member Function Documentation
canDelete()
bool AsyncWebSocketMessageBuffer::canDelete () inline
Definition at line 105 of file AsyncWebSocket.h.
count()
uint32_t AsyncWebSocketMessageBuffer::count () inline
Definition at line 104 of file AsyncWebSocket.h.
get()
uint8_t* AsyncWebSocketMessageBuffer::get () inline
Definition at line 102 of file AsyncWebSocket.h.
References AsyncWebSocketControl::_data.
Referenced by AsyncWebSocketMultiMessage::AsyncWebSocketMultiMessage(), AsyncWebSocket::printfAll(), and AsyncWebSocket::printfAll_P().
length()
size_t AsyncWebSocketMessageBuffer::length () inline
Definition at line 103 of file AsyncWebSocket.h.
References AsyncWebSocketControl::_len.
Referenced by AsyncWebSocketMultiMessage::AsyncWebSocketMultiMessage().
lock()
void AsyncWebSocketMessageBuffer::lock () inline
Definition at line 100 of file AsyncWebSocket.h.
Referenced by AsyncWebSocket::binaryAll(), and AsyncWebSocket::textAll().
operator++()
void AsyncWebSocketMessageBuffer::operator++ (int i) inline
Definition at line 97 of file AsyncWebSocket.h.
operator--()
void AsyncWebSocketMessageBuffer::operator-- (int i) inline
Definition at line 98 of file AsyncWebSocket.h.
reserve()
bool AsyncWebSocketMessageBuffer::reserve (size_t size)
Definition at line 218 of file AsyncWebSocket.cpp.
References _data, and _len.
unlock()
void AsyncWebSocketMessageBuffer::unlock () inline
Definition at line 101 of file AsyncWebSocket.h.
Referenced by AsyncWebSocket::binaryAll(), and AsyncWebSocket::textAll().
Field Documentation
_count
uint32_t AsyncWebSocketMessageBuffer::_count private
Definition at line 88 of file AsyncWebSocket.h.
Referenced by AsyncWebSocketMessageBuffer().
_data
uint8_t* AsyncWebSocketMessageBuffer::_data private
Definition at line 85 of file AsyncWebSocket.h.
Referenced by AsyncWebSocketMessageBuffer(), reserve(), and ~AsyncWebSocketMessageBuffer().
_len
size_t AsyncWebSocketMessageBuffer::_len private
Definition at line 86 of file AsyncWebSocket.h.
Referenced by AsyncWebSocketMessageBuffer(), and reserve().
_lock
bool AsyncWebSocketMessageBuffer::_lock private
Definition at line 87 of file AsyncWebSocket.h.
Referenced by AsyncWebSocketMessageBuffer().
AsyncWebSocket
friend AsyncWebSocketMessageBuffer::AsyncWebSocket
Definition at line 107 of file AsyncWebSocket.h.
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/AsyncWebSocket.h
src/ESPAsyncWebServer/AsyncWebSocket.cpp