RBE1001Lib: AsyncBasicResponse Class Reference
AsyncBasicResponse Class Reference
#include <WebResponseImpl.h>
Public Member Functions
AsyncBasicResponse (int code, const String &contentType=String(), const String &content=String())
void _respond (AsyncWebServerRequest *request)
size_t _ack (AsyncWebServerRequest *request, size_t len, uint32_t time)
bool _sourceValid () const
Public Member Functions inherited from AsyncWebServerResponse
AsyncWebServerResponse ()
virtual ~AsyncWebServerResponse ()
virtual void setCode (int code)
virtual void setContentLength (size_t len)
virtual void setContentType (const String &type)
virtual void addHeader (const String &name, const String &value)
virtual String _assembleHead (uint8_t version)
virtual bool _started () const
virtual bool _finished () const
virtual bool _failed () const
Private Attributes
String _content
Additional Inherited Members
Protected Member Functions inherited from AsyncWebServerResponse
const char * _responseCodeToString (int code)
Protected Attributes inherited from AsyncWebServerResponse
int _code
LinkedList< AsyncWebHeader * > _headers
String _contentType
size_t _contentLength
bool _sendContentLength
bool _chunked
size_t _headLength
size_t _sentLength
size_t _ackedLength
size_t _writtenLength
WebResponseState _state
Detailed Description
Definition at line 32 of file WebResponseImpl.h.
Constructor & Destructor Documentation
AsyncBasicResponse()
AsyncBasicResponse::AsyncBasicResponse (int code, const String & contentType = String(), const String & content = String())
Definition at line 169 of file WebResponses.cpp.
References AsyncWebServerResponse::_code, AsyncWebServerResponse::_contentLength, AsyncWebServerResponse::_contentType, and AsyncWebServerResponse::addHeader().
Member Function Documentation
_ack()
size_t AsyncBasicResponse::_ack (AsyncWebServerRequest * request, size_t len, uint32_t time) virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 215 of file WebResponses.cpp.
References AsyncWebServerResponse::_ackedLength, AsyncWebServerResponse::_contentLength, AsyncWebServerResponse::_sentLength, AsyncWebServerResponse::_state, AsyncWebServerResponse::_writtenLength, AsyncWebServerRequest::client(), RESPONSE_CONTENT, RESPONSE_END, RESPONSE_WAIT_ACK, AsyncClient::space(), and AsyncClient::write().
_respond()
void AsyncBasicResponse::_respond (AsyncWebServerRequest * request) virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 181 of file WebResponses.cpp.
References AsyncWebServerResponse::_assembleHead(), AsyncWebServerResponse::_contentLength, AsyncWebServerResponse::_sentLength, AsyncWebServerResponse::_state, AsyncWebServerResponse::_writtenLength, AsyncWebServerRequest::client(), RESPONSE_CONTENT, RESPONSE_HEADERS, RESPONSE_WAIT_ACK, AsyncClient::space(), AsyncWebServerRequest::version(), and AsyncClient::write().
_sourceValid()
bool AsyncBasicResponse::_sourceValid () const inline virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 39 of file WebResponseImpl.h.
Field Documentation
_content
String AsyncBasicResponse::_content private
Definition at line 34 of file WebResponseImpl.h.
Referenced by AsyncFileResponse::_sourceValid(), AsyncStreamResponse::_sourceValid(), AsyncCallbackResponse::_sourceValid(), and AsyncChunkedResponse::_sourceValid().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/WebResponseImpl.h
src/ESPAsyncWebServer/WebResponses.cpp