RBE1001Lib: AsyncEventSourceResponse Class Reference
AsyncEventSourceResponse Class Reference
#include <AsyncEventSource.h>
Public Member Functions
AsyncEventSourceResponse (AsyncEventSource *server)
void _respond (AsyncWebServerRequest *request)
size_t _ack (AsyncWebServerRequest *request, size_t len, uint32_t time)
bool _sourceValid () const
Public Member Functions inherited from AsyncWebServerResponse
AsyncWebServerResponse ()
virtual ~AsyncWebServerResponse ()
virtual void setCode (int code)
virtual void setContentLength (size_t len)
virtual void setContentType (const String &type)
virtual void addHeader (const String &name, const String &value)
virtual String _assembleHead (uint8_t version)
virtual bool _started () const
virtual bool _finished () const
virtual bool _failed () const
Private Attributes
String _content
AsyncEventSource * _server
Additional Inherited Members
Protected Member Functions inherited from AsyncWebServerResponse
const char * _responseCodeToString (int code)
Protected Attributes inherited from AsyncWebServerResponse
int _code
LinkedList< AsyncWebHeader * > _headers
String _contentType
size_t _contentLength
bool _sendContentLength
bool _chunked
size_t _headLength
size_t _sentLength
size_t _ackedLength
size_t _writtenLength
WebResponseState _state
Detailed Description
Definition at line 121 of file AsyncEventSource.h.
Constructor & Destructor Documentation
AsyncEventSourceResponse()
AsyncEventSourceResponse::AsyncEventSourceResponse (AsyncEventSource * server)
Definition at line 347 of file AsyncEventSource.cpp.
References server.
Member Function Documentation
_ack()
size_t AsyncEventSourceResponse::_ack (AsyncWebServerRequest * request, size_t len, uint32_t time) virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 362 of file AsyncEventSource.cpp.
_respond()
void AsyncEventSourceResponse::_respond (AsyncWebServerRequest * request) virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 356 of file AsyncEventSource.cpp.
References AsyncWebServerRequest::client(), RESPONSE_WAIT_ACK, AsyncWebServerRequest::version(), and AsyncClient::write().
_sourceValid()
bool AsyncEventSourceResponse::_sourceValid () const inline virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 129 of file AsyncEventSource.h.
Field Documentation
_content
String AsyncEventSourceResponse::_content private
Definition at line 123 of file AsyncEventSource.h.
_server
AsyncEventSource* AsyncEventSourceResponse::_server private
Definition at line 124 of file AsyncEventSource.h.
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/AsyncEventSource.h
src/ESPAsyncWebServer/AsyncEventSource.cpp