RBE1001Lib: LinkedList< T, Item > Class Template Reference
LinkedList< T, Item > Class Template Reference
#include <StringArray.h>
Data Structures
class Iterator
Public Types
typedef Item< T > ItemType
typedef std::function< void(const T &)> OnRemove
typedef std::function< bool(const T &)> Predicate
typedef const Iterator ConstIterator
Public Member Functions
ConstIterator begin () const
ConstIterator end () const
LinkedList (OnRemove onRemove)
~LinkedList ()
void add (const T &t)
T & front () const
bool isEmpty () const
size_t length () const
size_t count_if (Predicate predicate) const
const T * nth (size_t N) const
bool remove (const T &t)
bool remove_first (Predicate predicate)
void free ()
Private Attributes
ItemType * _root
OnRemove _onRemove
Detailed Description
template<typename T, template< typename > class Item = LinkedListNode>
class LinkedList< T, Item >
Definition at line 39 of file StringArray.h.
Member Typedef Documentation
ConstIterator
template<typename T, template< typename > class Item = LinkedListNode> typedef const Iterator LinkedList< T, Item >::ConstIterator
Definition at line 60 of file StringArray.h.
ItemType
template<typename T, template< typename > class Item = LinkedListNode> typedef Item<T> LinkedList< T, Item >::ItemType
Definition at line 41 of file StringArray.h.
OnRemove
template<typename T, template< typename > class Item = LinkedListNode> typedef std::function<void(const T&)> LinkedList< T, Item >::OnRemove
Definition at line 42 of file StringArray.h.
Predicate
template<typename T, template< typename > class Item = LinkedListNode> typedef std::function<bool(const T&)> LinkedList< T, Item >::Predicate
Definition at line 43 of file StringArray.h.
Constructor & Destructor Documentation
LinkedList()
template<typename T, template< typename > class Item = LinkedListNode> LinkedList< T, Item >::LinkedList (OnRemove onRemove) inline
Definition at line 64 of file StringArray.h.
~LinkedList()
template<typename T, template< typename > class Item = LinkedListNode> LinkedList< T, Item >::~LinkedList () inline
Definition at line 65 of file StringArray.h.
Member Function Documentation
add()
template<typename T, template< typename > class Item = LinkedListNode> void LinkedList< T, Item >::add (const T & t) inline
Definition at line 66 of file StringArray.h.
Referenced by AsyncEventSource::_addClient(), AsyncWebSocket::_addClient(), AsyncWebServerRequest::_addParam(), AsyncWebServerRequest::_addPathParam(), AsyncWebServerRequest::_parseReqHeader(), AsyncWebSocketClient::_queueControl(), AsyncEventSourceClient::_queueMessage(), AsyncWebSocketClient::_queueMessage(), AsyncWebServer::addHandler(), AsyncWebServerResponse::addHeader(), DefaultHeaders::addHeader(), AsyncWebServerRequest::addInterestingHeader(), AsyncWebServer::addRewrite(), AsyncWebServerResponse::AsyncWebServerResponse(), and AsyncWebSocket::makeBuffer().
begin()
template<typename T, template< typename > class Item = LinkedListNode> ConstIterator LinkedList< T, Item >::begin () const inline
Definition at line 61 of file StringArray.h.
Referenced by AsyncEventSourceClient::_runQueue(), and DefaultHeaders::begin().
count_if()
template<typename T, template< typename > class Item = LinkedListNode> size_t LinkedList< T, Item >::count_if (Predicate predicate) const inline
Definition at line 92 of file StringArray.h.
Referenced by AsyncEventSource::count(), and AsyncWebSocket::count().
end()
template<typename T, template< typename > class Item = LinkedListNode> ConstIterator LinkedList< T, Item >::end () const inline
Definition at line 62 of file StringArray.h.
Referenced by AsyncEventSourceClient::_runQueue(), and DefaultHeaders::end().
free()
template<typename T, template< typename > class Item = LinkedListNode> void LinkedList< T, Item >::free () inline
Definition at line 161 of file StringArray.h.
Referenced by AsyncWebServer::reset(), AsyncEventSourceClient::~AsyncEventSourceClient(), AsyncWebServerRequest::~AsyncWebServerRequest(), AsyncWebServerResponse::~AsyncWebServerResponse(), and AsyncWebSocketClient::~AsyncWebSocketClient().
front()
template<typename T, template< typename > class Item = LinkedListNode> T& LinkedList< T, Item >::front () const inline
Definition at line 76 of file StringArray.h.
Referenced by AsyncEventSourceClient::_onAck(), AsyncWebSocketClient::_onAck(), AsyncEventSourceClient::_runQueue(), AsyncWebSocketClient::_runQueue(), and AsyncWebSocket::cleanupClients().
isEmpty()
template<typename T, template< typename > class Item = LinkedListNode> bool LinkedList< T, Item >::isEmpty () const inline
Definition at line 80 of file StringArray.h.
Referenced by AsyncEventSourceClient::_onAck(), AsyncWebSocketClient::_onAck(), AsyncEventSourceClient::_onPoll(), AsyncWebSocketClient::_onPoll(), AsyncEventSourceClient::_runQueue(), AsyncWebSocketClient::_runQueue(), and AsyncEventSource::avgPacketsWaiting().
length()
template<typename T, template< typename > class Item = LinkedListNode> size_t LinkedList< T, Item >::length () const inline
Definition at line 83 of file StringArray.h.
Referenced by AsyncEventSourceClient::_queueMessage(), AsyncWebSocketClient::_queueMessage(), AsyncWebSocketClient::canSend(), AsyncWebServerRequest::headers(), AsyncEventSourceClient::packetsWaiting(), AsyncWebServerRequest::params(), and AsyncWebSocketClient::queueIsFull().
nth()
template<typename T, template< typename > class Item = LinkedListNode> const T* LinkedList< T, Item >::nth (size_t N) const inline
Definition at line 106 of file StringArray.h.
Referenced by AsyncWebServerRequest::getHeader(), AsyncWebServerRequest::getParam(), and AsyncWebServerRequest::pathArg().
remove()
template<typename T, template< typename > class Item = LinkedListNode> bool LinkedList< T, Item >::remove (const T & t) inline
Definition at line 116 of file StringArray.h.
Referenced by AsyncEventSource::_handleDisconnect(), AsyncEventSourceClient::_onAck(), AsyncWebSocketClient::_onAck(), AsyncEventSourceClient::_runQueue(), AsyncWebSocketClient::_runQueue(), AsyncWebServer::removeHandler(), and AsyncWebServer::removeRewrite().
remove_first()
template<typename T, template< typename > class Item = LinkedListNode> bool LinkedList< T, Item >::remove_first (Predicate predicate) inline
Definition at line 139 of file StringArray.h.
Referenced by AsyncWebSocket::_handleDisconnect().
Field Documentation
_onRemove
template<typename T, template< typename > class Item = LinkedListNode> OnRemove LinkedList< T, Item >::_onRemove private
Definition at line 46 of file StringArray.h.
_root
template<typename T, template< typename > class Item = LinkedListNode> ItemType* LinkedList< T, Item >::_root private
Definition at line 45 of file StringArray.h.
The documentation for this class was generated from the following file:
src/ESPAsyncWebServer/StringArray.h