RBE1001Lib: AsyncEventSource Class Reference
AsyncEventSource Class Reference
#include <AsyncEventSource.h>
Public Member Functions
AsyncEventSource (const String &url)
~AsyncEventSource ()
const char * url () const
void close ()
void onConnect (ArEventHandlerFunction cb)
void send (const char *message, const char *event=NULL, uint32_t id=0, uint32_t reconnect=0)
size_t count () const
size_t avgPacketsWaiting () const
void _addClient (AsyncEventSourceClient *client)
void _handleDisconnect (AsyncEventSourceClient *client)
virtual bool canHandle (AsyncWebServerRequest *request) override final
virtual void handleRequest (AsyncWebServerRequest *request) override final
Public Member Functions inherited from AsyncWebHandler
AsyncWebHandler ()
AsyncWebHandler & setFilter (ArRequestFilterFunction fn)
AsyncWebHandler & setAuthentication (const char *username, const char *password)
bool filter (AsyncWebServerRequest *request)
virtual ~AsyncWebHandler ()
virtual bool canHandle (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleRequest (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleUpload (AsyncWebServerRequest *request __attribute__((unused)), const String &filename __attribute__((unused)), size_t index __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), bool final __attribute__((unused)))
virtual void handleBody (AsyncWebServerRequest *request __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), size_t index __attribute__((unused)), size_t total __attribute__((unused)))
virtual bool isRequestHandlerTrivial ()
Private Attributes
String _url
LinkedList< AsyncEventSourceClient * > _clients
ArEventHandlerFunction _connectcb
Additional Inherited Members
Protected Attributes inherited from AsyncWebHandler
ArRequestFilterFunction _filter
String _username
String _password
Detailed Description
Definition at line 98 of file AsyncEventSource.h.
Constructor & Destructor Documentation
AsyncEventSource()
AsyncEventSource::AsyncEventSource (const String & url)
Definition at line 252 of file AsyncEventSource.cpp.
References _connectcb.
~AsyncEventSource()
AsyncEventSource::~AsyncEventSource ()
Definition at line 258 of file AsyncEventSource.cpp.
References close().
Member Function Documentation
_addClient()
void AsyncEventSource::_addClient (AsyncEventSourceClient * client)
Definition at line 266 of file AsyncEventSource.cpp.
References _clients, _connectcb, and LinkedList< T, Item >::add().
Referenced by AsyncEventSourceClient::AsyncEventSourceClient().
_handleDisconnect()
void AsyncEventSource::_handleDisconnect (AsyncEventSourceClient * client)
Definition at line 285 of file AsyncEventSource.cpp.
References _clients, and LinkedList< T, Item >::remove().
Referenced by AsyncEventSourceClient::_onDisconnect().
avgPacketsWaiting()
size_t AsyncEventSource::avgPacketsWaiting () const
Definition at line 297 of file AsyncEventSource.cpp.
References _clients, and LinkedList< T, Item >::isEmpty().
canHandle()
bool AsyncEventSource::canHandle (AsyncWebServerRequest * request) final override virtual
Definition at line 331 of file AsyncEventSource.cpp.
References _url, AsyncWebServerRequest::addInterestingHeader(), HTTP_GET, AsyncWebServerRequest::method(), and AsyncWebServerRequest::url().
close()
void AsyncEventSource::close ()
Definition at line 289 of file AsyncEventSource.cpp.
References _clients.
Referenced by ~AsyncEventSource().
count()
size_t AsyncEventSource::count () const
Definition at line 325 of file AsyncEventSource.cpp.
References _clients, AsyncEventSourceClient::connected(), and LinkedList< T, Item >::count_if().
handleRequest()
void AsyncEventSource::handleRequest (AsyncWebServerRequest * request) final override virtual
Definition at line 339 of file AsyncEventSource.cpp.
References AsyncWebHandler::_password, AsyncWebHandler::_username, AsyncWebServerRequest::authenticate(), AsyncWebServerRequest::requestAuthentication(), and AsyncWebServerRequest::send().
onConnect()
void AsyncEventSource::onConnect (ArEventHandlerFunction cb)
Definition at line 262 of file AsyncEventSource.cpp.
References _connectcb.
send()
void AsyncEventSource::send (const char * message, const char * event = NULL, uint32_t id = 0, uint32_t reconnect = 0)
Definition at line 314 of file AsyncEventSource.cpp.
References _clients, and generateEventMessage().
url()
const char* AsyncEventSource::url () const inline
Definition at line 107 of file AsyncEventSource.h.
References reconnect, and AsyncEventSourceMessage::send().
Field Documentation
_clients
LinkedList<AsyncEventSourceClient *> AsyncEventSource::_clients private
Definition at line 101 of file AsyncEventSource.h.
Referenced by _addClient(), _handleDisconnect(), avgPacketsWaiting(), close(), count(), and send().
_connectcb
ArEventHandlerFunction AsyncEventSource::_connectcb private
Definition at line 102 of file AsyncEventSource.h.
Referenced by _addClient(), AsyncEventSource(), and onConnect().
_url
String AsyncEventSource::_url private
Definition at line 100 of file AsyncEventSource.h.
Referenced by canHandle().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/AsyncEventSource.h
src/ESPAsyncWebServer/AsyncEventSource.cpp