RBE1001Lib: AsyncWebSocketResponse Class Reference
AsyncWebSocketResponse Class Reference
#include <AsyncWebSocket.h>
Public Member Functions
AsyncWebSocketResponse (const String &key, AsyncWebSocket *server)
void _respond (AsyncWebServerRequest *request)
size_t _ack (AsyncWebServerRequest *request, size_t len, uint32_t time)
bool _sourceValid () const
Public Member Functions inherited from AsyncWebServerResponse
AsyncWebServerResponse ()
virtual ~AsyncWebServerResponse ()
virtual void setCode (int code)
virtual void setContentLength (size_t len)
virtual void setContentType (const String &type)
virtual void addHeader (const String &name, const String &value)
virtual String _assembleHead (uint8_t version)
virtual bool _started () const
virtual bool _finished () const
virtual bool _failed () const
Private Attributes
String _content
AsyncWebSocket * _server
Additional Inherited Members
Protected Member Functions inherited from AsyncWebServerResponse
const char * _responseCodeToString (int code)
Protected Attributes inherited from AsyncWebServerResponse
int _code
LinkedList< AsyncWebHeader * > _headers
String _contentType
size_t _contentLength
bool _sendContentLength
bool _chunked
size_t _headLength
size_t _sentLength
size_t _ackedLength
size_t _writtenLength
WebResponseState _state
Detailed Description
Definition at line 338 of file AsyncWebSocket.h.
Constructor & Destructor Documentation
AsyncWebSocketResponse()
AsyncWebSocketResponse::AsyncWebSocketResponse (const String & key, AsyncWebSocket * server)
Definition at line 1251 of file AsyncWebSocket.cpp.
References RESPONSE_FAILED, server, SHA1Final(), SHA1Init(), SHA1Update(), WS_STR_ACCEPT, WS_STR_CONNECTION, WS_STR_UPGRADE, and WS_STR_UUID.
Member Function Documentation
_ack()
size_t AsyncWebSocketResponse::_ack (AsyncWebServerRequest * request, size_t len, uint32_t time) virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 1297 of file AsyncWebSocket.cpp.
_respond()
void AsyncWebSocketResponse::_respond (AsyncWebServerRequest * request) virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 1287 of file AsyncWebSocket.cpp.
References AsyncWebServerRequest::client(), AsyncClient::close(), RESPONSE_FAILED, RESPONSE_WAIT_ACK, AsyncWebServerRequest::version(), and AsyncClient::write().
_sourceValid()
bool AsyncWebSocketResponse::_sourceValid () const inline virtual
Reimplemented from AsyncWebServerResponse.
Definition at line 346 of file AsyncWebSocket.h.
Field Documentation
_content
String AsyncWebSocketResponse::_content private
Definition at line 340 of file AsyncWebSocket.h.
_server
AsyncWebSocket* AsyncWebSocketResponse::_server private
Definition at line 341 of file AsyncWebSocket.h.
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/AsyncWebSocket.h
src/ESPAsyncWebServer/AsyncWebSocket.cpp