RBE1001Lib: AsyncFileResponse Class Reference
AsyncFileResponse Class Reference
#include <WebResponseImpl.h>
Public Member Functions
AsyncFileResponse (FS &fs, const String &path, const String &contentType=String(), bool download=false, AwsTemplateProcessor callback=nullptr)
AsyncFileResponse (File content, const String &path, const String &contentType=String(), bool download=false, AwsTemplateProcessor callback=nullptr)
~AsyncFileResponse ()
bool _sourceValid () const
virtual size_t _fillBuffer (uint8_t *buf, size_t maxLen) override
Public Member Functions inherited from AsyncAbstractResponse
AsyncAbstractResponse (AwsTemplateProcessor callback=nullptr)
void _respond (AsyncWebServerRequest *request)
size_t _ack (AsyncWebServerRequest *request, size_t len, uint32_t time)
virtual size_t _fillBuffer (uint8_t *buf __attribute__((unused)), size_t maxLen __attribute__((unused)))
Public Member Functions inherited from AsyncWebServerResponse
AsyncWebServerResponse ()
virtual ~AsyncWebServerResponse ()
virtual void setCode (int code)
virtual void setContentLength (size_t len)
virtual void setContentType (const String &type)
virtual void addHeader (const String &name, const String &value)
virtual String _assembleHead (uint8_t version)
virtual bool _started () const
virtual bool _finished () const
virtual bool _failed () const
Private Types
using File = fs::File
using FS = fs::FS
Private Member Functions
void _setContentType (const String &path)
Private Attributes
File _content
String _path
Additional Inherited Members
Protected Member Functions inherited from AsyncWebServerResponse
const char * _responseCodeToString (int code)
Protected Attributes inherited from AsyncAbstractResponse
AwsTemplateProcessor _callback
Protected Attributes inherited from AsyncWebServerResponse
int _code
LinkedList< AsyncWebHeader * > _headers
String _contentType
size_t _contentLength
bool _sendContentLength
bool _chunked
size_t _headLength
size_t _sentLength
size_t _ackedLength
size_t _writtenLength
WebResponseState _state
Detailed Description
Definition at line 67 of file WebResponseImpl.h.
Member Typedef Documentation
File
using AsyncFileResponse::File = fs::File private
Definition at line 68 of file WebResponseImpl.h.
FS
using AsyncFileResponse::FS = fs::FS private
Definition at line 69 of file WebResponseImpl.h.
Constructor & Destructor Documentation
AsyncFileResponse() [1/2]
AsyncFileResponse::AsyncFileResponse (FS & fs, const String & path, const String & contentType = String(), bool download = false, AwsTemplateProcessor callback = nullptr)
Definition at line 507 of file WebResponses.cpp.
References AsyncAbstractResponse::_callback, AsyncWebServerResponse::_chunked, AsyncWebServerResponse::_code, _content, AsyncWebServerResponse::_contentLength, AsyncWebServerResponse::_contentType, _path, AsyncWebServerResponse::_sendContentLength, _setContentType(), and AsyncWebServerResponse::addHeader().
AsyncFileResponse() [2/2]
AsyncFileResponse::AsyncFileResponse (File content, const String & path, const String & contentType = String(), bool download = false, AwsTemplateProcessor callback = nullptr)
Definition at line 541 of file WebResponses.cpp.
References AsyncAbstractResponse::_callback, AsyncWebServerResponse::_chunked, AsyncWebServerResponse::_code, _content, AsyncWebServerResponse::_contentLength, AsyncWebServerResponse::_contentType, _path, AsyncWebServerResponse::_sendContentLength, _setContentType(), and AsyncWebServerResponse::addHeader().
~AsyncFileResponse()
AsyncFileResponse::~AsyncFileResponse ()
Definition at line 480 of file WebResponses.cpp.
Member Function Documentation
_fillBuffer()
size_t AsyncFileResponse::_fillBuffer (uint8_t * buf, size_t maxLen) override virtual
Definition at line 572 of file WebResponses.cpp.
References _content.
_setContentType()
void AsyncFileResponse::_setContentType (const String & path) private
Definition at line 485 of file WebResponses.cpp.
References AsyncWebServerResponse::_contentType.
Referenced by AsyncFileResponse().
_sourceValid()
bool AsyncFileResponse::_sourceValid () const inline virtual
Reimplemented from AsyncAbstractResponse.
Definition at line 78 of file WebResponseImpl.h.
References AsyncBasicResponse::_content.
Field Documentation
_content
File AsyncFileResponse::_content private
Definition at line 71 of file WebResponseImpl.h.
Referenced by _fillBuffer(), and AsyncFileResponse().
_path
String AsyncFileResponse::_path private
Definition at line 72 of file WebResponseImpl.h.
Referenced by AsyncFileResponse().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/WebResponseImpl.h
src/ESPAsyncWebServer/WebResponses.cpp