RBE1001Lib: AsyncWebParameter Class Reference
AsyncWebParameter Class Reference
#include <ESPAsyncWebServer.h>
Public Member Functions
AsyncWebParameter (const String &name, const String &value, bool form=false, bool file=false, size_t size=0)
const String & name () const
const String & value () const
size_t size () const
bool isPost () const
bool isFile () const
Private Attributes
String _name
String _value
size_t _size
bool _isForm
bool _isFile
Detailed Description
Definition at line 83 of file ESPAsyncWebServer.h.
Constructor & Destructor Documentation
AsyncWebParameter()
AsyncWebParameter::AsyncWebParameter (const String & name, const String & value, bool form = false, bool file = false, size_t size = 0) inline
Definition at line 93 of file ESPAsyncWebServer.h.
Member Function Documentation
isFile()
bool AsyncWebParameter::isFile () const inline
Definition at line 98 of file ESPAsyncWebServer.h.
References _isFile.
Referenced by AsyncWebServerRequest::getParam(), and AsyncWebServerRequest::hasParam().
isPost()
bool AsyncWebParameter::isPost () const inline
Definition at line 97 of file ESPAsyncWebServer.h.
References _isForm.
Referenced by AsyncWebServerRequest::getParam(), and AsyncWebServerRequest::hasParam().
name()
const String& AsyncWebParameter::name () const inline
Definition at line 94 of file ESPAsyncWebServer.h.
References _name.
Referenced by AsyncWebServerRequest::argName(), AsyncWebServerRequest::getParam(), AsyncWebServerRequest::hasParam(), and AsyncWebServerRequest::setHandler().
size()
size_t AsyncWebParameter::size () const inline
Definition at line 96 of file ESPAsyncWebServer.h.
References _size.
value()
const String& AsyncWebParameter::value () const inline
Definition at line 95 of file ESPAsyncWebServer.h.
References _value.
Referenced by AsyncWebServerRequest::arg(), and SPIFFSEditor::handleRequest().
Field Documentation
_isFile
bool AsyncWebParameter::_isFile private
Definition at line 89 of file ESPAsyncWebServer.h.
Referenced by isFile().
_isForm
bool AsyncWebParameter::_isForm private
Definition at line 88 of file ESPAsyncWebServer.h.
Referenced by isPost().
_name
String AsyncWebParameter::_name private
Definition at line 85 of file ESPAsyncWebServer.h.
Referenced by name(), and AsyncWebHeader::name().
_size
size_t AsyncWebParameter::_size private
Definition at line 87 of file ESPAsyncWebServer.h.
Referenced by size().
_value
String AsyncWebParameter::_value private
Definition at line 86 of file ESPAsyncWebServer.h.
Referenced by value(), and AsyncWebHeader::value().
The documentation for this class was generated from the following file:
src/ESPAsyncWebServer/ESPAsyncWebServer.h