RBE1001Lib: AsyncEventSourceClient Class Reference
AsyncEventSourceClient Class Reference
#include <AsyncEventSource.h>
Public Member Functions
AsyncEventSourceClient (AsyncWebServerRequest *request, AsyncEventSource *server)
~AsyncEventSourceClient ()
AsyncClient * client ()
void close ()
void write (const char *message, size_t len)
void send (const char *message, const char *event=NULL, uint32_t id=0, uint32_t reconnect=0)
bool connected () const
uint32_t lastId () const
size_t packetsWaiting () const
void _onAck (size_t len, uint32_t time)
void _onPoll ()
void _onTimeout (uint32_t time)
void _onDisconnect ()
Private Member Functions
void _queueMessage (AsyncEventSourceMessage *dataMessage)
void _runQueue ()
Private Attributes
AsyncClient * _client
AsyncEventSource * _server
uint32_t _lastId
LinkedList< AsyncEventSourceMessage * > _messageQueue
Detailed Description
Definition at line 69 of file AsyncEventSource.h.
Constructor & Destructor Documentation
AsyncEventSourceClient()
AsyncEventSourceClient::AsyncEventSourceClient (AsyncWebServerRequest * request, AsyncEventSource * server)
Definition at line 154 of file AsyncEventSource.cpp.
References AsyncEventSource::_addClient(), _client, _lastId, _onAck(), _onDisconnect(), _onPoll(), _onTimeout(), _server, AsyncClient::onAck(), AsyncClient::onData(), AsyncClient::onDisconnect(), AsyncClient::onError(), AsyncClient::onPoll(), AsyncClient::onTimeout(), server, and AsyncClient::setRxTimeout().
~AsyncEventSourceClient()
AsyncEventSourceClient::~AsyncEventSourceClient ()
Definition at line 175 of file AsyncEventSource.cpp.
References _messageQueue, close(), and LinkedList< T, Item >::free().
Member Function Documentation
_onAck()
void AsyncEventSourceClient::_onAck (size_t len, uint32_t time)
Definition at line 197 of file AsyncEventSource.cpp.
References _messageQueue, _runQueue(), AsyncEventSourceMessage::ack(), AsyncEventSourceMessage::finished(), LinkedList< T, Item >::front(), LinkedList< T, Item >::isEmpty(), and LinkedList< T, Item >::remove().
Referenced by AsyncEventSourceClient().
_onDisconnect()
void AsyncEventSourceClient::_onDisconnect ()
Definition at line 218 of file AsyncEventSource.cpp.
References _client, AsyncEventSource::_handleDisconnect(), and _server.
Referenced by AsyncEventSourceClient().
_onPoll()
void AsyncEventSourceClient::_onPoll ()
Definition at line 207 of file AsyncEventSource.cpp.
References _messageQueue, _runQueue(), and LinkedList< T, Item >::isEmpty().
Referenced by AsyncEventSourceClient().
_onTimeout()
void AsyncEventSourceClient::_onTimeout (uint32_t time)
Definition at line 214 of file AsyncEventSource.cpp.
References _client, and AsyncClient::close().
Referenced by AsyncEventSourceClient().
_queueMessage()
void AsyncEventSourceClient::_queueMessage (AsyncEventSourceMessage * dataMessage) private
Definition at line 180 of file AsyncEventSource.cpp.
References _client, _messageQueue, _runQueue(), LinkedList< T, Item >::add(), AsyncClient::canSend(), connected(), LinkedList< T, Item >::length(), and SSE_MAX_QUEUED_MESSAGES.
Referenced by send(), and write().
_runQueue()
void AsyncEventSourceClient::_runQueue () private
Definition at line 237 of file AsyncEventSource.cpp.
References _client, _messageQueue, LinkedList< T, Item >::begin(), LinkedList< T, Item >::end(), AsyncEventSourceMessage::finished(), LinkedList< T, Item >::front(), LinkedList< T, Item >::isEmpty(), and LinkedList< T, Item >::remove().
Referenced by _onAck(), _onPoll(), and _queueMessage().
client()
AsyncClient* AsyncEventSourceClient::client () inline
Definition at line 83 of file AsyncEventSource.h.
References reconnect, and AsyncEventSourceMessage::send().
close()
void AsyncEventSourceClient::close ()
Definition at line 223 of file AsyncEventSource.cpp.
References _client, and AsyncClient::close().
Referenced by ~AsyncEventSourceClient().
connected()
bool AsyncEventSourceClient::connected () const inline
Definition at line 87 of file AsyncEventSource.h.
References AsyncClient::connected().
Referenced by _queueMessage(), and AsyncEventSource::count().
lastId()
uint32_t AsyncEventSourceClient::lastId () const inline
Definition at line 88 of file AsyncEventSource.h.
packetsWaiting()
size_t AsyncEventSourceClient::packetsWaiting () const inline
Definition at line 89 of file AsyncEventSource.h.
References LinkedList< T, Item >::length().
send()
void AsyncEventSourceClient::send (const char * message, const char * event = NULL, uint32_t id = 0, uint32_t reconnect = 0)
Definition at line 232 of file AsyncEventSource.cpp.
References _queueMessage(), and generateEventMessage().
write()
void AsyncEventSourceClient::write (const char * message, size_t len)
Definition at line 228 of file AsyncEventSource.cpp.
References _queueMessage().
Field Documentation
_client
AsyncClient* AsyncEventSourceClient::_client private
Definition at line 71 of file AsyncEventSource.h.
Referenced by _onDisconnect(), _onTimeout(), _queueMessage(), _runQueue(), AsyncEventSourceClient(), and close().
_lastId
uint32_t AsyncEventSourceClient::_lastId private
Definition at line 73 of file AsyncEventSource.h.
Referenced by AsyncEventSourceClient().
_messageQueue
LinkedList<AsyncEventSourceMessage *> AsyncEventSourceClient::_messageQueue private
Definition at line 74 of file AsyncEventSource.h.
Referenced by _onAck(), _onPoll(), _queueMessage(), _runQueue(), and ~AsyncEventSourceClient().
_server
AsyncEventSource* AsyncEventSourceClient::_server private
Definition at line 72 of file AsyncEventSource.h.
Referenced by _onDisconnect(), and AsyncEventSourceClient().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/AsyncEventSource.h
src/ESPAsyncWebServer/AsyncEventSource.cpp