RBE1001Lib: DefaultHeaders Class Reference
DefaultHeaders Class Reference
#include <ESPAsyncWebServer.h>
Public Types
using ConstIterator = headers_t::ConstIterator
Public Member Functions
void addHeader (const String &name, const String &value)
ConstIterator begin () const
ConstIterator end () const
DefaultHeaders (DefaultHeaders const &)=delete
DefaultHeaders & operator= (DefaultHeaders const &)=delete
Static Public Member Functions
static DefaultHeaders & Instance ()
Private Types
using headers_t = LinkedList< AsyncWebHeader * >
Private Member Functions
DefaultHeaders ()
Private Attributes
headers_t _headers
Detailed Description
Definition at line 441 of file ESPAsyncWebServer.h.
Member Typedef Documentation
ConstIterator
using DefaultHeaders::ConstIterator = headers_t::ConstIterator
Definition at line 449 of file ESPAsyncWebServer.h.
headers_t
using DefaultHeaders::headers_t = LinkedList<AsyncWebHeader *> private
Definition at line 442 of file ESPAsyncWebServer.h.
Constructor & Destructor Documentation
DefaultHeaders() [1/2]
DefaultHeaders::DefaultHeaders () inline private
Definition at line 445 of file ESPAsyncWebServer.h.
DefaultHeaders() [2/2]
DefaultHeaders::DefaultHeaders (DefaultHeaders const &) delete
Member Function Documentation
addHeader()
void DefaultHeaders::addHeader (const String & name, const String & value) inline
Definition at line 451 of file ESPAsyncWebServer.h.
References LinkedList< T, Item >::add().
begin()
ConstIterator DefaultHeaders::begin () const inline
Definition at line 455 of file ESPAsyncWebServer.h.
References LinkedList< T, Item >::begin().
end()
ConstIterator DefaultHeaders::end () const inline
Definition at line 456 of file ESPAsyncWebServer.h.
References LinkedList< T, Item >::end().
Instance()
static DefaultHeaders& DefaultHeaders::Instance () inline static
Definition at line 460 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServerResponse::AsyncWebServerResponse().
operator=()
DefaultHeaders& DefaultHeaders::operator= (DefaultHeaders const &) delete
Field Documentation
_headers
headers_t DefaultHeaders::_headers private
Definition at line 443 of file ESPAsyncWebServer.h.
The documentation for this class was generated from the following file:
src/ESPAsyncWebServer/ESPAsyncWebServer.h