RBE1001Lib: LineTrackSensor Class Reference
LineTrackSensor Class Reference
#include <LineTrackSensor.h>
Public Member Functions
LineTrackSensor (int left, int right)
float getLeft ()
float getRight ()
Private Attributes
ESP32AnalogRead lineLeft
ESP32AnalogRead lineRight
Detailed Description
Definition at line 4 of file LineTrackSensor.h.
Constructor & Destructor Documentation
LineTrackSensor()
LineTrackSensor::LineTrackSensor (int left, int right)
Definition at line 3 of file LineTrackSensor.cpp.
References ESP32AnalogRead::attach(), lineLeft, and lineRight.
Member Function Documentation
getLeft()
float LineTrackSensor::getLeft ()
Definition at line 8 of file LineTrackSensor.cpp.
References lineLeft, and ESP32AnalogRead::readVoltage().
Referenced by updateDashboard().
getRight()
float LineTrackSensor::getRight ()
Definition at line 12 of file LineTrackSensor.cpp.
References lineRight, and ESP32AnalogRead::readVoltage().
Referenced by updateDashboard().
Field Documentation
lineLeft
ESP32AnalogRead LineTrackSensor::lineLeft private
Definition at line 11 of file LineTrackSensor.h.
Referenced by getLeft(), and LineTrackSensor().
lineRight
ESP32AnalogRead LineTrackSensor::lineRight private
Definition at line 12 of file LineTrackSensor.h.
Referenced by getRight(), and LineTrackSensor().
The documentation for this class was generated from the following files:
src/LineTrackSensor.h
src/LineTrackSensor.cpp