RBE1001Lib: AsyncStaticWebHandler Class Reference
AsyncStaticWebHandler Class Reference
#include <WebHandlerImpl.h>
Public Member Functions
AsyncStaticWebHandler (const char *uri, FS &fs, const char *path, const char *cache_control)
virtual bool canHandle (AsyncWebServerRequest *request) override final
virtual void handleRequest (AsyncWebServerRequest *request) override final
AsyncStaticWebHandler & setIsDir (bool isDir)
AsyncStaticWebHandler & setDefaultFile (const char *filename)
AsyncStaticWebHandler & setCacheControl (const char *cache_control)
AsyncStaticWebHandler & setLastModified (const char *last_modified)
AsyncStaticWebHandler & setLastModified (struct tm *last_modified)
AsyncStaticWebHandler & setTemplateProcessor (AwsTemplateProcessor newCallback)
Public Member Functions inherited from AsyncWebHandler
AsyncWebHandler ()
AsyncWebHandler & setFilter (ArRequestFilterFunction fn)
AsyncWebHandler & setAuthentication (const char *username, const char *password)
bool filter (AsyncWebServerRequest *request)
virtual ~AsyncWebHandler ()
virtual bool canHandle (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleRequest (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleUpload (AsyncWebServerRequest *request __attribute__((unused)), const String &filename __attribute__((unused)), size_t index __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), bool final __attribute__((unused)))
virtual void handleBody (AsyncWebServerRequest *request __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), size_t index __attribute__((unused)), size_t total __attribute__((unused)))
virtual bool isRequestHandlerTrivial ()
Protected Attributes
FS _fs
String _uri
String _path
String _default_file
String _cache_control
String _last_modified
AwsTemplateProcessor _callback
bool _isDir
bool _gzipFirst
uint8_t _gzipStats
Protected Attributes inherited from AsyncWebHandler
ArRequestFilterFunction _filter
String _username
String _password
Private Types
using File = fs::File
using FS = fs::FS
Private Member Functions
bool _getFile (AsyncWebServerRequest *request)
bool _fileExists (AsyncWebServerRequest *request, const String &path)
uint8_t _countBits (const uint8_t value) const
Detailed Description
Definition at line 32 of file WebHandlerImpl.h.
Member Typedef Documentation
File
using AsyncStaticWebHandler::File = fs::File private
Definition at line 33 of file WebHandlerImpl.h.
FS
using AsyncStaticWebHandler::FS = fs::FS private
Definition at line 34 of file WebHandlerImpl.h.
Constructor & Destructor Documentation
AsyncStaticWebHandler()
AsyncStaticWebHandler::AsyncStaticWebHandler (const char * uri, FS & fs, const char * path, const char * cache_control)
Definition at line 24 of file WebHandlers.cpp.
References _gzipFirst, _gzipStats, _isDir, _path, and _uri.
Member Function Documentation
_countBits()
uint8_t AsyncStaticWebHandler::_countBits (const uint8_t value) const private
Definition at line 179 of file WebHandlers.cpp.
Referenced by _fileExists().
_fileExists()
bool AsyncStaticWebHandler::_fileExists (AsyncWebServerRequest * request, const String & path) private
Definition at line 137 of file WebHandlers.cpp.
References _countBits(), _fs, _gzipFirst, _gzipStats, AsyncWebServerRequest::_tempFile, AsyncWebServerRequest::_tempObject, and FILE_IS_REAL.
Referenced by _getFile().
_getFile()
bool AsyncStaticWebHandler::_getFile (AsyncWebServerRequest * request) private
Definition at line 105 of file WebHandlers.cpp.
References _default_file, _fileExists(), _isDir, _path, _uri, and AsyncWebServerRequest::url().
Referenced by canHandle().
canHandle()
bool AsyncStaticWebHandler::canHandle (AsyncWebServerRequest * request) final override virtual
Definition at line 83 of file WebHandlers.cpp.
References _cache_control, _getFile(), _last_modified, _uri, AsyncWebServerRequest::addInterestingHeader(), DEBUGF, HTTP_GET, AsyncWebServerRequest::isExpectedRequestedConnType(), AsyncWebServerRequest::method(), RCT_DEFAULT, RCT_HTTP, and AsyncWebServerRequest::url().
handleRequest()
void AsyncStaticWebHandler::handleRequest (AsyncWebServerRequest * request) final override virtual
Definition at line 187 of file WebHandlers.cpp.
References _cache_control, _callback, _last_modified, AsyncWebHandler::_password, AsyncWebServerRequest::_tempFile, AsyncWebServerRequest::_tempObject, AsyncWebHandler::_username, AsyncWebServerResponse::addHeader(), AsyncWebServerRequest::authenticate(), AsyncWebServerRequest::hasHeader(), AsyncWebServerRequest::header(), AsyncWebServerRequest::requestAuthentication(), and AsyncWebServerRequest::send().
setCacheControl()
AsyncStaticWebHandler & AsyncStaticWebHandler::setCacheControl (const char * cache_control)
Definition at line 55 of file WebHandlers.cpp.
References _cache_control.
setDefaultFile()
AsyncStaticWebHandler & AsyncStaticWebHandler::setDefaultFile (const char * filename)
Definition at line 50 of file WebHandlers.cpp.
References _default_file.
setIsDir()
AsyncStaticWebHandler & AsyncStaticWebHandler::setIsDir (bool isDir)
Definition at line 45 of file WebHandlers.cpp.
References _isDir.
setLastModified() [1/2]
AsyncStaticWebHandler & AsyncStaticWebHandler::setLastModified (const char * last_modified)
Definition at line 60 of file WebHandlers.cpp.
References _last_modified.
Referenced by setLastModified().
setLastModified() [2/2]
AsyncStaticWebHandler & AsyncStaticWebHandler::setLastModified (struct tm * last_modified)
Definition at line 65 of file WebHandlers.cpp.
References setLastModified().
setTemplateProcessor()
AsyncStaticWebHandler& AsyncStaticWebHandler::setTemplateProcessor (AwsTemplateProcessor newCallback) inline
Definition at line 63 of file WebHandlerImpl.h.
Field Documentation
_cache_control
String AsyncStaticWebHandler::_cache_control protected
Definition at line 44 of file WebHandlerImpl.h.
Referenced by canHandle(), handleRequest(), and setCacheControl().
_callback
AwsTemplateProcessor AsyncStaticWebHandler::_callback protected
Definition at line 46 of file WebHandlerImpl.h.
Referenced by handleRequest().
_default_file
String AsyncStaticWebHandler::_default_file protected
Definition at line 43 of file WebHandlerImpl.h.
Referenced by _getFile(), and setDefaultFile().
_fs
FS AsyncStaticWebHandler::_fs protected
Definition at line 40 of file WebHandlerImpl.h.
Referenced by _fileExists().
_gzipFirst
bool AsyncStaticWebHandler::_gzipFirst protected
Definition at line 48 of file WebHandlerImpl.h.
Referenced by _fileExists(), and AsyncStaticWebHandler().
_gzipStats
uint8_t AsyncStaticWebHandler::_gzipStats protected
Definition at line 49 of file WebHandlerImpl.h.
Referenced by _fileExists(), and AsyncStaticWebHandler().
_isDir
bool AsyncStaticWebHandler::_isDir protected
Definition at line 47 of file WebHandlerImpl.h.
Referenced by _getFile(), AsyncStaticWebHandler(), and setIsDir().
_last_modified
String AsyncStaticWebHandler::_last_modified protected
Definition at line 45 of file WebHandlerImpl.h.
Referenced by canHandle(), handleRequest(), and setLastModified().
_path
String AsyncStaticWebHandler::_path protected
Definition at line 42 of file WebHandlerImpl.h.
Referenced by _getFile(), and AsyncStaticWebHandler().
_uri
String AsyncStaticWebHandler::_uri protected
Definition at line 41 of file WebHandlerImpl.h.
Referenced by _getFile(), AsyncStaticWebHandler(), and canHandle().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/WebHandlerImpl.h
src/ESPAsyncWebServer/WebHandlers.cpp