RBE1001Lib: AsyncServer Class Reference
AsyncServer Class Reference
#include <AsyncTCP.h>
Public Member Functions
AsyncServer (IPAddress addr, uint16_t port)
AsyncServer (uint16_t port)
~AsyncServer ()
void onClient (AcConnectHandler cb, void *arg)
void begin ()
void end ()
void setNoDelay (bool nodelay)
bool getNoDelay ()
uint8_t status ()
Static Public Member Functions
static int8_t _s_accept (void *arg, tcp_pcb *newpcb, int8_t err)
static int8_t _s_accepted (void *arg, AsyncClient *client)
Protected Member Functions
int8_t _accept (tcp_pcb *newpcb, int8_t err)
int8_t _accepted (AsyncClient *client)
Protected Attributes
uint16_t _port
IPAddress _addr
bool _noDelay
tcp_pcb * _pcb
AcConnectHandler _connect_cb
void * _connect_cb_arg
Detailed Description
Definition at line 188 of file AsyncTCP.h.
Constructor & Destructor Documentation
AsyncServer() [1/2]
AsyncServer::AsyncServer (IPAddress addr, uint16_t port)
Definition at line 1243 of file AsyncTCP.cpp.
AsyncServer() [2/2]
AsyncServer::AsyncServer (uint16_t port)
Definition at line 1252 of file AsyncTCP.cpp.
~AsyncServer()
AsyncServer::~AsyncServer ()
Definition at line 1261 of file AsyncTCP.cpp.
References end().
Member Function Documentation
_accept()
int8_t AsyncServer::_accept (tcp_pcb * newpcb, int8_t err) protected
Definition at line 1319 of file AsyncTCP.cpp.
References _connect_cb, _noDelay, _tcp_accept(), and AsyncClient::setNoDelay().
Referenced by _s_accept().
_accepted()
int8_t AsyncServer::_accepted (AsyncClient * client) protected
Definition at line 1335 of file AsyncTCP.cpp.
References _connect_cb, and _connect_cb_arg.
Referenced by _s_accepted().
_s_accept()
int8_t AsyncServer::_s_accept (void * arg, tcp_pcb * newpcb, int8_t err) static
Definition at line 1357 of file AsyncTCP.cpp.
References _accept().
Referenced by begin().
_s_accepted()
int8_t AsyncServer::_s_accepted (void * arg, AsyncClient * client) static
Definition at line 1361 of file AsyncTCP.cpp.
References _accepted().
Referenced by _handle_async_event().
begin()
void AsyncServer::begin ()
Definition at line 1270 of file AsyncTCP.cpp.
References _addr, _pcb, _port, _s_accept(), _start_async_task(), _tcp_bind(), _tcp_close(), and _tcp_listen_with_backlog().
Referenced by AsyncWebServer::begin().
end()
void AsyncServer::end ()
Definition at line 1307 of file AsyncTCP.cpp.
References _pcb, and _tcp_abort().
Referenced by AsyncWebServer::end(), and ~AsyncServer().
getNoDelay()
bool AsyncServer::getNoDelay ()
Definition at line 1346 of file AsyncTCP.cpp.
References _noDelay.
onClient()
void AsyncServer::onClient (AcConnectHandler cb, void * arg)
Definition at line 1265 of file AsyncTCP.cpp.
References _connect_cb, and _connect_cb_arg.
Referenced by AsyncWebServer::AsyncWebServer().
setNoDelay()
void AsyncServer::setNoDelay (bool nodelay)
Definition at line 1342 of file AsyncTCP.cpp.
References _noDelay.
Referenced by AsyncWebServer::begin().
status()
uint8_t AsyncServer::status ()
Definition at line 1350 of file AsyncTCP.cpp.
References _pcb.
Field Documentation
_addr
IPAddress AsyncServer::_addr protected
Definition at line 206 of file AsyncTCP.h.
Referenced by begin().
_connect_cb
AcConnectHandler AsyncServer::_connect_cb protected
Definition at line 209 of file AsyncTCP.h.
Referenced by _accept(), _accepted(), and onClient().
_connect_cb_arg
void* AsyncServer::_connect_cb_arg protected
Definition at line 210 of file AsyncTCP.h.
Referenced by _accepted(), and onClient().
_noDelay
bool AsyncServer::_noDelay protected
Definition at line 207 of file AsyncTCP.h.
Referenced by _accept(), getNoDelay(), and setNoDelay().
_pcb
tcp_pcb* AsyncServer::_pcb protected
Definition at line 208 of file AsyncTCP.h.
Referenced by begin(), end(), and status().
_port
uint16_t AsyncServer::_port protected
Definition at line 205 of file AsyncTCP.h.
Referenced by begin().
The documentation for this class was generated from the following files:
src/AsyncTCP/AsyncTCP.h
src/AsyncTCP/AsyncTCP.cpp