RBE1001Lib: AsyncWebSocket Class Reference
AsyncWebSocket Class Reference
#include <AsyncWebSocket.h>
Public Types
typedef LinkedList< AsyncWebSocketClient * > AsyncWebSocketClientLinkedList
Public Member Functions
AsyncWebSocket (const String &url)
~AsyncWebSocket ()
const char * url () const
void enable (bool e)
bool enabled () const
bool availableForWriteAll ()
bool availableForWrite (uint32_t id)
size_t count () const
AsyncWebSocketClient * client (uint32_t id)
bool hasClient (uint32_t id)
void close (uint32_t id, uint16_t code=0, const char *message=NULL)
void closeAll (uint16_t code=0, const char *message=NULL)
void cleanupClients (uint16_t maxClients=DEFAULT_MAX_WS_CLIENTS)
void ping (uint32_t id, uint8_t *data=NULL, size_t len=0)
void pingAll (uint8_t *data=NULL, size_t len=0)
void text (uint32_t id, const char *message, size_t len)
void text (uint32_t id, const char *message)
void text (uint32_t id, uint8_t *message, size_t len)
void text (uint32_t id, char *message)
void text (uint32_t id, const String &message)
void text (uint32_t id, const __FlashStringHelper *message)
void textAll (const char *message, size_t len)
void textAll (const char *message)
void textAll (uint8_t *message, size_t len)
void textAll (char *message)
void textAll (const String &message)
void textAll (const __FlashStringHelper *message)
void textAll (AsyncWebSocketMessageBuffer *buffer)
void binary (uint32_t id, const char *message, size_t len)
void binary (uint32_t id, const char *message)
void binary (uint32_t id, uint8_t *message, size_t len)
void binary (uint32_t id, char *message)
void binary (uint32_t id, const String &message)
void binary (uint32_t id, const __FlashStringHelper *message, size_t len)
void binaryAll (const char *message, size_t len)
void binaryAll (const char *message)
void binaryAll (uint8_t *message, size_t len)
void binaryAll (char *message)
void binaryAll (const String &message)
void binaryAll (const __FlashStringHelper *message, size_t len)
void binaryAll (AsyncWebSocketMessageBuffer *buffer)
void message (uint32_t id, AsyncWebSocketMessage *message)
void messageAll (AsyncWebSocketMultiMessage *message)
size_t printf (uint32_t id, const char *format,...) __attribute__((format(printf
size_t size_t printfAll (const char *format,...) __attribute__((format(printf
size_t size_t size_t printf_P (uint32_t id, PGM_P formatP,...) __attribute__((format(printf
size_t size_t size_t size_t printfAll_P (PGM_P formatP,...) __attribute__((format(printf
size_t size_t size_t size_t void onEvent (AwsEventHandler handler)
uint32_t _getNextId ()
void _addClient (AsyncWebSocketClient *client)
void _handleDisconnect (AsyncWebSocketClient *client)
void _handleEvent (AsyncWebSocketClient *client, AwsEventType type, void *arg, uint8_t *data, size_t len)
virtual bool canHandle (AsyncWebServerRequest *request) override final
virtual void handleRequest (AsyncWebServerRequest *request) override final
AsyncWebSocketMessageBuffer * makeBuffer (size_t size=0)
AsyncWebSocketMessageBuffer * makeBuffer (uint8_t *data, size_t size)
void _cleanBuffers ()
AsyncWebSocketClientLinkedList getClients () const
Public Member Functions inherited from AsyncWebHandler
AsyncWebHandler ()
AsyncWebHandler & setFilter (ArRequestFilterFunction fn)
AsyncWebHandler & setAuthentication (const char *username, const char *password)
bool filter (AsyncWebServerRequest *request)
virtual ~AsyncWebHandler ()
virtual bool canHandle (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleRequest (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleUpload (AsyncWebServerRequest *request __attribute__((unused)), const String &filename __attribute__((unused)), size_t index __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), bool final __attribute__((unused)))
virtual void handleBody (AsyncWebServerRequest *request __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), size_t index __attribute__((unused)), size_t total __attribute__((unused)))
virtual bool isRequestHandlerTrivial ()
Data Fields
LinkedList< AsyncWebSocketMessageBuffer * > _buffers
Private Attributes
String _url
AsyncWebSocketClientLinkedList _clients
uint32_t _cNextId
AwsEventHandler _eventHandler
bool _enabled
AsyncWebLock _lock
Additional Inherited Members
Protected Attributes inherited from AsyncWebHandler
ArRequestFilterFunction _filter
String _username
String _password
Detailed Description
Definition at line 243 of file AsyncWebSocket.h.
Member Typedef Documentation
AsyncWebSocketClientLinkedList
typedef LinkedList<AsyncWebSocketClient *> AsyncWebSocket::AsyncWebSocketClientLinkedList
Definition at line 245 of file AsyncWebSocket.h.
Constructor & Destructor Documentation
AsyncWebSocket()
AsyncWebSocket::AsyncWebSocket (const String & url)
Definition at line 861 of file AsyncWebSocket.cpp.
References _buffers, _cNextId, _enabled, and _eventHandler.
~AsyncWebSocket()
AsyncWebSocket::~AsyncWebSocket ()
Definition at line 871 of file AsyncWebSocket.cpp.
Member Function Documentation
_addClient()
void AsyncWebSocket::_addClient (AsyncWebSocketClient * client)
Definition at line 879 of file AsyncWebSocket.cpp.
References _clients, and LinkedList< T, Item >::add().
Referenced by AsyncWebSocketClient::AsyncWebSocketClient().
_cleanBuffers()
void AsyncWebSocket::_cleanBuffers ()
Definition at line 1231 of file AsyncWebSocket.cpp.
References _buffers, and _lock.
Referenced by AsyncWebSocketClient::_onAck(), binaryAll(), messageAll(), and textAll().
_getNextId()
uint32_t AsyncWebSocket::_getNextId () inline
Definition at line 320 of file AsyncWebSocket.h.
Referenced by AsyncWebSocketClient::AsyncWebSocketClient().
_handleDisconnect()
void AsyncWebSocket::_handleDisconnect (AsyncWebSocketClient * client)
Definition at line 883 of file AsyncWebSocket.cpp.
References _clients, AsyncWebSocketClient::id(), and LinkedList< T, Item >::remove_first().
Referenced by AsyncWebSocketClient::_onDisconnect().
_handleEvent()
void AsyncWebSocket::_handleEvent (AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t * data, size_t len)
Definition at line 873 of file AsyncWebSocket.cpp.
References _eventHandler.
Referenced by AsyncWebSocketClient::_onData(), AsyncWebSocketClient::AsyncWebSocketClient(), and AsyncWebSocketClient::~AsyncWebSocketClient().
availableForWrite()
bool AsyncWebSocket::availableForWrite (uint32_t id)
Definition at line 897 of file AsyncWebSocket.cpp.
References _clients.
availableForWriteAll()
bool AsyncWebSocket::availableForWriteAll ()
Definition at line 890 of file AsyncWebSocket.cpp.
References _clients.
Referenced by WebPage::SendAllLabels(), WebPage::SendAllValues(), and WebPage::sendHeartbeat().
binary() [1/6]
void AsyncWebSocket::binary (uint32_t id, const char * message, size_t len)
Definition at line 977 of file AsyncWebSocket.cpp.
References AsyncWebSocketClient::binary(), and client().
Referenced by binary(), and binaryAll().
binary() [2/6]
void AsyncWebSocket::binary (uint32_t id, const char * message)
Definition at line 1123 of file AsyncWebSocket.cpp.
References binary().
binary() [3/6]
void AsyncWebSocket::binary (uint32_t id, uint8_t * message, size_t len)
Definition at line 1126 of file AsyncWebSocket.cpp.
References binary().
binary() [4/6]
void AsyncWebSocket::binary (uint32_t id, char * message)
Definition at line 1129 of file AsyncWebSocket.cpp.
References binary().
binary() [5/6]
void AsyncWebSocket::binary (uint32_t id, const String & message)
Definition at line 1132 of file AsyncWebSocket.cpp.
References binary().
binary() [6/6]
void AsyncWebSocket::binary (uint32_t id, const __FlashStringHelper * message, size_t len)
Definition at line 1135 of file AsyncWebSocket.cpp.
References binary(), and client().
binaryAll() [1/7]
void AsyncWebSocket::binaryAll (const char * message, size_t len)
Definition at line 983 of file AsyncWebSocket.cpp.
References makeBuffer().
Referenced by binaryAll(), WebPage::SendAllLabels(), WebPage::SendAllValues(), and WebPage::sendHeartbeat().
binaryAll() [2/7]
void AsyncWebSocket::binaryAll (const char * message)
Definition at line 1140 of file AsyncWebSocket.cpp.
References binaryAll().
binaryAll() [3/7]
void AsyncWebSocket::binaryAll (uint8_t * message, size_t len)
Definition at line 1143 of file AsyncWebSocket.cpp.
References binaryAll().
binaryAll() [4/7]
void AsyncWebSocket::binaryAll (char * message)
Definition at line 1146 of file AsyncWebSocket.cpp.
References binaryAll().
binaryAll() [5/7]
void AsyncWebSocket::binaryAll (const String & message)
Definition at line 1149 of file AsyncWebSocket.cpp.
References binaryAll().
binaryAll() [6/7]
void AsyncWebSocket::binaryAll (const __FlashStringHelper * message, size_t len)
Definition at line 1152 of file AsyncWebSocket.cpp.
References _clients, binary(), and WS_CONNECTED.
binaryAll() [7/7]
void AsyncWebSocket::binaryAll (AsyncWebSocketMessageBuffer * buffer)
Definition at line 988 of file AsyncWebSocket.cpp.
References _cleanBuffers(), _clients, AsyncWebSocketMessageBuffer::lock(), AsyncWebSocketMessageBuffer::unlock(), and WS_CONNECTED.
canHandle()
bool AsyncWebSocket::canHandle (AsyncWebServerRequest * request) final override virtual
Definition at line 1168 of file AsyncWebSocket.cpp.
References _enabled, _url, AsyncWebServerRequest::addInterestingHeader(), HTTP_GET, AsyncWebServerRequest::isExpectedRequestedConnType(), AsyncWebServerRequest::method(), RCT_WS, AsyncWebServerRequest::url(), WS_STR_CONNECTION, WS_STR_KEY, WS_STR_ORIGIN, WS_STR_PROTOCOL, WS_STR_UPGRADE, and WS_STR_VERSION.
cleanupClients()
void AsyncWebSocket::cleanupClients (uint16_t maxClients = DEFAULT_MAX_WS_CLIENTS)
Definition at line 933 of file AsyncWebSocket.cpp.
References _clients, count(), and LinkedList< T, Item >::front().
client()
AsyncWebSocketClient * AsyncWebSocket::client (uint32_t id)
Definition at line 910 of file AsyncWebSocket.cpp.
References _clients, and WS_CONNECTED.
Referenced by binary(), close(), message(), ping(), printf(), printf_P(), and text().
close()
void AsyncWebSocket::close (uint32_t id, uint16_t code = 0, const char * message = NULL)
Definition at line 920 of file AsyncWebSocket.cpp.
References client(), and AsyncWebSocketClient::close().
closeAll()
void AsyncWebSocket::closeAll (uint16_t code = 0, const char * message = NULL)
Definition at line 926 of file AsyncWebSocket.cpp.
References _clients, and WS_CONNECTED.
count()
size_t AsyncWebSocket::count () const
Definition at line 904 of file AsyncWebSocket.cpp.
References _clients, LinkedList< T, Item >::count_if(), AsyncWebSocketClient::status(), and WS_CONNECTED.
Referenced by cleanupClients(), WebPage::SendAllLabels(), WebPage::SendAllValues(), and WebPage::sendHeartbeat().
enable()
void AsyncWebSocket::enable (bool e) inline
Definition at line 258 of file AsyncWebSocket.h.
enabled()
bool AsyncWebSocket::enabled () const inline
Definition at line 259 of file AsyncWebSocket.h.
getClients()
AsyncWebSocket::AsyncWebSocketClientLinkedList AsyncWebSocket::getClients () const
Definition at line 1242 of file AsyncWebSocket.cpp.
References _clients.
handleRequest()
void AsyncWebSocket::handleRequest (AsyncWebServerRequest * request) final override virtual
Definition at line 1184 of file AsyncWebSocket.cpp.
References AsyncWebHandler::_password, AsyncWebHandler::_username, AsyncWebServerResponse::addHeader(), AsyncWebServerRequest::authenticate(), AsyncWebServerRequest::beginResponse(), AsyncWebServerRequest::getHeader(), AsyncWebServerRequest::hasHeader(), AsyncWebServerRequest::requestAuthentication(), AsyncWebServerRequest::send(), AsyncWebHeader::value(), WS_STR_KEY, WS_STR_PROTOCOL, and WS_STR_VERSION.
hasClient()
bool AsyncWebSocket::hasClient (uint32_t id) inline
Definition at line 265 of file AsyncWebSocket.h.
References DEFAULT_MAX_WS_CLIENTS, and AsyncWebSocketControl::len().
makeBuffer() [1/2]
AsyncWebSocketMessageBuffer * AsyncWebSocket::makeBuffer (size_t size = 0)
Definition at line 1209 of file AsyncWebSocket.cpp.
References _buffers, _lock, and LinkedList< T, Item >::add().
Referenced by binaryAll(), printfAll(), printfAll_P(), and textAll().
makeBuffer() [2/2]
AsyncWebSocketMessageBuffer * AsyncWebSocket::makeBuffer (uint8_t * data, size_t size)
Definition at line 1219 of file AsyncWebSocket.cpp.
References _buffers, _lock, and LinkedList< T, Item >::add().
message()
void AsyncWebSocket::message (uint32_t id, AsyncWebSocketMessage * message)
Definition at line 1000 of file AsyncWebSocket.cpp.
References client(), and AsyncWebSocketClient::message().
messageAll()
void AsyncWebSocket::messageAll (AsyncWebSocketMultiMessage * message)
Definition at line 1006 of file AsyncWebSocket.cpp.
References _cleanBuffers(), _clients, and WS_CONNECTED.
onEvent()
size_t size_t size_t size_t void AsyncWebSocket::onEvent (AwsEventHandler handler) inline
Definition at line 315 of file AsyncWebSocket.h.
Referenced by WebPage::initalize().
ping()
void AsyncWebSocket::ping (uint32_t id, uint8_t * data = NULL, size_t len = 0)
Definition at line 940 of file AsyncWebSocket.cpp.
References client(), and AsyncWebSocketClient::ping().
pingAll()
void AsyncWebSocket::pingAll (uint8_t * data = NULL, size_t len = 0)
Definition at line 946 of file AsyncWebSocket.cpp.
References _clients, and WS_CONNECTED.
printf()
size_t AsyncWebSocket::printf (uint32_t id, const char * format, ...)
Definition at line 1014 of file AsyncWebSocket.cpp.
References client(), and AsyncWebSocketClient::printf().
printf_P()
size_t AsyncWebSocket::printf_P (uint32_t id, PGM_P formatP, ...)
Definition at line 1051 of file AsyncWebSocket.cpp.
References client(), and AsyncWebSocketClient::printf_P().
printfAll()
size_t AsyncWebSocket::printfAll (const char * format, ...)
Definition at line 1026 of file AsyncWebSocket.cpp.
References AsyncWebSocketMessageBuffer::get(), makeBuffer(), MAX_PRINTF_LEN, and textAll().
printfAll_P()
size_t AsyncWebSocket::printfAll_P (PGM_P formatP, ...)
Definition at line 1064 of file AsyncWebSocket.cpp.
References AsyncWebSocketMessageBuffer::get(), makeBuffer(), MAX_PRINTF_LEN, and textAll().
text() [1/6]
void AsyncWebSocket::text (uint32_t id, const char * message, size_t len)
Definition at line 953 of file AsyncWebSocket.cpp.
References client(), and AsyncWebSocketClient::text().
Referenced by text().
text() [2/6]
void AsyncWebSocket::text (uint32_t id, const char * message)
Definition at line 1088 of file AsyncWebSocket.cpp.
References text().
text() [3/6]
void AsyncWebSocket::text (uint32_t id, uint8_t * message, size_t len)
Definition at line 1091 of file AsyncWebSocket.cpp.
References text().
text() [4/6]
void AsyncWebSocket::text (uint32_t id, char * message)
Definition at line 1094 of file AsyncWebSocket.cpp.
References text().
text() [5/6]
void AsyncWebSocket::text (uint32_t id, const String & message)
Definition at line 1097 of file AsyncWebSocket.cpp.
References text().
text() [6/6]
void AsyncWebSocket::text (uint32_t id, const __FlashStringHelper * message)
Definition at line 1100 of file AsyncWebSocket.cpp.
References client(), and AsyncWebSocketClient::text().
textAll() [1/7]
void AsyncWebSocket::textAll (const char * message, size_t len)
Definition at line 972 of file AsyncWebSocket.cpp.
References makeBuffer().
Referenced by printfAll(), printfAll_P(), and textAll().
textAll() [2/7]
void AsyncWebSocket::textAll (const char * message)
Definition at line 1105 of file AsyncWebSocket.cpp.
References textAll().
textAll() [3/7]
void AsyncWebSocket::textAll (uint8_t * message, size_t len)
Definition at line 1108 of file AsyncWebSocket.cpp.
References textAll().
textAll() [4/7]
void AsyncWebSocket::textAll (char * message)
Definition at line 1111 of file AsyncWebSocket.cpp.
References textAll().
textAll() [5/7]
void AsyncWebSocket::textAll (const String & message)
Definition at line 1114 of file AsyncWebSocket.cpp.
References textAll().
textAll() [6/7]
void AsyncWebSocket::textAll (const __FlashStringHelper * message)
Definition at line 1117 of file AsyncWebSocket.cpp.
References _clients, and WS_CONNECTED.
textAll() [7/7]
void AsyncWebSocket::textAll (AsyncWebSocketMessageBuffer * buffer)
Definition at line 959 of file AsyncWebSocket.cpp.
References _cleanBuffers(), _clients, AsyncWebSocketMessageBuffer::lock(), AsyncWebSocketMessageBuffer::unlock(), and WS_CONNECTED.
url()
const char* AsyncWebSocket::url () const inline
Definition at line 257 of file AsyncWebSocket.h.
Field Documentation
_buffers
LinkedList<AsyncWebSocketMessageBuffer *> AsyncWebSocket::_buffers
Definition at line 331 of file AsyncWebSocket.h.
Referenced by _cleanBuffers(), AsyncWebSocket(), and makeBuffer().
_clients
AsyncWebSocketClientLinkedList AsyncWebSocket::_clients private
Definition at line 248 of file AsyncWebSocket.h.
Referenced by _addClient(), _handleDisconnect(), availableForWrite(), availableForWriteAll(), binaryAll(), cleanupClients(), client(), closeAll(), count(), getClients(), messageAll(), pingAll(), and textAll().
_cNextId
uint32_t AsyncWebSocket::_cNextId private
Definition at line 249 of file AsyncWebSocket.h.
Referenced by AsyncWebSocket().
_enabled
bool AsyncWebSocket::_enabled private
Definition at line 251 of file AsyncWebSocket.h.
Referenced by AsyncWebSocket(), and canHandle().
_eventHandler
AwsEventHandler AsyncWebSocket::_eventHandler private
Definition at line 250 of file AsyncWebSocket.h.
Referenced by _handleEvent(), and AsyncWebSocket().
_lock
AsyncWebLock AsyncWebSocket::_lock private
Definition at line 252 of file AsyncWebSocket.h.
Referenced by _cleanBuffers(), and makeBuffer().
_url
String AsyncWebSocket::_url private
Definition at line 247 of file AsyncWebSocket.h.
Referenced by canHandle().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/AsyncWebSocket.h
src/ESPAsyncWebServer/AsyncWebSocket.cpp