RBE1001Lib: AsyncWebSocketControl Class Reference
AsyncWebSocketControl Class Reference
Public Member Functions
AsyncWebSocketControl (uint8_t opcode, uint8_t *data=NULL, size_t len=0, bool mask=false)
virtual ~AsyncWebSocketControl ()
virtual bool finished () const
uint8_t opcode ()
uint8_t len ()
size_t send (AsyncClient *client)
Private Attributes
uint8_t _opcode
uint8_t * _data
size_t _len
bool _mask
bool _finished
Detailed Description
Definition at line 244 of file AsyncWebSocket.cpp.
Constructor & Destructor Documentation
AsyncWebSocketControl()
AsyncWebSocketControl::AsyncWebSocketControl (uint8_t opcode, uint8_t * data = NULL, size_t len = 0, bool mask = false) inline
Definition at line 252 of file AsyncWebSocket.cpp.
~AsyncWebSocketControl()
virtual AsyncWebSocketControl::~AsyncWebSocketControl () inline virtual
Definition at line 269 of file AsyncWebSocket.cpp.
Member Function Documentation
finished()
virtual bool AsyncWebSocketControl::finished () const inline virtual
Definition at line 273 of file AsyncWebSocket.cpp.
len()
uint8_t AsyncWebSocketControl::len () inline
Definition at line 275 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketClient::_onAck(), AsyncWebSocketClient::_runQueue(), AsyncWebSocketBasicMessage::betweenFrames(), AsyncWebSocketMultiMessage::betweenFrames(), AsyncWebSocket::hasClient(), AsyncWebSocketClient::message(), and AsyncWebSocketClient::pinfo().
opcode()
uint8_t AsyncWebSocketControl::opcode () inline
Definition at line 274 of file AsyncWebSocket.cpp.
send()
size_t AsyncWebSocketControl::send (AsyncClient * client) inline
Definition at line 276 of file AsyncWebSocket.cpp.
References webSocketSendFrame().
Referenced by AsyncWebSocketClient::_runQueue(), AsyncWebSocketBasicMessage::betweenFrames(), and AsyncWebSocketMultiMessage::betweenFrames().
Field Documentation
_data
uint8_t* AsyncWebSocketControl::_data private
Definition at line 247 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketMessageBuffer::get().
_finished
bool AsyncWebSocketControl::_finished private
Definition at line 250 of file AsyncWebSocket.cpp.
_len
size_t AsyncWebSocketControl::_len private
Definition at line 248 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketMessageBuffer::length().
_mask
bool AsyncWebSocketControl::_mask private
Definition at line 249 of file AsyncWebSocket.cpp.
_opcode
uint8_t AsyncWebSocketControl::_opcode private
Definition at line 246 of file AsyncWebSocket.cpp.
The documentation for this class was generated from the following file:
src/ESPAsyncWebServer/AsyncWebSocket.cpp