RBE1001Lib: AsyncEventSourceMessage Class Reference
AsyncEventSourceMessage Class Reference
#include <AsyncEventSource.h>
Public Member Functions
AsyncEventSourceMessage (const char *data, size_t len)
~AsyncEventSourceMessage ()
size_t ack (size_t len, uint32_t time __attribute__((unused)))
size_t send (AsyncClient *client)
bool finished ()
bool sent ()
Private Attributes
uint8_t * _data
size_t _len
size_t _sent
size_t _acked
Detailed Description
Definition at line 53 of file AsyncEventSource.h.
Constructor & Destructor Documentation
AsyncEventSourceMessage()
AsyncEventSourceMessage::AsyncEventSourceMessage (const char * data, size_t len)
Definition at line 109 of file AsyncEventSource.cpp.
References _data, and _len.
~AsyncEventSourceMessage()
AsyncEventSourceMessage::~AsyncEventSourceMessage ()
Definition at line 121 of file AsyncEventSource.cpp.
References _data.
Member Function Documentation
ack()
size_t AsyncEventSourceMessage::ack (size_t len, uint32_t time __attribute__(unused))
Definition at line 126 of file AsyncEventSource.cpp.
References _acked, and _len.
Referenced by AsyncEventSourceClient::_onAck().
finished()
bool AsyncEventSourceMessage::finished () inline
Definition at line 65 of file AsyncEventSource.h.
References _len.
Referenced by AsyncEventSourceClient::_onAck(), and AsyncEventSourceClient::_runQueue().
send()
size_t AsyncEventSourceMessage::send (AsyncClient * client)
Definition at line 140 of file AsyncEventSource.cpp.
References _data, _len, _sent, AsyncClient::add(), AsyncClient::canSend(), AsyncClient::send(), sent(), and AsyncClient::space().
Referenced by AsyncEventSourceClient::client(), and AsyncEventSource::url().
sent()
bool AsyncEventSourceMessage::sent () inline
Definition at line 66 of file AsyncEventSource.h.
References _len.
Referenced by send().
Field Documentation
_acked
size_t AsyncEventSourceMessage::_acked private
Definition at line 59 of file AsyncEventSource.h.
Referenced by ack().
_data
uint8_t* AsyncEventSourceMessage::_data private
Definition at line 55 of file AsyncEventSource.h.
Referenced by AsyncEventSourceMessage(), send(), and ~AsyncEventSourceMessage().
_len
size_t AsyncEventSourceMessage::_len private
Definition at line 56 of file AsyncEventSource.h.
Referenced by ack(), AsyncEventSourceMessage(), finished(), send(), and sent().
_sent
size_t AsyncEventSourceMessage::_sent private
Definition at line 57 of file AsyncEventSource.h.
Referenced by send().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/AsyncEventSource.h
src/ESPAsyncWebServer/AsyncEventSource.cpp