RBE1001Lib: AsyncWebServer Class Reference
AsyncWebServer Class Reference
#include <ESPAsyncWebServer.h>
Public Member Functions
AsyncWebServer (uint16_t port)
~AsyncWebServer ()
void begin ()
void end ()
AsyncWebRewrite & addRewrite (AsyncWebRewrite *rewrite)
bool removeRewrite (AsyncWebRewrite *rewrite)
AsyncWebRewrite & rewrite (const char *from, const char *to)
AsyncWebHandler & addHandler (AsyncWebHandler *handler)
bool removeHandler (AsyncWebHandler *handler)
AsyncCallbackWebHandler & on (const char *uri, ArRequestHandlerFunction onRequest)
AsyncCallbackWebHandler & on (const char *uri, WebRequestMethodComposite method, ArRequestHandlerFunction onRequest)
AsyncCallbackWebHandler & on (const char *uri, WebRequestMethodComposite method, ArRequestHandlerFunction onRequest, ArUploadHandlerFunction onUpload)
AsyncCallbackWebHandler & on (const char *uri, WebRequestMethodComposite method, ArRequestHandlerFunction onRequest, ArUploadHandlerFunction onUpload, ArBodyHandlerFunction onBody)
AsyncStaticWebHandler & serveStatic (const char *uri, fs::FS &fs, const char *path, const char *cache_control=NULL)
void onNotFound (ArRequestHandlerFunction fn)
void onFileUpload (ArUploadHandlerFunction fn)
void onRequestBody (ArBodyHandlerFunction fn)
void reset ()
void _handleDisconnect (AsyncWebServerRequest *request)
void _attachHandler (AsyncWebServerRequest *request)
void _rewriteRequest (AsyncWebServerRequest *request)
Protected Attributes
AsyncServer _server
LinkedList< AsyncWebRewrite * > _rewrites
LinkedList< AsyncWebHandler * > _handlers
AsyncCallbackWebHandler * _catchAllHandler
Detailed Description
Definition at line 397 of file ESPAsyncWebServer.h.
Constructor & Destructor Documentation
AsyncWebServer()
AsyncWebServer::AsyncWebServer (uint16_t port)
Definition at line 33 of file WebServer.cpp.
References _catchAllHandler, _handlers, _server, AsyncClient::close(), AsyncClient::free(), AsyncServer::onClient(), and AsyncClient::setRxTimeout().
~AsyncWebServer()
AsyncWebServer::~AsyncWebServer ()
Definition at line 54 of file WebServer.cpp.
References _catchAllHandler, end(), and reset().
Member Function Documentation
_attachHandler()
void AsyncWebServer::_attachHandler (AsyncWebServerRequest * request)
Definition at line 114 of file WebServer.cpp.
References _catchAllHandler, _handlers, AsyncWebServerRequest::addInterestingHeader(), AsyncWebHandler::canHandle(), AsyncWebHandler::filter(), and AsyncWebServerRequest::setHandler().
Referenced by AsyncWebServerRequest::_parseLine().
_handleDisconnect()
void AsyncWebServer::_handleDisconnect (AsyncWebServerRequest * request)
Definition at line 101 of file WebServer.cpp.
Referenced by AsyncWebServerRequest::_onDisconnect().
_rewriteRequest()
void AsyncWebServer::_rewriteRequest (AsyncWebServerRequest * request)
Definition at line 105 of file WebServer.cpp.
References AsyncWebServerRequest::_addGetParams(), _rewrites, and AsyncWebServerRequest::_url.
Referenced by AsyncWebServerRequest::_parseLine().
addHandler()
AsyncWebHandler & AsyncWebServer::addHandler (AsyncWebHandler * handler)
Definition at line 73 of file WebServer.cpp.
References _handlers, and LinkedList< T, Item >::add().
Referenced by WebPage::initalize(), on(), and serveStatic().
addRewrite()
AsyncWebRewrite & AsyncWebServer::addRewrite (AsyncWebRewrite * rewrite)
Definition at line 60 of file WebServer.cpp.
References _rewrites, LinkedList< T, Item >::add(), and rewrite().
Referenced by rewrite().
begin()
void AsyncWebServer::begin ()
Definition at line 82 of file WebServer.cpp.
References _server, AsyncServer::begin(), and AsyncServer::setNoDelay().
Referenced by WebPage::initalize().
end()
void AsyncWebServer::end ()
Definition at line 87 of file WebServer.cpp.
References _server, and AsyncServer::end().
Referenced by ~AsyncWebServer().
on() [1/4]
AsyncCallbackWebHandler & AsyncWebServer::on (const char * uri, ArRequestHandlerFunction onRequest)
Definition at line 157 of file WebServer.cpp.
References addHandler(), AsyncCallbackWebHandler::onRequest(), and AsyncCallbackWebHandler::setUri().
Referenced by WebPage::initalize().
on() [2/4]
AsyncCallbackWebHandler & AsyncWebServer::on (const char * uri, WebRequestMethodComposite method, ArRequestHandlerFunction onRequest)
Definition at line 148 of file WebServer.cpp.
References addHandler(), AsyncCallbackWebHandler::onRequest(), AsyncCallbackWebHandler::setMethod(), and AsyncCallbackWebHandler::setUri().
on() [3/4]
AsyncCallbackWebHandler & AsyncWebServer::on (const char * uri, WebRequestMethodComposite method, ArRequestHandlerFunction onRequest, ArUploadHandlerFunction onUpload)
Definition at line 138 of file WebServer.cpp.
References addHandler(), AsyncCallbackWebHandler::onRequest(), AsyncCallbackWebHandler::onUpload(), AsyncCallbackWebHandler::setMethod(), and AsyncCallbackWebHandler::setUri().
on() [4/4]
AsyncCallbackWebHandler & AsyncWebServer::on (const char * uri, WebRequestMethodComposite method, ArRequestHandlerFunction onRequest, ArUploadHandlerFunction onUpload, ArBodyHandlerFunction onBody)
Definition at line 127 of file WebServer.cpp.
References addHandler(), AsyncCallbackWebHandler::onBody(), AsyncCallbackWebHandler::onRequest(), AsyncCallbackWebHandler::onUpload(), AsyncCallbackWebHandler::setMethod(), and AsyncCallbackWebHandler::setUri().
onFileUpload()
void AsyncWebServer::onFileUpload (ArUploadHandlerFunction fn)
Definition at line 175 of file WebServer.cpp.
References _catchAllHandler, and AsyncCallbackWebHandler::onUpload().
onNotFound()
void AsyncWebServer::onNotFound (ArRequestHandlerFunction fn)
Definition at line 171 of file WebServer.cpp.
References _catchAllHandler, and AsyncCallbackWebHandler::onRequest().
onRequestBody()
void AsyncWebServer::onRequestBody (ArBodyHandlerFunction fn)
Definition at line 179 of file WebServer.cpp.
References _catchAllHandler, and AsyncCallbackWebHandler::onBody().
removeHandler()
bool AsyncWebServer::removeHandler (AsyncWebHandler * handler)
Definition at line 78 of file WebServer.cpp.
References _handlers, and LinkedList< T, Item >::remove().
removeRewrite()
bool AsyncWebServer::removeRewrite (AsyncWebRewrite * rewrite)
Definition at line 65 of file WebServer.cpp.
References _rewrites, and LinkedList< T, Item >::remove().
reset()
void AsyncWebServer::reset ()
Definition at line 183 of file WebServer.cpp.
References _catchAllHandler, _handlers, _rewrites, LinkedList< T, Item >::free(), AsyncCallbackWebHandler::onBody(), AsyncCallbackWebHandler::onRequest(), and AsyncCallbackWebHandler::onUpload().
Referenced by ~AsyncWebServer().
rewrite()
AsyncWebRewrite & AsyncWebServer::rewrite (const char * from, const char * to)
Definition at line 69 of file WebServer.cpp.
References addRewrite().
Referenced by addRewrite().
serveStatic()
AsyncStaticWebHandler & AsyncWebServer::serveStatic (const char * uri, fs::FS & fs, const char * path, const char * cache_control = NULL)
Definition at line 165 of file WebServer.cpp.
References addHandler().
Field Documentation
_catchAllHandler
AsyncCallbackWebHandler* AsyncWebServer::_catchAllHandler protected
Definition at line 402 of file ESPAsyncWebServer.h.
Referenced by _attachHandler(), AsyncWebServer(), onFileUpload(), onNotFound(), onRequestBody(), reset(), and ~AsyncWebServer().
_handlers
LinkedList<AsyncWebHandler*> AsyncWebServer::_handlers protected
Definition at line 401 of file ESPAsyncWebServer.h.
Referenced by _attachHandler(), addHandler(), AsyncWebServer(), removeHandler(), and reset().
_rewrites
LinkedList<AsyncWebRewrite*> AsyncWebServer::_rewrites protected
Definition at line 400 of file ESPAsyncWebServer.h.
Referenced by _rewriteRequest(), addRewrite(), removeRewrite(), and reset().
_server
AsyncServer AsyncWebServer::_server protected
Definition at line 399 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServer(), begin(), and end().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/ESPAsyncWebServer.h
src/ESPAsyncWebServer/WebServer.cpp