RBE1001Lib: SPIFFSEditor Class Reference
SPIFFSEditor Class Reference
#include <SPIFFSEditor.h>
Public Member Functions
SPIFFSEditor (const String &username=String(), const String &password=String(), const fs::FS &fs=SPIFFS)
virtual bool canHandle (AsyncWebServerRequest *request) override final
virtual void handleRequest (AsyncWebServerRequest *request) override final
virtual void handleUpload (AsyncWebServerRequest *request, const String &filename, size_t index, uint8_t *data, size_t len, bool final) override final
virtual bool isRequestHandlerTrivial () override final
Public Member Functions inherited from AsyncWebHandler
AsyncWebHandler ()
AsyncWebHandler & setFilter (ArRequestFilterFunction fn)
AsyncWebHandler & setAuthentication (const char *username, const char *password)
bool filter (AsyncWebServerRequest *request)
virtual ~AsyncWebHandler ()
virtual bool canHandle (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleRequest (AsyncWebServerRequest *request __attribute__((unused)))
virtual void handleUpload (AsyncWebServerRequest *request __attribute__((unused)), const String &filename __attribute__((unused)), size_t index __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), bool final __attribute__((unused)))
virtual void handleBody (AsyncWebServerRequest *request __attribute__((unused)), uint8_t *data __attribute__((unused)), size_t len __attribute__((unused)), size_t index __attribute__((unused)), size_t total __attribute__((unused)))
Private Attributes
fs::FS _fs
String _username
String _password
bool _authenticated
uint32_t _startTime
Additional Inherited Members
Protected Attributes inherited from AsyncWebHandler
ArRequestFilterFunction _filter
String _username
String _password
Detailed Description
Definition at line 5 of file SPIFFSEditor.h.
Constructor & Destructor Documentation
SPIFFSEditor()
SPIFFSEditor::SPIFFSEditor (const String & username = String(), const String & password = String(), const fs::FS & fs = SPIFFS)
Definition at line 382 of file SPIFFSEditor.cpp.
Referenced by isExcluded().
Member Function Documentation
canHandle()
bool SPIFFSEditor::canHandle (AsyncWebServerRequest * request) final override virtual
Definition at line 391 of file SPIFFSEditor.cpp.
References AsyncWebServerRequest::_tempFile, AsyncWebServerRequest::addInterestingHeader(), AsyncWebServerRequest::arg(), AsyncWebServerRequest::hasParam(), HTTP_DELETE, HTTP_GET, HTTP_POST, HTTP_PUT, AsyncWebServerRequest::method(), and AsyncWebServerRequest::url().
handleRequest()
void SPIFFSEditor::handleRequest (AsyncWebServerRequest * request) final override virtual
Definition at line 435 of file SPIFFSEditor.cpp.
References AsyncWebServerRequest::_tempFile, AsyncWebServerResponse::addHeader(), AsyncWebServerRequest::authenticate(), AsyncWebServerRequest::beginResponse_P(), edit_htm_gz_len, AsyncWebServerRequest::getParam(), AsyncWebServerRequest::hasParam(), AsyncWebServerRequest::header(), HTTP_DELETE, HTTP_GET, HTTP_POST, HTTP_PUT, isExcluded(), AsyncWebServerRequest::method(), AsyncWebServerRequest::requestAuthentication(), AsyncWebServerRequest::send(), and AsyncWebParameter::value().
handleUpload()
void SPIFFSEditor::handleUpload (AsyncWebServerRequest * request, const String & filename, size_t index, uint8_t * data, size_t len, bool final) final override virtual
Definition at line 528 of file SPIFFSEditor.cpp.
References AsyncWebServerRequest::_tempFile, and AsyncWebServerRequest::authenticate().
isRequestHandlerTrivial()
virtual bool SPIFFSEditor::isRequestHandlerTrivial () inline final override virtual
Reimplemented from AsyncWebHandler.
Definition at line 21 of file SPIFFSEditor.h.
Field Documentation
_authenticated
bool SPIFFSEditor::_authenticated private
Definition at line 10 of file SPIFFSEditor.h.
_fs
fs::FS SPIFFSEditor::_fs private
Definition at line 7 of file SPIFFSEditor.h.
_password
String SPIFFSEditor::_password private
Definition at line 9 of file SPIFFSEditor.h.
_startTime
uint32_t SPIFFSEditor::_startTime private
Definition at line 11 of file SPIFFSEditor.h.
_username
String SPIFFSEditor::_username private
Definition at line 8 of file SPIFFSEditor.h.
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/SPIFFSEditor.h
src/ESPAsyncWebServer/SPIFFSEditor.cpp