RBE1001Lib: AsyncWebSocketClient Class Reference
AsyncWebSocketClient Class Reference
#include <AsyncWebSocket.h>
Public Member Functions
AsyncWebSocketClient (AsyncWebServerRequest *request, AsyncWebSocket *server)
~AsyncWebSocketClient ()
uint32_t id ()
AwsClientStatus status ()
AsyncClient * client ()
AsyncWebSocket * server ()
AwsFrameInfo const & pinfo () const
IPAddress remoteIP ()
uint16_t remotePort ()
void close (uint16_t code=0, const char *message=NULL)
void ping (uint8_t *data=NULL, size_t len=0)
void keepAlivePeriod (uint16_t seconds)
uint16_t keepAlivePeriod ()
void message (AsyncWebSocketMessage *message)
bool queueIsFull ()
size_t printf (const char *format,...) __attribute__((format(printf
size_t size_t printf_P (PGM_P formatP,...) __attribute__((format(printf
size_t size_t void text (const char *message, size_t len)
void text (const char *message)
void text (uint8_t *message, size_t len)
void text (char *message)
void text (const String &message)
void text (const __FlashStringHelper *data)
void text (AsyncWebSocketMessageBuffer *buffer)
void binary (const char *message, size_t len)
void binary (const char *message)
void binary (uint8_t *message, size_t len)
void binary (char *message)
void binary (const String &message)
void binary (const __FlashStringHelper *data, size_t len)
void binary (AsyncWebSocketMessageBuffer *buffer)
bool canSend ()
void _onAck (size_t len, uint32_t time)
void _onError (int8_t)
void _onPoll ()
void _onTimeout (uint32_t time)
void _onDisconnect ()
void _onData (void *pbuf, size_t plen)
Data Fields
void * _tempObject
Private Member Functions
void _queueMessage (AsyncWebSocketMessage *dataMessage)
void _queueControl (AsyncWebSocketControl *controlMessage)
void _runQueue ()
Private Attributes
AsyncClient * _client
AsyncWebSocket * _server
uint32_t _clientId
AwsClientStatus _status
LinkedList< AsyncWebSocketControl * > _controlQueue
LinkedList< AsyncWebSocketMessage * > _messageQueue
uint8_t _pstate
AwsFrameInfo _pinfo
uint32_t _lastMessageTime
uint32_t _keepAlivePeriod
Detailed Description
Definition at line 157 of file AsyncWebSocket.h.
Constructor & Destructor Documentation
AsyncWebSocketClient()
AsyncWebSocketClient::AsyncWebSocketClient (AsyncWebServerRequest * request, AsyncWebSocket * server)
Definition at line 477 of file AsyncWebSocket.cpp.
References AsyncWebSocket::_addClient(), _client, _clientId, AsyncWebSocket::_getNextId(), AsyncWebSocket::_handleEvent(), _keepAlivePeriod, _lastMessageTime, _messageQueue, _onAck(), _onData(), _onDisconnect(), _onError(), _onPoll(), _onTimeout(), _pstate, _server, _status, _tempObject, AsyncClient::onAck(), AsyncClient::onData(), AsyncClient::onDisconnect(), AsyncClient::onError(), AsyncClient::onPoll(), AsyncClient::onTimeout(), server(), AsyncClient::setRxTimeout(), WS_CONNECTED, and WS_EVT_CONNECT.
~AsyncWebSocketClient()
AsyncWebSocketClient::~AsyncWebSocketClient ()
Definition at line 501 of file AsyncWebSocket.cpp.
References _controlQueue, AsyncWebSocket::_handleEvent(), _messageQueue, _server, LinkedList< T, Item >::free(), and WS_EVT_DISCONNECT.
Member Function Documentation
_onAck()
void AsyncWebSocketClient::_onAck (size_t len, uint32_t time)
Definition at line 507 of file AsyncWebSocket.cpp.
References AsyncWebSocket::_cleanBuffers(), _client, _controlQueue, _lastMessageTime, _messageQueue, _runQueue(), _server, _status, AsyncWebSocketMessage::ack(), AsyncClient::close(), LinkedList< T, Item >::front(), LinkedList< T, Item >::isEmpty(), AsyncWebSocketControl::len(), LinkedList< T, Item >::remove(), WS_DISCONNECT, WS_DISCONNECTED, and WS_DISCONNECTING.
Referenced by AsyncWebSocketClient().
_onData()
void AsyncWebSocketClient::_onData (void * pbuf, size_t plen)
Definition at line 621 of file AsyncWebSocket.cpp.
References _client, AsyncWebSocket::_handleEvent(), _lastMessageTime, _pinfo, _pstate, _queueControl(), _server, _status, AsyncClient::ackLater(), AWSC_PING_PAYLOAD, AWSC_PING_PAYLOAD_LEN, AsyncClient::close(), AwsFrameInfo::final, AwsFrameInfo::index, AwsFrameInfo::len, AwsFrameInfo::mask, AwsFrameInfo::masked, AwsFrameInfo::message_opcode, AwsFrameInfo::num, AwsFrameInfo::opcode, WS_DISCONNECT, WS_DISCONNECTED, WS_DISCONNECTING, WS_EVT_DATA, WS_EVT_ERROR, WS_EVT_PONG, WS_PING, and WS_PONG.
Referenced by AsyncWebSocketClient().
_onDisconnect()
void AsyncWebSocketClient::_onDisconnect ()
Definition at line 616 of file AsyncWebSocket.cpp.
References _client, AsyncWebSocket::_handleDisconnect(), and _server.
Referenced by AsyncWebSocketClient().
_onError()
void AsyncWebSocketClient::_onError (int8_t)
Definition at line 609 of file AsyncWebSocket.cpp.
Referenced by AsyncWebSocketClient().
_onPoll()
void AsyncWebSocketClient::_onPoll ()
Definition at line 529 of file AsyncWebSocket.cpp.
References _client, _controlQueue, _keepAlivePeriod, _lastMessageTime, _messageQueue, _runQueue(), AWSC_PING_PAYLOAD, AWSC_PING_PAYLOAD_LEN, AsyncClient::canSend(), LinkedList< T, Item >::isEmpty(), and ping().
Referenced by AsyncWebSocketClient().
_onTimeout()
void AsyncWebSocketClient::_onTimeout (uint32_t time)
Definition at line 611 of file AsyncWebSocket.cpp.
References _client, and AsyncClient::close().
Referenced by AsyncWebSocketClient().
_queueControl()
void AsyncWebSocketClient::_queueControl (AsyncWebSocketControl * controlMessage) private
Definition at line 571 of file AsyncWebSocket.cpp.
References _client, _controlQueue, _runQueue(), LinkedList< T, Item >::add(), and AsyncClient::canSend().
Referenced by _onData(), close(), and ping().
_queueMessage()
void AsyncWebSocketClient::_queueMessage (AsyncWebSocketMessage * dataMessage) private
Definition at line 554 of file AsyncWebSocket.cpp.
References _client, _messageQueue, _runQueue(), _status, LinkedList< T, Item >::add(), AsyncClient::canSend(), LinkedList< T, Item >::length(), WS_CONNECTED, and WS_MAX_QUEUED_MESSAGES.
Referenced by binary(), and text().
_runQueue()
void AsyncWebSocketClient::_runQueue () private
Definition at line 537 of file AsyncWebSocket.cpp.
References _client, _controlQueue, _messageQueue, AsyncWebSocketMessage::betweenFrames(), AsyncWebSocketMessage::finished(), LinkedList< T, Item >::front(), LinkedList< T, Item >::isEmpty(), AsyncWebSocketControl::len(), LinkedList< T, Item >::remove(), AsyncWebSocketMessage::send(), AsyncWebSocketControl::send(), and webSocketSendFrameWindow().
Referenced by _onAck(), _onPoll(), _queueControl(), and _queueMessage().
binary() [1/7]
void AsyncWebSocketClient::binary (const char * message, size_t len)
Definition at line 810 of file AsyncWebSocket.cpp.
References _queueMessage(), and WS_BINARY.
Referenced by binary(), and AsyncWebSocket::binary().
binary() [2/7]
void AsyncWebSocketClient::binary (const char * message)
Definition at line 813 of file AsyncWebSocket.cpp.
References binary().
binary() [3/7]
void AsyncWebSocketClient::binary (uint8_t * message, size_t len)
Definition at line 816 of file AsyncWebSocket.cpp.
References binary().
binary() [4/7]
void AsyncWebSocketClient::binary (char * message)
Definition at line 819 of file AsyncWebSocket.cpp.
References binary().
binary() [5/7]
void AsyncWebSocketClient::binary (const String & message)
Definition at line 822 of file AsyncWebSocket.cpp.
References binary().
binary() [6/7]
void AsyncWebSocketClient::binary (const __FlashStringHelper * data, size_t len)
Definition at line 825 of file AsyncWebSocket.cpp.
References binary(), and message().
binary() [7/7]
void AsyncWebSocketClient::binary (AsyncWebSocketMessageBuffer * buffer)
Definition at line 836 of file AsyncWebSocket.cpp.
References _queueMessage(), and WS_BINARY.
canSend()
bool AsyncWebSocketClient::canSend () inline
Definition at line 229 of file AsyncWebSocket.h.
References LinkedList< T, Item >::length(), and WS_MAX_QUEUED_MESSAGES.
client()
AsyncClient* AsyncWebSocketClient::client () inline
Definition at line 186 of file AsyncWebSocket.h.
close()
void AsyncWebSocketClient::close (uint16_t code = 0, const char * message = NULL)
Definition at line 579 of file AsyncWebSocket.cpp.
References _queueControl(), _status, WS_CONNECTED, and WS_DISCONNECT.
Referenced by AsyncWebSocket::close().
id()
uint32_t AsyncWebSocketClient::id () inline
Definition at line 184 of file AsyncWebSocket.h.
Referenced by AsyncWebSocket::_handleDisconnect().
keepAlivePeriod() [1/2]
void AsyncWebSocketClient::keepAlivePeriod (uint16_t seconds) inline
Definition at line 198 of file AsyncWebSocket.h.
keepAlivePeriod() [2/2]
uint16_t AsyncWebSocketClient::keepAlivePeriod () inline
Definition at line 201 of file AsyncWebSocket.h.
message()
void AsyncWebSocketClient::message (AsyncWebSocketMessage * message) inline
Definition at line 206 of file AsyncWebSocket.h.
References AsyncWebSocketControl::len().
Referenced by binary(), AsyncWebSocket::message(), and text().
pinfo()
AwsFrameInfo const& AsyncWebSocketClient::pinfo () const inline
Definition at line 188 of file AsyncWebSocket.h.
References AsyncWebSocketControl::len().
ping()
void AsyncWebSocketClient::ping (uint8_t * data = NULL, size_t len = 0)
Definition at line 604 of file AsyncWebSocket.cpp.
References _queueControl(), _status, WS_CONNECTED, and WS_PING.
Referenced by _onPoll(), and AsyncWebSocket::ping().
printf()
size_t AsyncWebSocketClient::printf (const char * format, ...)
Definition at line 712 of file AsyncWebSocket.cpp.
References MAX_PRINTF_LEN, and text().
Referenced by AsyncWebSocket::printf().
printf_P()
size_t AsyncWebSocketClient::printf_P (PGM_P formatP, ...)
Definition at line 743 of file AsyncWebSocket.cpp.
References MAX_PRINTF_LEN, and text().
Referenced by AsyncWebSocket::printf_P().
queueIsFull()
bool AsyncWebSocketClient::queueIsFull ()
Definition at line 549 of file AsyncWebSocket.cpp.
References _messageQueue, _status, LinkedList< T, Item >::length(), WS_CONNECTED, and WS_MAX_QUEUED_MESSAGES.
remoteIP()
IPAddress AsyncWebSocketClient::remoteIP ()
Definition at line 841 of file AsyncWebSocket.cpp.
References _client, and AsyncClient::remoteIP().
remotePort()
uint16_t AsyncWebSocketClient::remotePort ()
Definition at line 848 of file AsyncWebSocket.cpp.
References _client, and AsyncClient::remotePort().
server()
AsyncWebSocket* AsyncWebSocketClient::server () inline
Definition at line 187 of file AsyncWebSocket.h.
Referenced by AsyncWebSocketClient().
status()
AwsClientStatus AsyncWebSocketClient::status () inline
Definition at line 185 of file AsyncWebSocket.h.
Referenced by AsyncWebSocket::count().
text() [1/7]
void AsyncWebSocketClient::text (const char * message, size_t len)
Definition at line 774 of file AsyncWebSocket.cpp.
References _queueMessage().
Referenced by printf(), printf_P(), text(), and AsyncWebSocket::text().
text() [2/7]
void AsyncWebSocketClient::text (const char * message)
Definition at line 777 of file AsyncWebSocket.cpp.
References text().
text() [3/7]
void AsyncWebSocketClient::text (uint8_t * message, size_t len)
Definition at line 780 of file AsyncWebSocket.cpp.
References text().
text() [4/7]
void AsyncWebSocketClient::text (char * message)
Definition at line 783 of file AsyncWebSocket.cpp.
References text().
text() [5/7]
void AsyncWebSocketClient::text (const String & message)
Definition at line 786 of file AsyncWebSocket.cpp.
References text().
text() [6/7]
void AsyncWebSocketClient::text (const __FlashStringHelper * data)
Definition at line 789 of file AsyncWebSocket.cpp.
References message(), and text().
text() [7/7]
void AsyncWebSocketClient::text (AsyncWebSocketMessageBuffer * buffer)
Definition at line 805 of file AsyncWebSocket.cpp.
References _queueMessage().
Field Documentation
_client
AsyncClient* AsyncWebSocketClient::_client private
Definition at line 159 of file AsyncWebSocket.h.
Referenced by _onAck(), _onData(), _onDisconnect(), _onPoll(), _onTimeout(), _queueControl(), _queueMessage(), _runQueue(), AsyncWebSocketClient(), remoteIP(), and remotePort().
_clientId
uint32_t AsyncWebSocketClient::_clientId private
Definition at line 161 of file AsyncWebSocket.h.
Referenced by AsyncWebSocketClient().
_controlQueue
LinkedList<AsyncWebSocketControl *> AsyncWebSocketClient::_controlQueue private
Definition at line 164 of file AsyncWebSocket.h.
Referenced by _onAck(), _onPoll(), _queueControl(), _runQueue(), and ~AsyncWebSocketClient().
_keepAlivePeriod
uint32_t AsyncWebSocketClient::_keepAlivePeriod private
Definition at line 171 of file AsyncWebSocket.h.
Referenced by _onPoll(), and AsyncWebSocketClient().
_lastMessageTime
uint32_t AsyncWebSocketClient::_lastMessageTime private
Definition at line 170 of file AsyncWebSocket.h.
Referenced by _onAck(), _onData(), _onPoll(), and AsyncWebSocketClient().
_messageQueue
LinkedList<AsyncWebSocketMessage *> AsyncWebSocketClient::_messageQueue private
Definition at line 165 of file AsyncWebSocket.h.
Referenced by _onAck(), _onPoll(), _queueMessage(), _runQueue(), AsyncWebSocketClient(), queueIsFull(), and ~AsyncWebSocketClient().
_pinfo
AwsFrameInfo AsyncWebSocketClient::_pinfo private
Definition at line 168 of file AsyncWebSocket.h.
Referenced by _onData().
_pstate
uint8_t AsyncWebSocketClient::_pstate private
Definition at line 167 of file AsyncWebSocket.h.
Referenced by _onData(), and AsyncWebSocketClient().
_server
AsyncWebSocket* AsyncWebSocketClient::_server private
Definition at line 160 of file AsyncWebSocket.h.
Referenced by _onAck(), _onData(), _onDisconnect(), AsyncWebSocketClient(), and ~AsyncWebSocketClient().
_status
AwsClientStatus AsyncWebSocketClient::_status private
Definition at line 162 of file AsyncWebSocket.h.
Referenced by _onAck(), _onData(), _queueMessage(), AsyncWebSocketClient(), close(), ping(), and queueIsFull().
_tempObject
void* AsyncWebSocketClient::_tempObject
Definition at line 178 of file AsyncWebSocket.h.
Referenced by AsyncWebSocketClient().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/AsyncWebSocket.h
src/ESPAsyncWebServer/AsyncWebSocket.cpp