RBE1001Lib: AsyncWebServerRequest Class Reference
AsyncWebServerRequest Class Reference
#include <ESPAsyncWebServer.h>
Public Member Functions
AsyncWebServerRequest (AsyncWebServer *, AsyncClient *)
~AsyncWebServerRequest ()
AsyncClient * client ()
uint8_t version () const
WebRequestMethodComposite method () const
const String & url () const
const String & host () const
const String & contentType () const
size_t contentLength () const
bool multipart () const
const char * methodToString () const
const char * requestedConnTypeToString () const
RequestedConnectionType requestedConnType () const
bool isExpectedRequestedConnType (RequestedConnectionType erct1, RequestedConnectionType erct2=RCT_NOT_USED, RequestedConnectionType erct3=RCT_NOT_USED)
void onDisconnect (ArDisconnectHandler fn)
bool authenticate (const char *hash)
bool authenticate (const char *username, const char *password, const char *realm=NULL, bool passwordIsHash=false)
void requestAuthentication (const char *realm=NULL, bool isDigest=true)
void setHandler (AsyncWebHandler *handler)
void addInterestingHeader (const String &name)
void redirect (const String &url)
void send (AsyncWebServerResponse *response)
void send (int code, const String &contentType=String(), const String &content=String())
void send (FS &fs, const String &path, const String &contentType=String(), bool download=false, AwsTemplateProcessor callback=nullptr)
void send (File content, const String &path, const String &contentType=String(), bool download=false, AwsTemplateProcessor callback=nullptr)
void send (Stream &stream, const String &contentType, size_t len, AwsTemplateProcessor callback=nullptr)
void send (const String &contentType, size_t len, AwsResponseFiller callback, AwsTemplateProcessor templateCallback=nullptr)
void sendChunked (const String &contentType, AwsResponseFiller callback, AwsTemplateProcessor templateCallback=nullptr)
void send_P (int code, const String &contentType, const uint8_t *content, size_t len, AwsTemplateProcessor callback=nullptr)
void send_P (int code, const String &contentType, PGM_P content, AwsTemplateProcessor callback=nullptr)
AsyncWebServerResponse * beginResponse (int code, const String &contentType=String(), const String &content=String())
AsyncWebServerResponse * beginResponse (FS &fs, const String &path, const String &contentType=String(), bool download=false, AwsTemplateProcessor callback=nullptr)
AsyncWebServerResponse * beginResponse (File content, const String &path, const String &contentType=String(), bool download=false, AwsTemplateProcessor callback=nullptr)
AsyncWebServerResponse * beginResponse (Stream &stream, const String &contentType, size_t len, AwsTemplateProcessor callback=nullptr)
AsyncWebServerResponse * beginResponse (const String &contentType, size_t len, AwsResponseFiller callback, AwsTemplateProcessor templateCallback=nullptr)
AsyncWebServerResponse * beginChunkedResponse (const String &contentType, AwsResponseFiller callback, AwsTemplateProcessor templateCallback=nullptr)
AsyncResponseStream * beginResponseStream (const String &contentType, size_t bufferSize=1460)
AsyncWebServerResponse * beginResponse_P (int code, const String &contentType, const uint8_t *content, size_t len, AwsTemplateProcessor callback=nullptr)
AsyncWebServerResponse * beginResponse_P (int code, const String &contentType, PGM_P content, AwsTemplateProcessor callback=nullptr)
size_t headers () const
bool hasHeader (const String &name) const
bool hasHeader (const __FlashStringHelper *data) const
AsyncWebHeader * getHeader (const String &name) const
AsyncWebHeader * getHeader (const __FlashStringHelper *data) const
AsyncWebHeader * getHeader (size_t num) const
size_t params () const
bool hasParam (const String &name, bool post=false, bool file=false) const
bool hasParam (const __FlashStringHelper *data, bool post=false, bool file=false) const
AsyncWebParameter * getParam (const String &name, bool post=false, bool file=false) const
AsyncWebParameter * getParam (const __FlashStringHelper *data, bool post, bool file) const
AsyncWebParameter * getParam (size_t num) const
size_t args () const
const String & arg (const String &name) const
const String & arg (const __FlashStringHelper *data) const
const String & arg (size_t i) const
const String & argName (size_t i) const
bool hasArg (const char *name) const
bool hasArg (const __FlashStringHelper *data) const
const String &ASYNCWEBSERVER_REGEX_ATTRIBUTE pathArg (size_t i) const
const String & header (const char *name) const
const String & header (const __FlashStringHelper *data) const
const String & header (size_t i) const
const String & headerName (size_t i) const
String urlDecode (const String &text) const
Data Fields
File _tempFile
void * _tempObject
Private Types
using File = fs::File
using FS = fs::FS
Private Member Functions
void _removeNotInterestingHeaders ()
void _onPoll ()
void _onAck (size_t len, uint32_t time)
void _onError (int8_t error)
void _onTimeout (uint32_t time)
void _onDisconnect ()
void _onData (void *buf, size_t len)
void _addParam (AsyncWebParameter *)
void _addPathParam (const char *param)
bool _parseReqHead ()
bool _parseReqHeader ()
void _parseLine ()
void _parsePlainPostChar (uint8_t data)
void _parseMultipartPostByte (uint8_t data, bool last)
void _addGetParams (const String &params)
void _handleUploadStart ()
void _handleUploadByte (uint8_t data, bool last)
void _handleUploadEnd ()
Private Attributes
AsyncClient * _client
AsyncWebServer * _server
AsyncWebHandler * _handler
AsyncWebServerResponse * _response
StringArray _interestingHeaders
ArDisconnectHandler _onDisconnectfn
String _temp
uint8_t _parseState
uint8_t _version
WebRequestMethodComposite _method
String _url
String _host
String _contentType
String _boundary
String _authorization
RequestedConnectionType _reqconntype
bool _isDigest
bool _isMultipart
bool _isPlainPost
bool _expectingContinue
size_t _contentLength
size_t _parsedLength
LinkedList< AsyncWebHeader * > _headers
LinkedList< AsyncWebParameter * > _params
LinkedList< String * > _pathParams
uint8_t _multiParseState
uint8_t _boundaryPosition
size_t _itemStartIndex
size_t _itemSize
String _itemName
String _itemFilename
String _itemType
String _itemValue
uint8_t * _itemBuffer
size_t _itemBufferIndex
bool _itemIsFile
Friends
class AsyncWebServer
class AsyncCallbackWebHandler
Detailed Description
Definition at line 134 of file ESPAsyncWebServer.h.
Member Typedef Documentation
File
using AsyncWebServerRequest::File = fs::File private
Definition at line 135 of file ESPAsyncWebServer.h.
FS
using AsyncWebServerRequest::FS = fs::FS private
Definition at line 136 of file ESPAsyncWebServer.h.
Constructor & Destructor Documentation
AsyncWebServerRequest()
AsyncWebServerRequest::AsyncWebServerRequest (AsyncWebServer * s, AsyncClient * c)
Definition at line 35 of file WebRequest.cpp.
References _boundaryPosition, _itemBuffer, _itemBufferIndex, _itemFilename, _itemIsFile, _itemName, _itemSize, _itemStartIndex, _itemType, _itemValue, _multiParseState, _onAck(), _onData(), _onDisconnect(), _onError(), _onPoll(), _onTimeout(), _params, _pathParams, _tempObject, AsyncClient::onAck(), AsyncClient::onData(), AsyncClient::onDisconnect(), AsyncClient::onPoll(), and AsyncClient::onTimeout().
~AsyncWebServerRequest()
AsyncWebServerRequest::~AsyncWebServerRequest ()
Definition at line 80 of file WebRequest.cpp.
References _headers, _interestingHeaders, _params, _pathParams, _response, _tempFile, _tempObject, and LinkedList< T, Item >::free().
Member Function Documentation
_addGetParams()
void AsyncWebServerRequest::_addGetParams (const String & params) private
Definition at line 240 of file WebRequest.cpp.
References _addParam(), and urlDecode().
Referenced by _parseReqHead(), and AsyncWebServer::_rewriteRequest().
_addParam()
void AsyncWebServerRequest::_addParam (AsyncWebParameter * p) private
Definition at line 232 of file WebRequest.cpp.
References _params, and LinkedList< T, Item >::add().
Referenced by _addGetParams(), _parseMultipartPostByte(), and _parsePlainPostChar().
_addPathParam()
void AsyncWebServerRequest::_addPathParam (const char * param) private
Definition at line 236 of file WebRequest.cpp.
References _pathParams, and LinkedList< T, Item >::add().
_handleUploadByte()
void AsyncWebServerRequest::_handleUploadByte (uint8_t data, bool last) private
Definition at line 369 of file WebRequest.cpp.
References _handler, _itemBuffer, _itemBufferIndex, _itemFilename, _itemSize, and AsyncWebHandler::handleUpload().
_handleUploadEnd()
void AsyncWebServerRequest::_handleUploadEnd () private
_handleUploadStart()
void AsyncWebServerRequest::_handleUploadStart () private
_onAck()
void AsyncWebServerRequest::_onAck (size_t len, uint32_t time) private
Definition at line 197 of file WebRequest.cpp.
References AsyncWebServerResponse::_ack(), AsyncWebServerResponse::_finished(), and _response.
Referenced by AsyncWebServerRequest().
_onData()
void AsyncWebServerRequest::_onData (void * buf, size_t len) private
Definition at line 101 of file WebRequest.cpp.
References __is_param_char, _contentLength, _contentType, _handler, _isMultipart, _isPlainPost, _parsedLength, _parseLine(), _parseMultipartPostByte(), _parsePlainPostChar(), _parseState, _temp, AsyncWebHandler::handleBody(), AsyncWebHandler::handleRequest(), AsyncWebHandler::isRequestHandlerTrivial(), PARSE_REQ_BODY, PARSE_REQ_END, and send().
Referenced by AsyncWebServerRequest().
_onDisconnect()
void AsyncWebServerRequest::_onDisconnect () private
Definition at line 224 of file WebRequest.cpp.
References AsyncWebServer::_handleDisconnect(), _onDisconnectfn, and _server.
Referenced by AsyncWebServerRequest(), and send().
_onError()
void AsyncWebServerRequest::_onError (int8_t error) private
Definition at line 210 of file WebRequest.cpp.
Referenced by AsyncWebServerRequest().
_onPoll()
void AsyncWebServerRequest::_onPoll () private
Definition at line 190 of file WebRequest.cpp.
References AsyncWebServerResponse::_ack(), _client, AsyncWebServerResponse::_finished(), _response, and AsyncClient::canSend().
Referenced by AsyncWebServerRequest().
_onTimeout()
void AsyncWebServerRequest::_onTimeout (uint32_t time) private
Definition at line 214 of file WebRequest.cpp.
References _client, and AsyncClient::close().
Referenced by AsyncWebServerRequest().
_parseLine()
void AsyncWebServerRequest::_parseLine () private
Definition at line 554 of file WebRequest.cpp.
References AsyncWebServer::_attachHandler(), _client, _contentLength, _expectingContinue, _handler, _parseReqHead(), _parseReqHeader(), _parseState, _removeNotInterestingHeaders(), AsyncWebServer::_rewriteRequest(), _server, _temp, AsyncClient::close(), AsyncWebHandler::handleRequest(), os_strlen, PARSE_REQ_BODY, PARSE_REQ_END, PARSE_REQ_FAIL, PARSE_REQ_HEADERS, PARSE_REQ_START, send(), and AsyncClient::write().
Referenced by _onData().
_parseMultipartPostByte()
void AsyncWebServerRequest::_parseMultipartPostByte (uint8_t data, bool last) private
Definition at line 394 of file WebRequest.cpp.
References _addParam(), _boundary, _boundaryPosition, _contentLength, _handler, _itemBuffer, _itemBufferIndex, _itemFilename, _itemIsFile, _itemName, _itemSize, _itemStartIndex, _itemType, _itemValue, _multiParseState, _parsedLength, _temp, BOUNDARY_OR_DATA, DASH3_OR_RETURN2, EXPECT_BOUNDARY, EXPECT_DASH1, EXPECT_DASH2, EXPECT_FEED1, EXPECT_FEED2, AsyncWebHandler::handleUpload(), itemWriteByte, PARSE_ERROR, PARSE_HEADERS, PARSING_FINISHED, and WAIT_FOR_RETURN1.
Referenced by _onData().
_parsePlainPostChar()
void AsyncWebServerRequest::_parsePlainPostChar (uint8_t data) private
Definition at line 354 of file WebRequest.cpp.
References _addParam(), _contentLength, _parsedLength, _temp, and urlDecode().
Referenced by _onData().
_parseReqHead()
bool AsyncWebServerRequest::_parseReqHead () private
Definition at line 254 of file WebRequest.cpp.
References _addGetParams(), _method, _temp, _url, _version, HTTP_DELETE, HTTP_GET, HTTP_HEAD, HTTP_OPTIONS, HTTP_PATCH, HTTP_POST, HTTP_PUT, and urlDecode().
Referenced by _parseLine().
_parseReqHeader()
bool AsyncWebServerRequest::_parseReqHeader () private
Definition at line 312 of file WebRequest.cpp.
References _authorization, _boundary, _contentLength, _contentType, _expectingContinue, _headers, _host, _isDigest, _isMultipart, _reqconntype, _temp, LinkedList< T, Item >::add(), RCT_EVENT, RCT_WS, and strContains().
Referenced by _parseLine().
_removeNotInterestingHeaders()
void AsyncWebServerRequest::_removeNotInterestingHeaders () private
Definition at line 181 of file WebRequest.cpp.
References _headers, _interestingHeaders, StringArray::containsIgnoreCase(), and header().
Referenced by _parseLine().
addInterestingHeader()
void AsyncWebServerRequest::addInterestingHeader (const String & name)
Definition at line 706 of file WebRequest.cpp.
References _interestingHeaders, LinkedList< T, Item >::add(), and StringArray::containsIgnoreCase().
Referenced by AsyncWebServer::_attachHandler(), SPIFFSEditor::canHandle(), AsyncStaticWebHandler::canHandle(), AsyncEventSource::canHandle(), and AsyncWebSocket::canHandle().
arg() [1/3]
const String & AsyncWebServerRequest::arg (const String & name) const
Definition at line 888 of file WebRequest.cpp.
References _params, and SharedEmptyString.
Referenced by arg(), SPIFFSEditor::canHandle(), hasArg(), and WebPage::initalize().
arg() [2/3]
const String & AsyncWebServerRequest::arg (const __FlashStringHelper * data) const
Definition at line 897 of file WebRequest.cpp.
References arg(), and SharedEmptyString.
arg() [3/3]
const String & AsyncWebServerRequest::arg (size_t i) const
Definition at line 912 of file WebRequest.cpp.
References getParam(), and AsyncWebParameter::value().
argName()
const String & AsyncWebServerRequest::argName (size_t i) const
Definition at line 916 of file WebRequest.cpp.
References getParam(), and AsyncWebParameter::name().
Referenced by WebPage::initalize().
args()
size_t AsyncWebServerRequest::args () const inline
Definition at line 272 of file ESPAsyncWebServer.h.
References ASYNCWEBSERVER_REGEX_ATTRIBUTE.
Referenced by WebPage::initalize().
authenticate() [1/2]
bool AsyncWebServerRequest::authenticate (const char * hash)
Definition at line 825 of file WebRequest.cpp.
References _authorization, _isDigest, checkDigestAuthentication(), and methodToString().
Referenced by SPIFFSEditor::handleRequest(), AsyncStaticWebHandler::handleRequest(), AsyncEventSource::handleRequest(), AsyncWebSocket::handleRequest(), and SPIFFSEditor::handleUpload().
authenticate() [2/2]
bool AsyncWebServerRequest::authenticate (const char * username, const char * password, const char * realm = NULL, bool passwordIsHash = false)
Definition at line 813 of file WebRequest.cpp.
References _authorization, _isDigest, checkBasicAuthentication(), checkDigestAuthentication(), and methodToString().
beginChunkedResponse()
AsyncWebServerResponse * AsyncWebServerRequest::beginChunkedResponse (const String & contentType, AwsResponseFiller callback, AwsTemplateProcessor templateCallback = nullptr)
Definition at line 753 of file WebRequest.cpp.
References _version.
Referenced by sendChunked().
beginResponse() [1/5]
AsyncWebServerResponse * AsyncWebServerRequest::beginResponse (int code, const String & contentType = String(), const String & content = String())
Definition at line 729 of file WebRequest.cpp.
Referenced by AsyncWebSocket::handleRequest(), redirect(), requestAuthentication(), and send().
beginResponse() [2/5]
AsyncWebServerResponse * AsyncWebServerRequest::beginResponse (FS & fs, const String & path, const String & contentType = String(), bool download = false, AwsTemplateProcessor callback = nullptr)
Definition at line 733 of file WebRequest.cpp.
beginResponse() [3/5]
AsyncWebServerResponse * AsyncWebServerRequest::beginResponse (File content, const String & path, const String & contentType = String(), bool download = false, AwsTemplateProcessor callback = nullptr)
Definition at line 739 of file WebRequest.cpp.
beginResponse() [4/5]
AsyncWebServerResponse * AsyncWebServerRequest::beginResponse (Stream & stream, const String & contentType, size_t len, AwsTemplateProcessor callback = nullptr)
Definition at line 745 of file WebRequest.cpp.
beginResponse() [5/5]
AsyncWebServerResponse * AsyncWebServerRequest::beginResponse (const String & contentType, size_t len, AwsResponseFiller callback, AwsTemplateProcessor templateCallback = nullptr)
Definition at line 749 of file WebRequest.cpp.
beginResponse_P() [1/2]
AsyncWebServerResponse * AsyncWebServerRequest::beginResponse_P (int code, const String & contentType, const uint8_t * content, size_t len, AwsTemplateProcessor callback = nullptr)
Definition at line 763 of file WebRequest.cpp.
Referenced by beginResponse_P(), SPIFFSEditor::handleRequest(), and send_P().
beginResponse_P() [2/2]
AsyncWebServerResponse * AsyncWebServerRequest::beginResponse_P (int code, const String & contentType, PGM_P content, AwsTemplateProcessor callback = nullptr)
Definition at line 767 of file WebRequest.cpp.
References beginResponse_P().
beginResponseStream()
AsyncResponseStream * AsyncWebServerRequest::beginResponseStream (const String & contentType, size_t bufferSize = 1460)
Definition at line 759 of file WebRequest.cpp.
client()
AsyncClient* AsyncWebServerRequest::client () inline
Definition at line 210 of file ESPAsyncWebServer.h.
Referenced by AsyncBasicResponse::_ack(), AsyncAbstractResponse::_ack(), AsyncBasicResponse::_respond(), AsyncEventSourceResponse::_respond(), AsyncWebSocketResponse::_respond(), AsyncWebServerResponse::_respond(), ON_AP_FILTER(), and ON_STA_FILTER().
contentLength()
size_t AsyncWebServerRequest::contentLength () const inline
Definition at line 216 of file ESPAsyncWebServer.h.
contentType()
const String& AsyncWebServerRequest::contentType () const inline
Definition at line 215 of file ESPAsyncWebServer.h.
getHeader() [1/3]
AsyncWebHeader * AsyncWebServerRequest::getHeader (const String & name) const
Definition at line 621 of file WebRequest.cpp.
References _headers.
Referenced by getHeader(), AsyncWebSocket::handleRequest(), header(), and headerName().
getHeader() [2/3]
AsyncWebHeader * AsyncWebServerRequest::getHeader (const __FlashStringHelper * data) const
Definition at line 630 of file WebRequest.cpp.
References getHeader().
getHeader() [3/3]
AsyncWebHeader * AsyncWebServerRequest::getHeader (size_t num) const
Definition at line 644 of file WebRequest.cpp.
References _headers, header(), and LinkedList< T, Item >::nth().
getParam() [1/3]
AsyncWebParameter * AsyncWebServerRequest::getParam (const String & name, bool post = false, bool file = false) const
Definition at line 678 of file WebRequest.cpp.
References _params, AsyncWebParameter::isFile(), AsyncWebParameter::isPost(), and AsyncWebParameter::name().
Referenced by arg(), argName(), getParam(), and SPIFFSEditor::handleRequest().
getParam() [2/3]
AsyncWebParameter * AsyncWebServerRequest::getParam (const __FlashStringHelper * data, bool post, bool file) const
Definition at line 687 of file WebRequest.cpp.
References getParam().
getParam() [3/3]
AsyncWebParameter * AsyncWebServerRequest::getParam (size_t num) const
Definition at line 701 of file WebRequest.cpp.
References _params, and LinkedList< T, Item >::nth().
hasArg() [1/2]
bool AsyncWebServerRequest::hasArg (const char * name) const
Definition at line 864 of file WebRequest.cpp.
References _params, and arg().
Referenced by hasArg().
hasArg() [2/2]
bool AsyncWebServerRequest::hasArg (const __FlashStringHelper * data) const
Definition at line 873 of file WebRequest.cpp.
References hasArg().
hasHeader() [1/2]
bool AsyncWebServerRequest::hasHeader (const String & name) const
Definition at line 592 of file WebRequest.cpp.
References _headers.
Referenced by AsyncStaticWebHandler::handleRequest(), AsyncWebSocket::handleRequest(), and hasHeader().
hasHeader() [2/2]
bool AsyncWebServerRequest::hasHeader (const __FlashStringHelper * data) const
Definition at line 601 of file WebRequest.cpp.
References hasHeader().
hasParam() [1/2]
bool AsyncWebServerRequest::hasParam (const String & name, bool post = false, bool file = false) const
Definition at line 653 of file WebRequest.cpp.
References _params, AsyncWebParameter::isFile(), AsyncWebParameter::isPost(), and AsyncWebParameter::name().
Referenced by SPIFFSEditor::canHandle(), SPIFFSEditor::handleRequest(), and hasParam().
hasParam() [2/2]
bool AsyncWebServerRequest::hasParam (const __FlashStringHelper * data, bool post = false, bool file = false) const
Definition at line 662 of file WebRequest.cpp.
References hasParam().
header() [1/3]
const String & AsyncWebServerRequest::header (const char * name) const
Definition at line 925 of file WebRequest.cpp.
References getHeader(), SharedEmptyString, and AsyncWebHeader::value().
Referenced by _removeNotInterestingHeaders(), getHeader(), SPIFFSEditor::handleRequest(), AsyncStaticWebHandler::handleRequest(), header(), and requestAuthentication().
header() [2/3]
const String & AsyncWebServerRequest::header (const __FlashStringHelper * data) const
Definition at line 930 of file WebRequest.cpp.
References header(), and SharedEmptyString.
header() [3/3]
const String & AsyncWebServerRequest::header (size_t i) const
Definition at line 945 of file WebRequest.cpp.
References getHeader(), SharedEmptyString, and AsyncWebHeader::value().
headerName()
const String & AsyncWebServerRequest::headerName (size_t i) const
Definition at line 950 of file WebRequest.cpp.
References getHeader(), AsyncWebHeader::name(), and SharedEmptyString.
headers()
size_t AsyncWebServerRequest::headers () const
Definition at line 588 of file WebRequest.cpp.
References _headers, and LinkedList< T, Item >::length().
host()
const String& AsyncWebServerRequest::host () const inline
Definition at line 214 of file ESPAsyncWebServer.h.
isExpectedRequestedConnType()
bool AsyncWebServerRequest::isExpectedRequestedConnType (RequestedConnectionType erct1, RequestedConnectionType erct2 = RCT_NOT_USED, RequestedConnectionType erct3 = RCT_NOT_USED)
Definition at line 1002 of file WebRequest.cpp.
References _reqconntype, and RCT_NOT_USED.
Referenced by AsyncStaticWebHandler::canHandle(), and AsyncWebSocket::canHandle().
method()
WebRequestMethodComposite AsyncWebServerRequest::method () const inline
Definition at line 212 of file ESPAsyncWebServer.h.
References AsyncCallbackWebHandler::_method.
Referenced by SPIFFSEditor::canHandle(), AsyncStaticWebHandler::canHandle(), AsyncEventSource::canHandle(), AsyncWebSocket::canHandle(), and SPIFFSEditor::handleRequest().
methodToString()
const char * AsyncWebServerRequest::methodToString () const
Definition at line 979 of file WebRequest.cpp.
References _method, HTTP_ANY, HTTP_DELETE, HTTP_GET, HTTP_HEAD, HTTP_OPTIONS, HTTP_PATCH, HTTP_POST, and HTTP_PUT.
Referenced by authenticate().
multipart()
bool AsyncWebServerRequest::multipart () const inline
Definition at line 217 of file ESPAsyncWebServer.h.
onDisconnect()
void AsyncWebServerRequest::onDisconnect (ArDisconnectHandler fn)
Definition at line 220 of file WebRequest.cpp.
References _onDisconnectfn.
params()
size_t AsyncWebServerRequest::params () const
Definition at line 649 of file WebRequest.cpp.
References _params, and LinkedList< T, Item >::length().
pathArg()
const String & AsyncWebServerRequest::pathArg (size_t i) const
Definition at line 920 of file WebRequest.cpp.
References _pathParams, LinkedList< T, Item >::nth(), and SharedEmptyString.
redirect()
void AsyncWebServerRequest::redirect (const String & url)
Definition at line 807 of file WebRequest.cpp.
References AsyncWebServerResponse::addHeader(), beginResponse(), and send().
requestAuthentication()
void AsyncWebServerRequest::requestAuthentication (const char * realm = NULL, bool isDigest = true)
Definition at line 847 of file WebRequest.cpp.
References AsyncWebServerResponse::addHeader(), beginResponse(), header(), requestDigestAuthentication(), and send().
Referenced by SPIFFSEditor::handleRequest(), AsyncStaticWebHandler::handleRequest(), AsyncEventSource::handleRequest(), and AsyncWebSocket::handleRequest().
requestedConnType()
RequestedConnectionType AsyncWebServerRequest::requestedConnType () const inline
Definition at line 220 of file ESPAsyncWebServer.h.
References RCT_NOT_USED.
requestedConnTypeToString()
const char * AsyncWebServerRequest::requestedConnTypeToString () const
Definition at line 991 of file WebRequest.cpp.
References _reqconntype, RCT_DEFAULT, RCT_EVENT, RCT_HTTP, RCT_NOT_USED, and RCT_WS.
send() [1/6]
void AsyncWebServerRequest::send (AsyncWebServerResponse * response)
Definition at line 711 of file WebRequest.cpp.
References _client, _onDisconnect(), AsyncWebServerResponse::_respond(), _response, AsyncWebServerResponse::_sourceValid(), AsyncClient::close(), and AsyncClient::setRxTimeout().
Referenced by _onData(), _parseLine(), SPIFFSEditor::handleRequest(), AsyncStaticWebHandler::handleRequest(), AsyncEventSource::handleRequest(), AsyncWebSocket::handleRequest(), WebPage::initalize(), redirect(), requestAuthentication(), send(), send_P(), and sendChunked().
send() [2/6]
void AsyncWebServerRequest::send (int code, const String & contentType = String(), const String & content = String())
Definition at line 771 of file WebRequest.cpp.
References beginResponse(), and send().
send() [3/6]
void AsyncWebServerRequest::send (FS & fs, const String & path, const String & contentType = String(), bool download = false, AwsTemplateProcessor callback = nullptr)
Definition at line 775 of file WebRequest.cpp.
References beginResponse(), and send().
send() [4/6]
void AsyncWebServerRequest::send (File content, const String & path, const String & contentType = String(), bool download = false, AwsTemplateProcessor callback = nullptr)
Definition at line 781 of file WebRequest.cpp.
References beginResponse(), and send().
send() [5/6]
void AsyncWebServerRequest::send (Stream & stream, const String & contentType, size_t len, AwsTemplateProcessor callback = nullptr)
Definition at line 787 of file WebRequest.cpp.
References beginResponse(), and send().
send() [6/6]
void AsyncWebServerRequest::send (const String & contentType, size_t len, AwsResponseFiller callback, AwsTemplateProcessor templateCallback = nullptr)
Definition at line 791 of file WebRequest.cpp.
References beginResponse(), and send().
send_P() [1/2]
void AsyncWebServerRequest::send_P (int code, const String & contentType, const uint8_t * content, size_t len, AwsTemplateProcessor callback = nullptr)
Definition at line 799 of file WebRequest.cpp.
References beginResponse_P(), and send().
send_P() [2/2]
void AsyncWebServerRequest::send_P (int code, const String & contentType, PGM_P content, AwsTemplateProcessor callback = nullptr)
Definition at line 803 of file WebRequest.cpp.
References beginResponse_P(), and send().
sendChunked()
void AsyncWebServerRequest::sendChunked (const String & contentType, AwsResponseFiller callback, AwsTemplateProcessor templateCallback = nullptr)
Definition at line 795 of file WebRequest.cpp.
References beginChunkedResponse(), and send().
setHandler()
void AsyncWebServerRequest::setHandler (AsyncWebHandler * handler) inline
Definition at line 231 of file ESPAsyncWebServer.h.
References AsyncWebParameter::name().
Referenced by AsyncWebServer::_attachHandler().
url()
const String& AsyncWebServerRequest::url () const inline
Definition at line 213 of file ESPAsyncWebServer.h.
Referenced by AsyncStaticWebHandler::_getFile(), SPIFFSEditor::canHandle(), AsyncStaticWebHandler::canHandle(), AsyncEventSource::canHandle(), AsyncWebSocket::canHandle(), and AsyncWebRewrite::match().
urlDecode()
String AsyncWebServerRequest::urlDecode (const String & text) const
Definition at line 955 of file WebRequest.cpp.
Referenced by _addGetParams(), _parsePlainPostChar(), and _parseReqHead().
version()
uint8_t AsyncWebServerRequest::version () const inline
Definition at line 211 of file ESPAsyncWebServer.h.
Referenced by AsyncBasicResponse::_respond(), AsyncAbstractResponse::_respond(), AsyncEventSourceResponse::_respond(), and AsyncWebSocketResponse::_respond().
Friends And Related Function Documentation
AsyncCallbackWebHandler
friend class AsyncCallbackWebHandler friend
Definition at line 138 of file ESPAsyncWebServer.h.
AsyncWebServer
friend class AsyncWebServer friend
Definition at line 137 of file ESPAsyncWebServer.h.
Field Documentation
_authorization
String AsyncWebServerRequest::_authorization private
Definition at line 156 of file ESPAsyncWebServer.h.
Referenced by _parseReqHeader(), and authenticate().
_boundary
String AsyncWebServerRequest::_boundary private
Definition at line 155 of file ESPAsyncWebServer.h.
Referenced by _parseMultipartPostByte(), and _parseReqHeader().
_boundaryPosition
uint8_t AsyncWebServerRequest::_boundaryPosition private
Definition at line 171 of file ESPAsyncWebServer.h.
Referenced by _parseMultipartPostByte(), and AsyncWebServerRequest().
_client
AsyncClient* AsyncWebServerRequest::_client private
Definition at line 140 of file ESPAsyncWebServer.h.
Referenced by _onPoll(), _onTimeout(), _parseLine(), and send().
_contentLength
size_t AsyncWebServerRequest::_contentLength private
Definition at line 163 of file ESPAsyncWebServer.h.
Referenced by _onData(), _parseLine(), _parseMultipartPostByte(), _parsePlainPostChar(), and _parseReqHeader().
_contentType
String AsyncWebServerRequest::_contentType private
Definition at line 154 of file ESPAsyncWebServer.h.
Referenced by _onData(), and _parseReqHeader().
_expectingContinue
bool AsyncWebServerRequest::_expectingContinue private
Definition at line 162 of file ESPAsyncWebServer.h.
Referenced by _parseLine(), and _parseReqHeader().
_handler
AsyncWebHandler* AsyncWebServerRequest::_handler private
Definition at line 142 of file ESPAsyncWebServer.h.
Referenced by _handleUploadByte(), _onData(), _parseLine(), and _parseMultipartPostByte().
_headers
LinkedList<AsyncWebHeader *> AsyncWebServerRequest::_headers private
Definition at line 166 of file ESPAsyncWebServer.h.
Referenced by _parseReqHeader(), _removeNotInterestingHeaders(), getHeader(), hasHeader(), headers(), and ~AsyncWebServerRequest().
_host
String AsyncWebServerRequest::_host private
Definition at line 153 of file ESPAsyncWebServer.h.
Referenced by _parseReqHeader().
_interestingHeaders
StringArray AsyncWebServerRequest::_interestingHeaders private
Definition at line 144 of file ESPAsyncWebServer.h.
Referenced by _removeNotInterestingHeaders(), addInterestingHeader(), and ~AsyncWebServerRequest().
_isDigest
bool AsyncWebServerRequest::_isDigest private
Definition at line 159 of file ESPAsyncWebServer.h.
Referenced by _parseReqHeader(), and authenticate().
_isMultipart
bool AsyncWebServerRequest::_isMultipart private
Definition at line 160 of file ESPAsyncWebServer.h.
Referenced by _onData(), and _parseReqHeader().
_isPlainPost
bool AsyncWebServerRequest::_isPlainPost private
Definition at line 161 of file ESPAsyncWebServer.h.
Referenced by _onData().
_itemBuffer
uint8_t* AsyncWebServerRequest::_itemBuffer private
Definition at line 178 of file ESPAsyncWebServer.h.
Referenced by _handleUploadByte(), _parseMultipartPostByte(), and AsyncWebServerRequest().
_itemBufferIndex
size_t AsyncWebServerRequest::_itemBufferIndex private
Definition at line 179 of file ESPAsyncWebServer.h.
Referenced by _handleUploadByte(), _parseMultipartPostByte(), and AsyncWebServerRequest().
_itemFilename
String AsyncWebServerRequest::_itemFilename private
Definition at line 175 of file ESPAsyncWebServer.h.
Referenced by _handleUploadByte(), _parseMultipartPostByte(), and AsyncWebServerRequest().
_itemIsFile
bool AsyncWebServerRequest::_itemIsFile private
Definition at line 180 of file ESPAsyncWebServer.h.
Referenced by _parseMultipartPostByte(), and AsyncWebServerRequest().
_itemName
String AsyncWebServerRequest::_itemName private
Definition at line 174 of file ESPAsyncWebServer.h.
Referenced by _parseMultipartPostByte(), and AsyncWebServerRequest().
_itemSize
size_t AsyncWebServerRequest::_itemSize private
Definition at line 173 of file ESPAsyncWebServer.h.
Referenced by _handleUploadByte(), _parseMultipartPostByte(), and AsyncWebServerRequest().
_itemStartIndex
size_t AsyncWebServerRequest::_itemStartIndex private
Definition at line 172 of file ESPAsyncWebServer.h.
Referenced by _parseMultipartPostByte(), and AsyncWebServerRequest().
_itemType
String AsyncWebServerRequest::_itemType private
Definition at line 176 of file ESPAsyncWebServer.h.
Referenced by _parseMultipartPostByte(), and AsyncWebServerRequest().
_itemValue
String AsyncWebServerRequest::_itemValue private
Definition at line 177 of file ESPAsyncWebServer.h.
Referenced by _parseMultipartPostByte(), and AsyncWebServerRequest().
_method
WebRequestMethodComposite AsyncWebServerRequest::_method private
Definition at line 151 of file ESPAsyncWebServer.h.
Referenced by _parseReqHead(), and methodToString().
_multiParseState
uint8_t AsyncWebServerRequest::_multiParseState private
Definition at line 170 of file ESPAsyncWebServer.h.
Referenced by _parseMultipartPostByte(), and AsyncWebServerRequest().
_onDisconnectfn
ArDisconnectHandler AsyncWebServerRequest::_onDisconnectfn private
Definition at line 145 of file ESPAsyncWebServer.h.
Referenced by _onDisconnect(), and onDisconnect().
_params
LinkedList<AsyncWebParameter *> AsyncWebServerRequest::_params private
Definition at line 167 of file ESPAsyncWebServer.h.
Referenced by _addParam(), arg(), AsyncWebServerRequest(), getParam(), hasArg(), hasParam(), params(), and ~AsyncWebServerRequest().
_parsedLength
size_t AsyncWebServerRequest::_parsedLength private
Definition at line 164 of file ESPAsyncWebServer.h.
Referenced by _onData(), _parseMultipartPostByte(), and _parsePlainPostChar().
_parseState
uint8_t AsyncWebServerRequest::_parseState private
Definition at line 148 of file ESPAsyncWebServer.h.
Referenced by _onData(), and _parseLine().
_pathParams
LinkedList<String *> AsyncWebServerRequest::_pathParams private
Definition at line 168 of file ESPAsyncWebServer.h.
Referenced by _addPathParam(), AsyncWebServerRequest(), pathArg(), and ~AsyncWebServerRequest().
_reqconntype
RequestedConnectionType AsyncWebServerRequest::_reqconntype private
Definition at line 157 of file ESPAsyncWebServer.h.
Referenced by _parseReqHeader(), isExpectedRequestedConnType(), and requestedConnTypeToString().
_response
AsyncWebServerResponse* AsyncWebServerRequest::_response private
Definition at line 143 of file ESPAsyncWebServer.h.
Referenced by _onAck(), _onPoll(), send(), and ~AsyncWebServerRequest().
_server
AsyncWebServer* AsyncWebServerRequest::_server private
Definition at line 141 of file ESPAsyncWebServer.h.
Referenced by _onDisconnect(), and _parseLine().
_temp
String AsyncWebServerRequest::_temp private
Definition at line 147 of file ESPAsyncWebServer.h.
Referenced by _onData(), _parseLine(), _parseMultipartPostByte(), _parsePlainPostChar(), _parseReqHead(), and _parseReqHeader().
_tempFile
File AsyncWebServerRequest::_tempFile
Definition at line 204 of file ESPAsyncWebServer.h.
Referenced by AsyncStaticWebHandler::_fileExists(), SPIFFSEditor::canHandle(), SPIFFSEditor::handleRequest(), AsyncStaticWebHandler::handleRequest(), SPIFFSEditor::handleUpload(), and ~AsyncWebServerRequest().
_tempObject
void* AsyncWebServerRequest::_tempObject
Definition at line 205 of file ESPAsyncWebServer.h.
Referenced by AsyncStaticWebHandler::_fileExists(), AsyncWebServerRequest(), AsyncStaticWebHandler::handleRequest(), and ~AsyncWebServerRequest().
_url
String AsyncWebServerRequest::_url private
Definition at line 152 of file ESPAsyncWebServer.h.
Referenced by _parseReqHead(), and AsyncWebServer::_rewriteRequest().
_version
uint8_t AsyncWebServerRequest::_version private
Definition at line 150 of file ESPAsyncWebServer.h.
Referenced by _parseReqHead(), and beginChunkedResponse().
The documentation for this class was generated from the following files:
src/ESPAsyncWebServer/ESPAsyncWebServer.h
src/ESPAsyncWebServer/WebRequest.cpp