RBE1001Lib: /home/hephaestus/git/ESP32Servo/src/ESP32PWM.cpp File Reference
ESP32PWM.cpp File Reference
#include <ESP32PWM.h>
#include "esp32-hal-ledc.h"
Functions
ESP32PWM * pwmFactory (int pin)
Function Documentation
pwmFactory()
ESP32PWM* pwmFactory (int pin)
Definition at line 305 of file ESP32PWM.cpp.
References ESP32PWM::getPin(), and NUM_PWM.
Referenced by analogWrite(), ESP32PWM::channelsRemaining(), loop(), noTone(), and tone().