RBE1001Lib: /home/hephaestus/git/ESP32Servo/src/ESP32PWM.h File Reference
ESP32PWM.h File Reference
#include "esp32-hal-ledc.h"
#include <cstdint>
#include "Arduino.h"
Data Structures
class ESP32PWM
Macros
#define NUM_PWM 16
#define PWM_BASE_INDEX 0
#define USABLE_ESP32_PWM (NUM_PWM-PWM_BASE_INDEX)
Functions
ESP32PWM * pwmFactory (int pin)
Macro Definition Documentation
NUM_PWM
#define NUM_PWM 16
Definition at line 11 of file ESP32PWM.h.
Referenced by ESP32PWM::channelsRemaining(), ESP32PWM::ESP32PWM(), pwmFactory(), and ESP32PWM::timerAndIndexToChannel().
PWM_BASE_INDEX
#define PWM_BASE_INDEX 0
Definition at line 12 of file ESP32PWM.h.
Referenced by ESP32PWM::ESP32PWM().
USABLE_ESP32_PWM
#define USABLE_ESP32_PWM (NUM_PWM-PWM_BASE_INDEX)
Definition at line 13 of file ESP32PWM.h.
Function Documentation
pwmFactory()
ESP32PWM* pwmFactory (int pin)
Definition at line 305 of file ESP32PWM.cpp.
References ESP32PWM::getPin(), and NUM_PWM.
Referenced by analogWrite(), ESP32PWM::channelsRemaining(), loop(), noTone(), and tone().