RBE1001Lib: /home/hephaestus/git/ESP32Servo/src/ESP32Tone.h File Reference
ESP32Tone.h File Reference
#include "ESP32PWM.h"
Functions
void tone (int pin, unsigned int frequency)
void tone (int pin, unsigned int frequency, unsigned long duration)
void noTone (int pin)
Function Documentation
noTone()
void noTone (int pin)
Definition at line 29 of file ESP32Tone.cpp.
References ESP32PWM::attached(), ESP32PWM::detachPin(), and pwmFactory().
Referenced by tone().
tone() [1/2]
void tone (int pin, unsigned int frequency)
Definition at line 11 of file ESP32Tone.cpp.
References ESP32PWM::attached(), ESP32PWM::attachPin(), pwmFactory(), and ESP32PWM::writeTone().
Referenced by loop(), and tone().
tone() [2/2]
void tone (int pin, unsigned int frequency, unsigned long duration)
Definition at line 23 of file ESP32Tone.cpp.
References noTone(), and tone().