RBE1001Lib: src/ESPAsyncWebServer/ESPAsyncWebServer.h File Reference
ESPAsyncWebServer.h File Reference
#include "Arduino.h"
#include <functional>
#include "FS.h"
#include "StringArray.h"
#include "WebResponseImpl.h"
#include "WebHandlerImpl.h"
#include "AsyncWebSocket.h"
#include "AsyncEventSource.h"
Data Structures
class AsyncWebParameter
class AsyncWebHeader
class AsyncWebServerRequest
class AsyncWebRewrite
class AsyncWebHandler
class AsyncWebServerResponse
class AsyncWebServer
class DefaultHeaders
Macros
#define ASYNCWEBSERVER_REGEX_ATTRIBUTE __attribute__((warning("ASYNCWEBSERVER_REGEX not defined")))
#define DEBUGF(...)
#define RESPONSE_TRY_AGAIN 0xFFFFFFFF
Typedefs
typedef uint8_t WebRequestMethodComposite
typedef std::function< void(void)> ArDisconnectHandler
typedef std::function< size_t(uint8_t *, size_t, size_t)> AwsResponseFiller
typedef std::function< String(const String &)> AwsTemplateProcessor
typedef std::function< bool(AsyncWebServerRequest *request)> ArRequestFilterFunction
typedef std::function< void(AsyncWebServerRequest *request)> ArRequestHandlerFunction
typedef std::function< void(AsyncWebServerRequest *request, const String &filename, size_t index, uint8_t *data, size_t len, bool final)> ArUploadHandlerFunction
typedef std::function< void(AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total)> ArBodyHandlerFunction
Enumerations
enum WebRequestMethod {
HTTP_GET = 0b00000001, HTTP_POST = 0b00000010, HTTP_DELETE = 0b00000100, HTTP_PUT = 0b00001000,
HTTP_PATCH = 0b00010000, HTTP_HEAD = 0b00100000, HTTP_OPTIONS = 0b01000000, HTTP_ANY = 0b01111111
}
enum RequestedConnectionType {
RCT_NOT_USED = -1, RCT_DEFAULT = 0, RCT_HTTP, RCT_WS,
RCT_EVENT, RCT_MAX
}
enum WebResponseState {
RESPONSE_SETUP, RESPONSE_HEADERS, RESPONSE_CONTENT, RESPONSE_WAIT_ACK,
RESPONSE_END, RESPONSE_FAILED
}
Functions
bool ON_STA_FILTER (AsyncWebServerRequest *request)
bool ON_AP_FILTER (AsyncWebServerRequest *request)
Macro Definition Documentation
ASYNCWEBSERVER_REGEX_ATTRIBUTE
#define ASYNCWEBSERVER_REGEX_ATTRIBUTE __attribute__((warning("ASYNCWEBSERVER_REGEX not defined")))
Definition at line 44 of file ESPAsyncWebServer.h.
Referenced by AsyncWebServerRequest::args().
DEBUGF
#define DEBUGF (...)
Definition at line 47 of file ESPAsyncWebServer.h.
Referenced by AsyncStaticWebHandler::canHandle().
RESPONSE_TRY_AGAIN
#define RESPONSE_TRY_AGAIN 0xFFFFFFFF
Definition at line 74 of file ESPAsyncWebServer.h.
Referenced by AsyncAbstractResponse::_ack(), AsyncCallbackResponse::_fillBuffer(), and AsyncChunkedResponse::_fillBuffer().
Typedef Documentation
ArBodyHandlerFunction
typedef std::function<void(AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total)> ArBodyHandlerFunction
Definition at line 395 of file ESPAsyncWebServer.h.
ArDisconnectHandler
typedef std::function<void(void)> ArDisconnectHandler
Definition at line 77 of file ESPAsyncWebServer.h.
ArRequestFilterFunction
typedef std::function<bool(AsyncWebServerRequest *request)> ArRequestFilterFunction
Definition at line 293 of file ESPAsyncWebServer.h.
ArRequestHandlerFunction
typedef std::function<void(AsyncWebServerRequest *request)> ArRequestHandlerFunction
Definition at line 393 of file ESPAsyncWebServer.h.
ArUploadHandlerFunction
typedef std::function<void(AsyncWebServerRequest *request, const String& filename, size_t index, uint8_t *data, size_t len, bool final)> ArUploadHandlerFunction
Definition at line 394 of file ESPAsyncWebServer.h.
AwsResponseFiller
typedef std::function<size_t(uint8_t*, size_t, size_t)> AwsResponseFiller
Definition at line 131 of file ESPAsyncWebServer.h.
AwsTemplateProcessor
typedef std::function<String(const String&)> AwsTemplateProcessor
Definition at line 132 of file ESPAsyncWebServer.h.
WebRequestMethodComposite
typedef uint8_t WebRequestMethodComposite
Definition at line 76 of file ESPAsyncWebServer.h.
Enumeration Type Documentation
RequestedConnectionType
enum RequestedConnectionType
Enumerator
RCT_NOT_USED
RCT_DEFAULT
RCT_HTTP
RCT_WS
RCT_EVENT
RCT_MAX
Definition at line 129 of file ESPAsyncWebServer.h.
WebRequestMethod
enum WebRequestMethod
Enumerator
HTTP_GET
HTTP_POST
HTTP_DELETE
HTTP_PUT
HTTP_PATCH
HTTP_HEAD
HTTP_OPTIONS
HTTP_ANY
Definition at line 61 of file ESPAsyncWebServer.h.
WebResponseState
enum WebResponseState
Enumerator
RESPONSE_SETUP
RESPONSE_HEADERS
RESPONSE_CONTENT
RESPONSE_WAIT_ACK
RESPONSE_END
RESPONSE_FAILED
Definition at line 354 of file ESPAsyncWebServer.h.
Function Documentation
ON_AP_FILTER()
bool ON_AP_FILTER (AsyncWebServerRequest * request)
Definition at line 28 of file WebServer.cpp.
References AsyncWebServerRequest::client(), and AsyncClient::localIP().
ON_STA_FILTER()
bool ON_STA_FILTER (AsyncWebServerRequest * request)
Definition at line 24 of file WebServer.cpp.
References AsyncWebServerRequest::client(), and AsyncClient::localIP().