RBE1001Lib: examples/FullSystemTest/FullSystemTest.ino File Reference
FullSystemTest.ino File Reference
#include <Arduino.h>
#include <RBE1001Lib.h>
#include "Motor.h"
#include "Rangefinder.h"
#include <ESP32Servo.h>
#include <ESP32AnalogRead.h>
Functions
void setup ()
void loop ()
Variables
Motor motor1
Motor motor2
Rangefinder rangefinder1
Servo lifter
ESP32AnalogRead leftLineSensor
ESP32AnalogRead rightLineSensor
ESP32AnalogRead servoPositionFeedback
bool upDown =false
Function Documentation
loop()
void loop ()
Definition at line 40 of file FullSystemTest.ino.
References Motor::getCurrentDegrees(), Motor::getDegreesPerSecond(), Rangefinder::getDistanceCM(), Rangefinder::getTimeoutState(), leftLineSensor, lifter, rightLineSensor, servoPositionFeedback, Motor::SetSetpointWithLinearInterpolation(), Motor::SetSetpointWithSinusoidalInterpolation(), and upDown.
setup()
void setup ()
Definition at line 20 of file FullSystemTest.ino.
References Motor::allocateTimer(), Rangefinder::attach(), Motor::attach(), LEFT_LINE_SENSE, leftLineSensor, lifter, MOTOR1_DIR, MOTOR1_ENCA, MOTOR1_ENCB, MOTOR1_PWM, MOTOR2_DIR, MOTOR2_ENCA, MOTOR2_ENCB, MOTOR2_PWM, RIGHT_LINE_SENSE, rightLineSensor, SERVO_FEEDBACK_SENSOR, SERVO_PIN, servoPositionFeedback, SIDE_ULTRASONIC_ECHO, and SIDE_ULTRASONIC_TRIG.
Variable Documentation
leftLineSensor
ESP32AnalogRead leftLineSensor
Definition at line 12 of file FullSystemTest.ino.
Referenced by loop(), and setup().
lifter
Servo lifter
Definition at line 11 of file FullSystemTest.ino.
Referenced by loop(), and setup().
motor1
Motor motor1
Definition at line 8 of file FullSystemTest.ino.
motor2
Motor motor2
Definition at line 9 of file FullSystemTest.ino.
rangefinder1
Rangefinder rangefinder1
Definition at line 10 of file FullSystemTest.ino.
rightLineSensor
ESP32AnalogRead rightLineSensor
Definition at line 13 of file FullSystemTest.ino.
Referenced by loop(), and setup().
servoPositionFeedback
ESP32AnalogRead servoPositionFeedback
Definition at line 14 of file FullSystemTest.ino.
Referenced by loop(), and setup().
upDown
bool upDown =false
Definition at line 15 of file FullSystemTest.ino.
Referenced by loop().