RBE1001Lib: /home/hephaestus/git/ESP32Servo/examples/Knob/Knob.ino File Reference
Knob.ino File Reference
#include <ESP32Servo.h>
Functions
void setup ()
void loop ()
Variables
Servo myservo
int servoPin = 18
int potPin = 34
int ADC_Max = 4096
int val
Function Documentation
loop()
void loop ()
Definition at line 69 of file Knob.ino.
References ADC_Max, potPin, val, and Servo::write().
setup()
void setup ()
Definition at line 54 of file Knob.ino.
References ESP32PWM::allocateTimer(), Servo::attach(), servoPin, and Servo::setPeriodHertz().
Variable Documentation
ADC_Max
int ADC_Max = 4096
Definition at line 48 of file Knob.ino.
Referenced by loop().
myservo
Servo myservo
Definition at line 42 of file Knob.ino.
potPin
int potPin = 34
Definition at line 47 of file Knob.ino.
Referenced by loop().
servoPin
int servoPin = 18
Definition at line 45 of file Knob.ino.
Referenced by setup().
val
int val
Definition at line 52 of file Knob.ino.
Referenced by loop(), and ESP32PWM::setup().