RBE1001Lib: examples/LineTrackerTest/LineTrackerTest.ino File Reference
LineTrackerTest.ino File Reference
#include <Arduino.h>
#include <RBE1001Lib.h>
#include "Rangefinder.h"
Functions
void setup ()
void loop ()
Variables
Rangefinder rangefinder1 (FORWARD_ULTRASONIC_TRIG, FORWARD_ULTRASONIC_ECHO)
Rangefinder rangefinder2 (SIDE_ULTRASONIC_TRIG, SIDE_ULTRASONIC_ECHO)
Function Documentation
loop()
void loop ()
Definition at line 25 of file LineTrackerTest.ino.
References Rangefinder::getDistanceCM(), rangefinder1, and rangefinder2.
setup()
void setup ()
Definition at line 12 of file LineTrackerTest.ino.
Variable Documentation
rangefinder1
Rangefinder rangefinder1(FORWARD_ULTRASONIC_TRIG, FORWARD_ULTRASONIC_ECHO)
Referenced by loop().
rangefinder2
Rangefinder rangefinder2(SIDE_ULTRASONIC_TRIG, SIDE_ULTRASONIC_ECHO)
Referenced by loop().