RBE1001Lib: examples/MotorVelocityTest/MotorVelocityTest.ino File Reference
MotorVelocityTest.ino File Reference
#include <Arduino.h>
#include <RBE1001Lib.h>
Functions
void setup ()
void loop ()
Variables
Motor left_motor
Motor right_motor
bool upDown =false
Function Documentation
loop()
void loop ()
Definition at line 27 of file MotorVelocityTest.ino.
References Motor::getCurrentDegrees(), Motor::getDegreesPerSecond(), Motor::GetEffortPercent(), Motor::SetSpeed(), and upDown.
setup()
void setup ()
Definition at line 11 of file MotorVelocityTest.ino.
References Motor::allocateTimer(), Motor::attach(), MOTOR_LEFT_DIR, MOTOR_LEFT_ENCA, MOTOR_LEFT_ENCB, MOTOR_LEFT_PWM, MOTOR_RIGHT_DIR, MOTOR_RIGHT_ENCA, MOTOR_RIGHT_ENCB, MOTOR_RIGHT_PWM, and Motor::SetSpeed().
Variable Documentation
left_motor
Motor left_motor
Definition at line 4 of file MotorVelocityTest.ino.
right_motor
Motor right_motor
Definition at line 5 of file MotorVelocityTest.ino.
upDown
bool upDown =false
Definition at line 6 of file MotorVelocityTest.ino.
Referenced by loop().