RBE1001Lib: examples/week01/motor_position/motor_position.ino File Reference
motor_position.ino File Reference
#include <Arduino.h>
#include <RBE1001Lib.h>
Functions
void setup ()
void loop ()
Variables
Motor motor1
Motor motor2
const int buttonPin = 0
Function Documentation
loop()
void loop ()
Definition at line 38 of file motor_position.ino.
References buttonPin, Motor::getCurrentDegrees(), and Motor::MoveTo().
setup()
void setup ()
Definition at line 21 of file motor_position.ino.
References Motor::allocateTimer(), Motor::attach(), buttonPin, MOTOR1_DIR, MOTOR1_ENCA, MOTOR1_ENCB, MOTOR1_PWM, MOTOR2_DIR, MOTOR2_ENCA, MOTOR2_ENCB, and MOTOR2_PWM.
Variable Documentation
buttonPin
const int buttonPin = 0
Definition at line 15 of file motor_position.ino.
Referenced by loop(), and setup().
motor1
Motor motor1
Definition at line 12 of file motor_position.ino.
motor2
Motor motor2
Definition at line 13 of file motor_position.ino.