RBE1001Lib: examples/MotorSpinExample/MotorSpinExample.ino File Reference
MotorSpinExample.ino File Reference
#include <Arduino.h>
#include <RBE1001Lib.h>
Functions
void setup ()
void loop ()
Variables
const int buttonPin = BOOT_FLAG_PIN
Motor left_motor
Motor right_motor
bool upDown =false
Function Documentation
loop()
void loop ()
Definition at line 29 of file MotorSpinExample.ino.
References buttonPin, Motor::getDegreesPerSecond(), Motor::getEffortPercent(), and Motor::setSpeed().
setup()
void setup ()
Definition at line 15 of file MotorSpinExample.ino.
References Motor::allocateTimer(), Motor::attach(), MOTOR_LEFT_DIR, MOTOR_LEFT_ENCA, MOTOR_LEFT_ENCB, MOTOR_LEFT_PWM, MOTOR_RIGHT_DIR, MOTOR_RIGHT_ENCA, MOTOR_RIGHT_ENCB, and MOTOR_RIGHT_PWM.
Variable Documentation
buttonPin
const int buttonPin = BOOT_FLAG_PIN
Definition at line 6 of file MotorSpinExample.ino.
Referenced by loop().
left_motor
Motor left_motor
Definition at line 8 of file MotorSpinExample.ino.
right_motor
Motor right_motor
Definition at line 9 of file MotorSpinExample.ino.
upDown
bool upDown =false
Definition at line 10 of file MotorSpinExample.ino.