RBE1001Lib: examples/MotorSpeedTest/MotorSpeedTest.ino File Reference
MotorSpeedTest.ino File Reference
#include <Arduino.h>
#include <RBE1001Lib.h>
Functions
void setup ()
void loop ()
Variables
Motor left_motor
Motor right_motor
bool upDown =false
Function Documentation
loop()
void loop ()
Definition at line 25 of file MotorSpeedTest.ino.
References Motor::getDegreesPerSecond(), and Motor::setSpeed().
setup()
void setup ()
Definition at line 11 of file MotorSpeedTest.ino.
References Motor::allocateTimer(), Motor::attach(), MOTOR_LEFT_DIR, MOTOR_LEFT_ENCA, MOTOR_LEFT_ENCB, MOTOR_LEFT_PWM, MOTOR_RIGHT_DIR, MOTOR_RIGHT_ENCA, MOTOR_RIGHT_ENCB, and MOTOR_RIGHT_PWM.
Variable Documentation
left_motor
Motor left_motor
Definition at line 4 of file MotorSpeedTest.ino.
right_motor
Motor right_motor
Definition at line 5 of file MotorSpeedTest.ino.
upDown
bool upDown =false
Definition at line 6 of file MotorSpeedTest.ino.