RBE1001Lib: /home/hephaestus/git/ESP32Servo/examples/Multiple-Servo-Example-Arduino/Multiple-Servo-Example-Arduino.ino File Reference
Multiple-Servo-Example-Arduino.ino File Reference
#include <ESP32Servo.h>
Functions
void setup ()
void loop ()
Variables
Servo servo1
Servo servo2
Servo servo3
Servo servo4
Servo servo5
int minUs = 1000
int maxUs = 2000
int servo1Pin = 15
int servo2Pin = 16
int servo3Pin = 14
int servo4Pin = 32
int servo5Pin = 4
int pos = 0
ESP32PWM pwm
Function Documentation
loop()
void loop ()
Definition at line 74 of file Multiple-Servo-Example-Arduino.ino.
References Servo::attach(), ESP32PWM::attachPin(), Servo::detach(), ESP32PWM::detachPin(), maxUs, minUs, pos, servo1Pin, servo2Pin, servo3Pin, servo4Pin, and Servo::write().
setup()
void setup ()
Definition at line 58 of file Multiple-Servo-Example-Arduino.ino.
References ESP32PWM::allocateTimer(), and Servo::setPeriodHertz().
Variable Documentation
maxUs
int maxUs = 2000
Definition at line 46 of file Multiple-Servo-Example-Arduino.ino.
Referenced by loop().
minUs
int minUs = 1000
Definition at line 45 of file Multiple-Servo-Example-Arduino.ino.
Referenced by loop().
pos
int pos = 0
Definition at line 56 of file Multiple-Servo-Example-Arduino.ino.
Referenced by loop().
pwm
ESP32PWM pwm
Definition at line 57 of file Multiple-Servo-Example-Arduino.ino.
Referenced by ESP32PWM::adjustFrequency(), ESP32PWM::checkFrequencyForSideEffects(), and ESP32PWM::writeTone().
servo1
Servo servo1
Definition at line 39 of file Multiple-Servo-Example-Arduino.ino.
servo1Pin
int servo1Pin = 15
Definition at line 50 of file Multiple-Servo-Example-Arduino.ino.
Referenced by loop().
servo2
Servo servo2
Definition at line 40 of file Multiple-Servo-Example-Arduino.ino.
servo2Pin
int servo2Pin = 16
Definition at line 51 of file Multiple-Servo-Example-Arduino.ino.
Referenced by loop().
servo3
Servo servo3
Definition at line 41 of file Multiple-Servo-Example-Arduino.ino.
servo3Pin
int servo3Pin = 14
Definition at line 52 of file Multiple-Servo-Example-Arduino.ino.
Referenced by loop().
servo4
Servo servo4
Definition at line 42 of file Multiple-Servo-Example-Arduino.ino.
servo4Pin
int servo4Pin = 32
Definition at line 53 of file Multiple-Servo-Example-Arduino.ino.
Referenced by loop().
servo5
Servo servo5
Definition at line 43 of file Multiple-Servo-Example-Arduino.ino.
servo5Pin
int servo5Pin = 4
Definition at line 54 of file Multiple-Servo-Example-Arduino.ino.