RBE1001Lib: /home/hephaestus/git/ESP32Servo/examples/PWMExample/PWMExample.ino File Reference
PWMExample.ino File Reference
#include <ESP32Servo.h>
Functions
void setup ()
void loop ()
Variables
int APin = 13
ESP32PWM pwm
int freq = 1000
Function Documentation
loop()
void loop ()
Definition at line 15 of file PWMExample.ino.
References ESP32PWM::adjustFrequency(), freq, and ESP32PWM::writeScaled().
setup()
void setup ()
Definition at line 5 of file PWMExample.ino.
References ESP32PWM::allocateTimer(), APin, ESP32PWM::attachPin(), and freq.
Variable Documentation
APin
int APin = 13
Definition at line 2 of file PWMExample.ino.
Referenced by setup().
freq
int freq = 1000
Definition at line 4 of file PWMExample.ino.
Referenced by ESP32PWM::adjustFrequencyLocal(), ESP32PWM::allocatenext(), ESP32PWM::checkFrequencyForSideEffects(), loop(), ESP32PWM::mapf(), and setup().
pwm
ESP32PWM pwm
Definition at line 3 of file PWMExample.ino.