RBE1001Lib: examples/RangeFinderTest/RangeFinderTest.ino File Reference
RangeFinderTest.ino File Reference
#include <Arduino.h>
#include <RBE1001Lib.h>
#include "Rangefinder.h"
Functions
void setup ()
void loop ()
Variables
Rangefinder rangefinder1
Function Documentation
loop()
void loop ()
Definition at line 25 of file RangeFinderTest.ino.
References Rangefinder::getDistanceCM(), and Rangefinder::getTimeoutState().
setup()
void setup ()
Definition at line 10 of file RangeFinderTest.ino.
References Rangefinder::attach(), SIDE_ULTRASONIC_ECHO, and SIDE_ULTRASONIC_TRIG.
Variable Documentation
rangefinder1
Rangefinder rangefinder1
Definition at line 4 of file RangeFinderTest.ino.