RBE1001Lib: src/Rangefinder.cpp File Reference
Rangefinder.cpp File Reference
#include "Rangefinder.h"
#include "Timer.h"
Functions
void onTimer (void *param)
void IRAM_ATTR sensorISR0 ()
void IRAM_ATTR sensorISR1 ()
void IRAM_ATTR sensorISR2 ()
void IRAM_ATTR sensorISR3 ()
Variables
static TaskHandle_t complexHandlerTaskUS
static long threadTimeout
Function Documentation
onTimer()
void onTimer (void * param)
Definition at line 27 of file Rangefinder.cpp.
References Rangefinder::checkTimeout(), Rangefinder::fire(), Rangefinder::forceFire, and threadTimeout.
Referenced by Rangefinder::attach().
sensorISR0()
void IRAM_ATTR sensorISR0 ()
Definition at line 56 of file Rangefinder.cpp.
References Rangefinder::sensorISR().
Referenced by Rangefinder::attach().
sensorISR1()
void IRAM_ATTR sensorISR1 ()
Definition at line 59 of file Rangefinder.cpp.
References Rangefinder::sensorISR().
Referenced by Rangefinder::attach().
sensorISR2()
void IRAM_ATTR sensorISR2 ()
Definition at line 62 of file Rangefinder.cpp.
References Rangefinder::sensorISR().
Referenced by Rangefinder::attach().
sensorISR3()
void IRAM_ATTR sensorISR3 ()
Definition at line 65 of file Rangefinder.cpp.
References Rangefinder::sensorISR().
Referenced by Rangefinder::attach().
Variable Documentation
complexHandlerTaskUS
TaskHandle_t complexHandlerTaskUS static
Definition at line 5 of file Rangefinder.cpp.
Referenced by Rangefinder::attach().
threadTimeout
long threadTimeout static
Definition at line 14 of file Rangefinder.cpp.
Referenced by Rangefinder::fire(), Rangefinder::getTimeoutState(), and onTimer().