RBE1001Lib: examples/RCCTL/RCCTL.ino File Reference
RCCTL.ino File Reference
#include <Arduino.h>
#include <RBE1001Lib.h>
#include "Motor.h"
#include "Rangefinder.h"
#include <ESP32Servo.h>
#include <ESP32AnalogRead.h>
#include <Esp32WifiManager.h>
#include "wifi/WifiManager.h"
#include "WebPage.h"
#include <Timer.h>
Functions
void setup ()
void runStateMachine ()
void updateDashboard ()
void loop ()
Variables
LeftMotor left_motor
RightMotor right_motor
Rangefinder rangefinder1
Servo lifter
ESP32AnalogRead leftLineSensor
ESP32AnalogRead rightLineSensor
ESP32AnalogRead servoPositionFeedback
WebPage control_page
WifiManager manager
Timer dashboardUpdateTimer
int inc = 0
uint32_t packet_old = 0
Function Documentation
loop()
void loop ()
Definition at line 171 of file RCCTL.ino.
References manager, runStateMachine(), and updateDashboard().
runStateMachine()
void runStateMachine ()
Definition at line 99 of file RCCTL.ino.
References control_page, WebPage::getJoystickX(), WebPage::getJoystickY(), WebPage::getSliderValue(), left_motor, lifter, right_motor, and Motor::setSpeed().
Referenced by loop().
setup()
void setup ()
Definition at line 69 of file RCCTL.ino.
References Rangefinder::attach(), control_page, dashboardUpdateTimer, WebPage::initalize(), LEFT_LINE_SENSE, leftLineSensor, lifter, manager, rangefinder1, Timer::reset(), RIGHT_LINE_SENSE, rightLineSensor, SERVO_FEEDBACK_SENSOR, SERVO_PIN, servoPositionFeedback, SIDE_ULTRASONIC_ECHO, and SIDE_ULTRASONIC_TRIG.
updateDashboard()
void updateDashboard ()
Definition at line 118 of file RCCTL.ino.
References control_page, dashboardUpdateTimer, Motor::getCurrentDegrees(), Motor::getDegreesPerSecond(), Rangefinder::getDistanceCM(), Motor::getEffortPercent(), Timer::getMS(), WebPage::getSliderValue(), inc, left_motor, leftLineSensor, rangefinder1, Timer::reset(), right_motor, rightLineSensor, WebPage::rxPacketCount, WebPage::setValue(), and WebPage::txPacketCount.
Referenced by loop().
Variable Documentation
control_page
WebPage control_page
Definition at line 24 of file RCCTL.ino.
Referenced by runStateMachine(), setup(), and updateDashboard().
dashboardUpdateTimer
Timer dashboardUpdateTimer
Definition at line 28 of file RCCTL.ino.
Referenced by setup(), and updateDashboard().
inc
int inc = 0
Definition at line 68 of file RCCTL.ino.
Referenced by updateDashboard().
left_motor
LeftMotor left_motor
Definition at line 13 of file RCCTL.ino.
Referenced by runStateMachine(), and updateDashboard().
leftLineSensor
ESP32AnalogRead leftLineSensor
Definition at line 20 of file RCCTL.ino.
Referenced by setup(), and updateDashboard().
lifter
Servo lifter
Definition at line 18 of file RCCTL.ino.
Referenced by runStateMachine(), and setup().
manager
WifiManager manager
Definition at line 26 of file RCCTL.ino.
Referenced by loop(), and setup().
packet_old
uint32_t packet_old = 0
Definition at line 117 of file RCCTL.ino.
rangefinder1
Rangefinder rangefinder1
Definition at line 16 of file RCCTL.ino.
Referenced by setup(), and updateDashboard().
right_motor
RightMotor right_motor
Definition at line 14 of file RCCTL.ino.
Referenced by runStateMachine(), and updateDashboard().
rightLineSensor
ESP32AnalogRead rightLineSensor
Definition at line 21 of file RCCTL.ino.
Referenced by setup(), and updateDashboard().
servoPositionFeedback
ESP32AnalogRead servoPositionFeedback
Definition at line 22 of file RCCTL.ino.
Referenced by setup().