RBE1001Lib: examples/Servo/Servo.ino File Reference
Servo.ino File Reference
#include <RBE1001Lib.h>
#include <ESP32Servo.h>
#include <ESP32AnalogRead.h>
Functions
void setup ()
void loop ()
Variables
Servo lifter
ESP32AnalogRead servoPositionFeedback
Function Documentation
loop()
void loop ()
Definition at line 25 of file Servo.ino.
References Servo::write().
setup()
void setup ()
Definition at line 11 of file Servo.ino.
References ESP32AnalogRead::attach(), Servo::attach(), SERVO_FEEDBACK_SENSOR, SERVO_PIN, and Servo::write().
Variable Documentation
lifter
Servo lifter
Definition at line 6 of file Servo.ino.
servoPositionFeedback
ESP32AnalogRead servoPositionFeedback
Definition at line 8 of file Servo.ino.