RBE1001Lib: src/SimpleWebServer.cpp File Reference
SimpleWebServer.cpp File Reference
#include <WebServer.h>
#include <HTTP_Method.h>
#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiServer.h>
#include <ESPmDNS.h>
#include <Esp32WifiManager.h>
#include "wifi/WifiManager.h"
#include "SimpleWebServer.h"
Functions
static WebServer server (80)
Variables
WifiManager manager
Function Documentation
server()
static WebServer server (80) static
Referenced by SimpleWebServer::handleClient(), SimpleWebServer::initialize(), SimpleWebServer::registerHandler(), SimpleWebServer::sendHTMLResponse(), and SimpleWebServer::sendResponse().
Variable Documentation
manager
WifiManager manager
Definition at line 13 of file SimpleWebServer.cpp.