RBE1001Lib: src/ESPAsyncWebServer/SPIFFSEditor.cpp File Reference
SPIFFSEditor.cpp File Reference
#include "SPIFFSEditor.h"
#include <FS.h>
Data Structures
struct ExcludeListS
Macros
#define edit_htm_gz_len 4151
#define SPIFFS_MAXLENGTH_FILEPATH 32
Typedefs
typedef struct ExcludeListS ExcludeList
Functions
static bool matchWild (const char *pattern, const char *testee)
static bool addExclude (const char *item)
static void loadExcludeList (fs::FS &_fs, const char *filename)
static bool isExcluded (fs::FS &_fs, const char *filename)
Variables
const uint8_t edit_htm_gz [] PROGMEM
const char * excludeListFile = "/.exclude.files"
static ExcludeList * excludes = NULL
Macro Definition Documentation
edit_htm_gz_len
#define edit_htm_gz_len 4151
Definition at line 5 of file SPIFFSEditor.cpp.
Referenced by SPIFFSEditor::handleRequest().
SPIFFS_MAXLENGTH_FILEPATH
#define SPIFFS_MAXLENGTH_FILEPATH 32
Definition at line 269 of file SPIFFSEditor.cpp.
Referenced by loadExcludeList().
Typedef Documentation
ExcludeList
typedef struct ExcludeListS ExcludeList
Function Documentation
addExclude()
static bool addExclude (const char * item) static
Definition at line 301 of file SPIFFSEditor.cpp.
References excludes, ExcludeListS::item, and ExcludeListS::next.
Referenced by loadExcludeList().
isExcluded()
static bool isExcluded (fs::FS & _fs, const char * filename) static
Definition at line 363 of file SPIFFSEditor.cpp.
References excludeListFile, excludes, ExcludeListS::item, loadExcludeList(), matchWild(), ExcludeListS::next, and SPIFFSEditor::SPIFFSEditor().
Referenced by SPIFFSEditor::handleRequest().
loadExcludeList()
static void loadExcludeList (fs::FS & _fs, const char * filename) static
Definition at line 321 of file SPIFFSEditor.cpp.
References addExclude(), and SPIFFS_MAXLENGTH_FILEPATH.
Referenced by isExcluded().
matchWild()
static bool matchWild (const char * pattern, const char * testee) static
Definition at line 279 of file SPIFFSEditor.cpp.
Referenced by isExcluded().
Variable Documentation
excludeListFile
const char* excludeListFile = "/.exclude.files"
Definition at line 270 of file SPIFFSEditor.cpp.
Referenced by isExcluded().
excludes
ExcludeList* excludes = NULL static
Definition at line 277 of file SPIFFSEditor.cpp.
Referenced by addExclude(), and isExcluded().
PROGMEM
const uint8_t edit_htm_gz [] PROGMEM
Definition at line 6 of file SPIFFSEditor.cpp.