RBE1001Lib: examples/UltrasonicProject/UltrasonicProject.ino File Reference
UltrasonicProject.ino File Reference
#include "ESP32Encoder.h"
#include "ESP32Servo.h"
#include "RBE1001Lib.h"
#include <Arduino.h>
Functions
void setup ()
void setEfforts (float left, float right)
void setEfforts (float both)
void loop ()
Variables
Motor motor1
Motor motor2
Rangefinder rangeFinder
Function Documentation
loop()
void loop ()
Definition at line 28 of file UltrasonicProject.ino.
References Rangefinder::getDistanceCM(), and setEfforts().
setEfforts() [1/2]
void setEfforts (float left, float right)
Definition at line 19 of file UltrasonicProject.ino.
References Motor::SetEffort().
Referenced by loop(), and setEfforts().
setEfforts() [2/2]
void setEfforts (float both)
Definition at line 24 of file UltrasonicProject.ino.
References setEfforts().
setup()
void setup ()
Definition at line 10 of file UltrasonicProject.ino.
References Motor::allocateTimer(), Rangefinder::attach(), Motor::attach(), MOTOR1_DIR, MOTOR1_ENCA, MOTOR1_ENCB, MOTOR1_PWM, MOTOR2_DIR, MOTOR2_ENCA, MOTOR2_ENCB, and MOTOR2_PWM.
Variable Documentation
motor1
Motor motor1
Definition at line 6 of file UltrasonicProject.ino.
motor2
Motor motor2
Definition at line 7 of file UltrasonicProject.ino.
rangeFinder
Rangefinder rangeFinder
Definition at line 8 of file UltrasonicProject.ino.