RBE1001Lib: src/ESPAsyncWebServer/WebAuthentication.h File Reference
WebAuthentication.h File Reference
#include "Arduino.h"
Functions
bool checkBasicAuthentication (const char *header, const char *username, const char *password)
String requestDigestAuthentication (const char *realm)
bool checkDigestAuthentication (const char *header, const char *method, const char *username, const char *password, const char *realm, bool passwordIsHash, const char *nonce, const char *opaque, const char *uri)
String generateDigestHash (const char *username, const char *password, const char *realm)
Function Documentation
checkBasicAuthentication()
bool checkBasicAuthentication (const char * header, const char * username, const char * password)
Definition at line 32 of file WebAuthentication.cpp.
Referenced by AsyncWebServerRequest::authenticate().
checkDigestAuthentication()
bool checkDigestAuthentication (const char * header, const char * method, const char * username, const char * password, const char * realm, bool passwordIsHash, const char * nonce, const char * opaque, const char * uri)
Definition at line 144 of file WebAuthentication.cpp.
References stringMD5().
Referenced by AsyncWebServerRequest::authenticate().
generateDigestHash()
String generateDigestHash (const char * username, const char * password, const char * realm)
Definition at line 112 of file WebAuthentication.cpp.
References getMD5().
requestDigestAuthentication()
String requestDigestAuthentication (const char * realm)
Definition at line 130 of file WebAuthentication.cpp.
References genRandomMD5().
Referenced by AsyncWebServerRequest::requestAuthentication().