RBE1001Lib: src/ESPAsyncWebServer/WebAuthentication.cpp File Reference
WebAuthentication.cpp File Reference
#include "WebAuthentication.h"
#include <libb64/cencode.h>
#include "md5.h"
Functions
bool checkBasicAuthentication (const char *hash, const char *username, const char *password)
static bool getMD5 (uint8_t *data, uint16_t len, char *output)
static String genRandomMD5 ()
static String stringMD5 (const String &in)
String generateDigestHash (const char *username, const char *password, const char *realm)
String requestDigestAuthentication (const char *realm)
bool checkDigestAuthentication (const char *header, const char *method, const char *username, const char *password, const char *realm, bool passwordIsHash, const char *nonce, const char *opaque, const char *uri)
Function Documentation
checkBasicAuthentication()
bool checkBasicAuthentication (const char * hash, const char * username, const char * password)
Definition at line 32 of file WebAuthentication.cpp.
Referenced by AsyncWebServerRequest::authenticate().
checkDigestAuthentication()
bool checkDigestAuthentication (const char * header, const char * method, const char * username, const char * password, const char * realm, bool passwordIsHash, const char * nonce, const char * opaque, const char * uri)
Definition at line 144 of file WebAuthentication.cpp.
References stringMD5().
Referenced by AsyncWebServerRequest::authenticate().
generateDigestHash()
String generateDigestHash (const char * username, const char * password, const char * realm)
Definition at line 112 of file WebAuthentication.cpp.
References getMD5().
genRandomMD5()
static String genRandomMD5 () static
Definition at line 89 of file WebAuthentication.cpp.
References getMD5().
Referenced by requestDigestAuthentication().
getMD5()
static bool getMD5 (uint8_t * data, uint16_t len, char * output) static
Definition at line 61 of file WebAuthentication.cpp.
Referenced by generateDigestHash(), genRandomMD5(), and stringMD5().
requestDigestAuthentication()
String requestDigestAuthentication (const char * realm)
Definition at line 130 of file WebAuthentication.cpp.
References genRandomMD5().
Referenced by AsyncWebServerRequest::requestAuthentication().
stringMD5()
static String stringMD5 (const String & in) static
Definition at line 103 of file WebAuthentication.cpp.
References getMD5().
Referenced by checkDigestAuthentication().