RBE1001Lib: src/WebPage.cpp File Reference
WebPage.cpp File Reference
#include <Arduino.h>
#include <WebServer.h>
#include <HTTP_Method.h>
#include "WebPage.h"
#include "static/indexhtml.h"
#include "static/nipplejsminjs.h"
#include <ESPAsyncWebServer/ESPAsyncWebServer.h>
#include "Motor.h"
#include "RBE1001Lib.h"
Functions
const String js (nipplejs_min_js)
const String myHTML (index_html)
void onWsEvent (AsyncWebSocket *server, AsyncWebSocketClient *client, AwsEventType type, void *arg, uint8_t *data, size_t len)
char * String2Chars (String str)
bool isSafeToSend ()
void lock ()
void unlock ()
void updateTask (void *param)
Variables
AsyncWebServer server (80)
AsyncWebSocket ws ("/test")
static WebPage * thisPage
static char stringBuffer [200]
const String updtime ="Uptime"
static bool lockOutSending = false
long timeSinceLastSend =0
Function Documentation
isSafeToSend()
bool isSafeToSend ()
Definition at line 137 of file WebPage.cpp.
References lockOutSending, and timeSinceLastSend.
Referenced by lock().
js()
const String js (nipplejs_min_js)
Referenced by WebPage::initalize().
lock()
void lock ()
Definition at line 143 of file WebPage.cpp.
References isSafeToSend(), and lockOutSending.
Referenced by WebPage::initalize(), and updateTask().
myHTML()
const String myHTML (index_html)
Referenced by WebPage::initalize().
onWsEvent()
void onWsEvent (AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t * data, size_t len)
Definition at line 26 of file WebPage.cpp.
References WebPage::markAllDirty(), WebPage::rxPacketCount, WebPage::SendAllLabels(), WebPage::SendAllValues(), WebPage::setHeartbeatUUID(), WebPage::setJoystickValue(), WebPage::setSliderValue(), WS_EVT_CONNECT, WS_EVT_DATA, and WS_EVT_DISCONNECT.
Referenced by WebPage::initalize().
String2Chars()
char* String2Chars (String str)
Definition at line 115 of file WebPage.cpp.
References stringBuffer.
unlock()
void unlock ()
Definition at line 150 of file WebPage.cpp.
References lockOutSending, and timeSinceLastSend.
Referenced by WebPage::initalize(), and updateTask().
updateTask()
void updateTask (void * param)
Definition at line 157 of file WebPage.cpp.
References lock(), WebPage::SendAllLabels(), WebPage::SendAllValues(), WebPage::sendHeartbeat(), and unlock().
Referenced by WebPage::initalize().
Variable Documentation
lockOutSending
bool lockOutSending = false static
Definition at line 20 of file WebPage.cpp.
Referenced by isSafeToSend(), lock(), and unlock().
server
AsyncWebServer server(80)
Referenced by AsyncEventSourceClient::AsyncEventSourceClient(), AsyncEventSourceResponse::AsyncEventSourceResponse(), AsyncWebSocketResponse::AsyncWebSocketResponse(), and WebPage::initalize().
stringBuffer
char stringBuffer[200] static
Definition at line 14 of file WebPage.cpp.
Referenced by String2Chars().
thisPage
WebPage* thisPage static
Definition at line 13 of file WebPage.cpp.
timeSinceLastSend
long timeSinceLastSend =0
Definition at line 22 of file WebPage.cpp.
Referenced by isSafeToSend(), and unlock().
updtime
const String updtime ="Uptime"
Definition at line 16 of file WebPage.cpp.
ws
AsyncWebSocket ws("/test")
Referenced by WebPage::initalize(), WebPage::SendAllLabels(), WebPage::SendAllValues(), and WebPage::sendHeartbeat().