RBE1001Lib: src/ESPAsyncWebServer/WebRequest.cpp File Reference
WebRequest.cpp File Reference
#include "ESPAsyncWebServer.h"
#include "WebResponseImpl.h"
#include "WebAuthentication.h"
Macros
#define os_strlen strlen
#define __is_param_char(c) ((c) && ((c) != '{') && ((c) != '[') && ((c) != '&') && ((c) != '='))
#define itemWriteByte(b) do { _itemSize++; if(_itemIsFile) _handleUploadByte(b, last); else _itemValue+=(char)(b); } while(0)
Enumerations
enum {
PARSE_REQ_START, PARSE_REQ_HEADERS, PARSE_REQ_BODY, PARSE_REQ_END,
PARSE_REQ_FAIL
}
enum {
EXPECT_BOUNDARY, PARSE_HEADERS, WAIT_FOR_RETURN1, EXPECT_FEED1,
EXPECT_DASH1, EXPECT_DASH2, BOUNDARY_OR_DATA, DASH3_OR_RETURN2,
EXPECT_FEED2, PARSING_FINISHED, PARSE_ERROR
}
Functions
bool strContains (String src, String find, bool mindcase=true)
Variables
static const String SharedEmptyString = String()
Macro Definition Documentation
__is_param_char
#define __is_param_char (c) ((c) && ((c) != '{') && ((c) != '[') && ((c) != '&') && ((c) != '='))
Definition at line 31 of file WebRequest.cpp.
Referenced by AsyncWebServerRequest::_onData().
itemWriteByte
#define itemWriteByte (b) do { _itemSize++; if(_itemIsFile) _handleUploadByte(b, last); else _itemValue+=(char)(b); } while(0)
Referenced by AsyncWebServerRequest::_parseMultipartPostByte().
os_strlen
#define os_strlen strlen
Definition at line 26 of file WebRequest.cpp.
Referenced by AsyncWebServerRequest::_parseLine().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PARSE_REQ_START
PARSE_REQ_HEADERS
PARSE_REQ_BODY
PARSE_REQ_END
PARSE_REQ_FAIL
Definition at line 33 of file WebRequest.cpp.
anonymous enum
anonymous enum
Enumerator
EXPECT_BOUNDARY
PARSE_HEADERS
WAIT_FOR_RETURN1
EXPECT_FEED1
EXPECT_DASH1
EXPECT_DASH2
BOUNDARY_OR_DATA
DASH3_OR_RETURN2
EXPECT_FEED2
PARSING_FINISHED
PARSE_ERROR
Definition at line 380 of file WebRequest.cpp.
Function Documentation
strContains()
bool strContains (String src, String find, bool mindcase = true)
Definition at line 294 of file WebRequest.cpp.
References pos.
Referenced by AsyncWebServerRequest::_parseReqHeader().
Variable Documentation
SharedEmptyString
const String SharedEmptyString = String() static
Definition at line 29 of file WebRequest.cpp.
Referenced by AsyncWebServerRequest::arg(), AsyncWebServerRequest::header(), AsyncWebServerRequest::headerName(), and AsyncWebServerRequest::pathArg().