RBE1001Lib: src/ESPAsyncWebServer/WebServer.cpp File Reference
WebServer.cpp File Reference
#include "ESPAsyncWebServer.h"
#include "WebHandlerImpl.h"
Functions
bool ON_STA_FILTER (AsyncWebServerRequest *request)
bool ON_AP_FILTER (AsyncWebServerRequest *request)
Function Documentation
ON_AP_FILTER()
bool ON_AP_FILTER (AsyncWebServerRequest * request)
Definition at line 28 of file WebServer.cpp.
References AsyncWebServerRequest::client(), and AsyncClient::localIP().
ON_STA_FILTER()
bool ON_STA_FILTER (AsyncWebServerRequest * request)
Definition at line 24 of file WebServer.cpp.
References AsyncWebServerRequest::client(), and AsyncClient::localIP().